import LieRings.DimensionSubring.DegreeTwo
import LieRings.UniversalEnveloping.Quotient

/-!
# Small examples: Lie quotients and the second dimension subring

These examples show the public statements with the same notation used in mathematics.
-/

namespace LieRings.Examples

universe u

variable (F : Type u) [LieRing F] [LieAlgebra ℤ F]

/-- `U(F/R) ≃ U(F)/r`, where `r` is the two-sided ideal generated by the image of `R`. -/
noncomputable example (R : LieIdeal ℤ F) :
    letI : LieAlgebra ℤ (F ⧸ R) :=
      LieSubmodule.Quotient.lieQuotientLieAlgebra R
    UEA ℤ (F ⧸ R) ≃ₐ[ℤ] UEA ℤ F ⧸ UEA.idealOfLieIdeal ℤ F R :=
  UEA.quotientEquivLieIdeal ℤ F R

/-- In conventional notation this is exactly `delta_2(F) = gamma_2(F)`. -/
example : dimensionSubring ℤ F 2 = lowerCentralSeries ℤ F 1 :=
  dimensionSubring_two_eq_lowerCentralSeries_one ℤ F

end LieRings.Examples
