import LieRings.DimensionSubring.MetabelianVanishing.FactorCollector

#check LieRings.MetabelianVanishing.triangularTaggedExpansionList
#check LieRings.MetabelianVanishing.triangularRelationRightBracket
#check LieRings.MetabelianVanishing.triangularPlacedExpansion
#check LieRings.MetabelianVanishing.rowTail_cutoff
#check LieRings.MetabelianVanishing.QuotientWeightRow.factorCount
#check LieRings.MetabelianVanishing.QuotientWeightRow.marked
