import LieRings.Homological.QuadraticUCT
#check Finset.dvd_prod_of_mem
#check Finset.prod_pos
#check Finset.prod_pos
#check Nat.mul_div_cancel'
#check Nat.div_mul_cancel
#check Finsupp.single_apply
#check Module.Basis.repr_self
#check Finset.sum_ite_irrel
#check Finset.sum_ite_eq'
