import LieRings.DimensionSubring.MetabelianOdd.Assembly
#check Multiset.pairwise_sort
#check List.pairwise_append
#check List.Pairwise.sublist
#check List.pairwise_append_comm
#check List.pairwise_cons
#check List.pairwise_cons.1
#check List.pairwise_cons.2
#check List.pairwise_append.1
#check List.pairwise_append.2
#check List.rel_get_of_rel
#check List.rel_get
#check List.pairwise_iff_get
#check List.pairwise_iff_getElem
#check List.pairwise_reverse
#check List.reverse_pairwise
#check List.get_mem
#check Finsupp.sum_apply
#check Finset.sum_eq_zero
#check List.reverse_eq_cons_iff
#check List.eq_reverse_cons
#check List.getLast_le_of_pairwise
#check List.rel_getLast_of_rel
