import LieRings.DimensionSubring.MetabelianVanishing.StepSeven

/-!
# EXPERIMENTAL ONLY: provenance-stage trace toward Points 1.1 and 1.2

This root-level file is deliberately not imported by the library.  It tests
the exact dependency boundary between Points 1.1 and 1.2.

The governing external word is expanded into the finite provenance seed, the
existing provenance rewrite system is exposed with coverage, preservation,
and termination theorems, and a finite locally sound trace is generated by
well-founded recursion.  Canonical path tags then prove the structural Stokes
identity for that trace.  This file contains no proof holes.

This is not yet the complete Point-1 trace required by the plan.  In
particular, the provenance collector stops at component leaves before the
component PBW continuation, terminal preceding-prefix realization, and final
four-constructor classification.  Thus the declarations below are completed
infrastructure for Points 1.1 and 1.2, not completion of those plan items.
-/

namespace LieRings.MetabelianVanishing.ExperimentalPoint12

open FreeMetabelian LieRings.PBW

universe u v

noncomputable section

variable (n : ℕ) (L : Type u) [LieRing L] [Finite L]
variable (data : CyclicTopData n L)
variable (hn : 2 ≤ n)

local instance experimentalPoint12Fintype : Fintype L := Fintype.ofFinite L

abbrev Occurrence := UEA ℤ (FreeModel n L)

/-! ## The exact output type of Point 1.1 -/

/-- The kind of a local closed-square rewrite.  This tag is bookkeeping
only; no cancellation or terminal assertion is stored in it. -/
inductive RewriteKind where
  | root
  | horizontal
  | vertical
  | truncation
  | diagonal
  | precedingPrefix
  deriving DecidableEq

/- Traces and their finite signed child forests.  The first-child/next-
sibling representation gives Lean structural recursion without requiring
any well-foundedness assumption from Point 1.1. -/
mutual
  inductive RewriteTrace (M : Type v) where
    | leaf (word : M)
    | node (kind : RewriteKind) (word : M) (children : RewriteForest M)

  inductive RewriteForest (M : Type v) where
    | nil
    | cons (coefficient : ℤ) (trace : RewriteTrace M) (tail : RewriteForest M)
end

namespace RewriteTrace

/-- The literal word at the root of a trace. -/
def rootWord {M : Type v} : RewriteTrace M → M
  | .leaf word => word
  | .node _ word _ => word

end RewriteTrace

namespace RewriteForest

/-- The signed sum of the literal words immediately output by a node. -/
def immediateValue {M : Type v} [AddCommGroup M] :
    RewriteForest M → M
  | .nil => 0
  | .cons coefficient trace tail =>
      coefficient • trace.rootWord + immediateValue tail

end RewriteForest

/- Every node is a genuine local rewrite and every continuation is locally
sound.  This is deliberately only a recursive collection of local
equalities. -/
mutual
  def RewriteTrace.LocallySound {M : Type v} [AddCommGroup M] :
      RewriteTrace M → Prop
    | .leaf _ => True
    | .node _ word children =>
        children.immediateValue = word ∧ children.LocallySound

  def RewriteForest.LocallySound {M : Type v} [AddCommGroup M] :
      RewriteForest M → Prop
    | .nil => True
    | .cons _ trace tail => trace.LocallySound ∧ tail.LocallySound
end

/-- Point 1.1 returns a trace whose root is specified by the type and whose
only proof field is recursive local rewrite soundness. -/
structure PointOneOneTrace {M : Type v} [AddCommGroup M]
    (root : M) where
  trace : RewriteTrace M
  root_eq : trace.rootWord = root
  locallySound : trace.LocallySound

/-! ### Point 1.1.1: the exact root seed forest -/

/-- Expand the already grouped external relation-on-the-left rows into the
same provenance-preserving PBW rows consumed by `provenancedExpansion`.
Unlike `GoverningWitness.provenancedInitial`, this starts from `externalRows`,
so the grouped terminal one-factor relation has already been removed and the
result evaluates to the actual root `externalMarkedWord.word`, not to
`w.theta`. -/
def GoverningWitness.pointOneOneSeedRows {a : L}
    (w : GoverningWitness n L data a) :
    ProvenancedRow n L data hn →₀ ℤ :=
  (w.externalRows n L data hn).sum fun p z ↦
    z • provenancedRowsOfRightFactor n L data hn p.1 p.2

/-- Linear literal-word read of a finite family of provenance rows. -/
def pointOneOneSeedValue :
    (ProvenancedRow n L data hn →₀ ℤ) →ₗ[ℤ] Occurrence n L :=
  Finsupp.linearCombination ℤ (ProvenancedRow.value n L data hn)

/-- The seed Finsupp has exactly the governing root as its literal UEA value.
This is the root-to-seed identity required by Point 1.1.1. -/
theorem GoverningWitness.pointOneOneSeedRows_value {a : L}
    (w : GoverningWitness n L data a) :
    pointOneOneSeedValue n L data hn
        (GoverningWitness.pointOneOneSeedRows n L data hn w) =
      (w.externalMarkedWord n L data hn).word := by
  classical
  rw [GoverningWitness.pointOneOneSeedRows, map_finsuppSum]
  change (w.externalRows n L data hn).sum
      (fun p z ↦ pointOneOneSeedValue n L data hn
        (z • provenancedRowsOfRightFactor n L data hn p.1 p.2)) = _
  calc
    _ = (w.externalRows n L data hn).sum (fun p z ↦ z •
        (UniversalEnvelopingAlgebra.ι ℤ (p.1 : FreeModel n L) * p.2)) := by
      apply Finsupp.sum_congr
      intro p hp
      rw [map_zsmul]
      rw [show pointOneOneSeedValue n L data hn
          (provenancedRowsOfRightFactor n L data hn p.1 p.2) =
        (provenancedCollector n L data hn).evaluate
          (provenancedRowsOfRightFactor n L data hn p.1 p.2) by rfl]
      rw [evaluate_provenancedRowsOfRightFactor]
    _ = terminalPacketWord n L data (w.externalRows n L data hn) := rfl
    _ = (w.externalMarkedWord n L data hn).word := rfl

/-- Literal finite list of seed rows.  It contains one entry for every
nonzero coefficient of `pointOneOneSeedRows`; no choice of enumeration is
exposed to later points. -/
def GoverningWitness.pointOneOneSeedList {a : L}
    (w : GoverningWitness n L data a) :
    List (ℤ × ProvenancedRow n L data hn) :=
  LieRings.DegreeFive.finsuppTaggedList
    (GoverningWitness.pointOneOneSeedRows n L data hn w) id

/-- **POINT 1.1.1 COMPLETE.** The finite signed seed list has literal value
equal to the governing root. -/
theorem GoverningWitness.pointOneOneSeedList_value {a : L}
    (w : GoverningWitness n L data a) :
    ((GoverningWitness.pointOneOneSeedList n L data hn w).map fun q ↦
        q.1 • ProvenancedRow.value n L data hn q.2).sum =
      (w.externalMarkedWord n L data hn).word := by
  rw [GoverningWitness.pointOneOneSeedList,
    LieRings.DegreeFive.finsuppTaggedList_value_sum]
  exact GoverningWitness.pointOneOneSeedRows_value n L data hn w

/-! ### Point 1.1.2: the complete provenance rewrite system -/

/-- The rewrite system used by Point 1.1 is exactly the already verified
provenance-preserving collector.  Giving it a dedicated name freezes the
interface consumed by Point 1.1.3. -/
def pointOneOneRewriteSystem :
    LieRings.DegreeFive.FiniteTaggedCollector
      (ProvenancedRow n L data hn) (Occurrence n L) :=
  provenancedCollector n L data hn

/-- Bookkeeping kind of the next local rewrite.  A marked transfer is the
horizontal edge; a non-wall truncation emits the diagonal component; and a
component transfer is the vertical edge carrying the signed contextual
correction. -/
def pointOneOneRewriteKind : ProvenancedRow n L data hn → RewriteKind
  | .marked _ _ _ _ (_ :: _) => .horizontal
  | .marked _ _ _ _ [] => .truncation
  | .component _ _ _ _ _ => .vertical

/-- Concrete terminal predicate for the unified rewrite system.  Component
rows stop precisely at the left edge.  Marked rows stop precisely at one of
the two walls, after all right factors have transferred and while the mark is
still positive. -/
def PointOneOneExternal : ProvenancedRow n L data hn → Prop
  | .component _ _ _ left _ => left = []
  | .marked _ context mark left right =>
      right = [] ∧ 0 < mark.val ∧
        provenancedWall n L data hn context mark left = true

/-- A horizontal transfer.  The second child retains the full root relation
and records the complete preceding-prefix/context correction. -/
@[simp] theorem pointOneOneRewrite_horizontal
    (rho : Relations n L data) (context : RelationContext n L data hn)
    (mark : Fin (n + 2)) (left right : List (AdaptedIndex n L data hn))
    (x : AdaptedIndex n L data hn) :
    (pointOneOneRewriteSystem n L data hn).expansion
        (.marked rho context mark left (x :: right)) =
      some [(1, .marked rho context mark (left ++ [x]) right),
        (1, .marked rho (RelationContext.lieRight context x)
          mark left right)] := by
  rfl

/-- A vertical component transfer.  Its second child is the negatively
oriented contextual correction; this is the literal incidence that pairs
with the corresponding positive correction emitted horizontally. -/
@[simp] theorem pointOneOneRewrite_vertical
    (rho : Relations n L data) (context : RelationContext n L data hn)
    (mark : Fin (n + 2)) (left right : List (AdaptedIndex n L data hn))
    (x : AdaptedIndex n L data hn) :
    (pointOneOneRewriteSystem n L data hn).expansion
        (.component rho context mark (left ++ [x]) right) =
      some [(1, .component rho context mark left (x :: right)),
        (-1, .component rho (RelationContext.lieRight context x)
          mark left right)] := by
  change provenancedExpansion n L data hn
      (.component rho context mark (left ++ [x]) right) = _
  simp only [provenancedExpansion]
  split
  · rename_i hnil
    simp at hnil
  · rename_i y leftRev hcons
    have hshape : x :: left.reverse = y :: leftRev := by simpa using hcons
    injection hshape with hy htail
    subst y
    subst leftRev
    simp

/-- A non-wall truncation.  The first child lowers the prefix mark and the
second child is exactly the intermediate diagonal component at the old
mark. -/
theorem pointOneOneRewrite_truncation
    (rho : Relations n L data) (context : RelationContext n L data hn)
    (mark : Fin (n + 2)) (left : List (AdaptedIndex n L data hn))
    (hmark : 0 < mark.val)
    (hwall : provenancedWall n L data hn context mark left = false) :
    (pointOneOneRewriteSystem n L data hn).expansion
        (.marked rho context mark left []) =
      some [(1, .marked rho context
          ⟨mark.val - 1, by omega⟩ left []),
        (1, .component rho context mark left [])] := by
  simp [pointOneOneRewriteSystem, provenancedCollector,
    provenancedExpansion, Nat.ne_of_gt hmark, hwall]

/-- At mark zero the contextual prefix is zero, so the row has the empty
signed expansion rather than becoming an external leaf. -/
theorem pointOneOneRewrite_zeroMark
    (rho : Relations n L data) (context : RelationContext n L data hn)
    (mark : Fin (n + 2)) (left : List (AdaptedIndex n L data hn))
    (hmark : mark.val = 0) :
    (pointOneOneRewriteSystem n L data hn).expansion
        (.marked rho context mark left []) = some [] := by
  simp [pointOneOneRewriteSystem, provenancedCollector,
    provenancedExpansion, hmark]

/-- The above cases are exhaustive: `none` occurs exactly at a genuine
external stopping row, never at an unprocessed internal occurrence. -/
theorem pointOneOneRewrite_terminal_iff
    (row : ProvenancedRow n L data hn) :
    (pointOneOneRewriteSystem n L data hn).expansion row = none ↔
      PointOneOneExternal n L data hn row := by
  cases row with
  | component rho context mark left right =>
      change provenancedExpansion n L data hn
          (.component rho context mark left right) = none ↔ left = []
      constructor
      · intro h
        simp only [provenancedExpansion] at h
        split at h
        · rename_i hleft
          have hreverse := congrArg List.reverse hleft
          simpa using hreverse
        · contradiction
      · intro hleft
        subst left
        rfl
  | marked rho context mark left right =>
      cases right with
      | nil =>
          simp only [pointOneOneRewriteSystem, provenancedCollector,
            provenancedExpansion, PointOneOneExternal]
          by_cases hmark : mark.val = 0
          · simp [hmark]
          · have hmarkPos : 0 < mark.val := Nat.pos_of_ne_zero hmark
            by_cases hwall :
                provenancedWall n L data hn context mark left = true
            · simp [hmark, hmarkPos, hwall]
            · have hwallFalse :
                  provenancedWall n L data hn context mark left = false := by
                exact Bool.eq_false_of_not_eq_true hwall
              simp [hmark, hmarkPos, hwall]
      | cons x right =>
          simp [pointOneOneRewriteSystem, provenancedCollector,
            provenancedExpansion, PointOneOneExternal]

/-- The common lexicographic relation is well founded. -/
theorem pointOneOneRewrite_wellFounded :
    WellFounded (pointOneOneRewriteSystem n L data hn).relation :=
  (pointOneOneRewriteSystem n L data hn).wellFounded

/-- Every child of every nonterminal rewrite is strictly smaller in the
common provenance measure. -/
theorem pointOneOneRewrite_decreases
    {row : ProvenancedRow n L data hn}
    {children : List (ℤ × ProvenancedRow n L data hn)}
    (h : (pointOneOneRewriteSystem n L data hn).expansion row =
      some children) :
    ∀ child ∈ children,
      (pointOneOneRewriteSystem n L data hn).relation child.2 row :=
  (pointOneOneRewriteSystem n L data hn).decreases h

/-- Every local rewrite preserves the complete literal UEA word, with its
full relation and contextual provenance still attached. -/
theorem pointOneOneRewrite_preserves
    {row : ProvenancedRow n L data hn}
    {children : List (ℤ × ProvenancedRow n L data hn)}
    (h : (pointOneOneRewriteSystem n L data hn).expansion row =
      some children) :
    (children.map fun child ↦ child.1 •
        ProvenancedRow.value n L data hn child.2).sum =
      ProvenancedRow.value n L data hn row :=
  (pointOneOneRewriteSystem n L data hn).preserves h

/-! ### Point 1.1.3: routine finite recursion and packaging -/

/-- Convert a literal finite list of signed traces into the first-child/
next-sibling forest used by Point 1.2. -/
def RewriteForest.ofList {M : Type v} :
    List (ℤ × RewriteTrace M) → RewriteForest M
  | [] => .nil
  | branch :: branches => .cons branch.1 branch.2 (ofList branches)

@[simp] theorem RewriteForest.immediateValue_ofList
    {M : Type v} [AddCommGroup M]
    (branches : List (ℤ × RewriteTrace M)) :
    (RewriteForest.ofList branches).immediateValue =
      (branches.map fun branch ↦
        branch.1 • branch.2.rootWord).sum := by
  induction branches with
  | nil => rfl
  | cons branch branches ih =>
      simp [RewriteForest.ofList, RewriteForest.immediateValue, ih]

@[simp] theorem RewriteForest.locallySound_ofList_iff
    {M : Type v} [AddCommGroup M]
    (branches : List (ℤ × RewriteTrace M)) :
    (RewriteForest.ofList branches).LocallySound ↔
      ∀ branch ∈ branches, branch.2.LocallySound := by
  induction branches with
  | nil => simp [RewriteForest.ofList, RewriteForest.LocallySound]
  | cons branch branches ih =>
      simp [RewriteForest.ofList, RewriteForest.LocallySound, ih]

/-- One well-founded recursion layer.  It performs no mathematical work:
the chosen expansion, its decrease proof, and its local preservation theorem
all come from Point 1.1.2. -/
private def pointOneOneRowTraceStep
    (row : ProvenancedRow n L data hn)
    (rec : ∀ child,
      (pointOneOneRewriteSystem n L data hn).relation child row →
        RewriteTrace (Occurrence n L)) :
    RewriteTrace (Occurrence n L) :=
  match h : (pointOneOneRewriteSystem n L data hn).expansion row with
  | none => .leaf (ProvenancedRow.value n L data hn row)
  | some children =>
      .node (pointOneOneRewriteKind n L data hn row)
        (ProvenancedRow.value n L data hn row)
        (RewriteForest.ofList (children.attach.map fun child ↦
          (child.1.1, rec child.1.2
            (pointOneOneRewrite_decreases n L data hn h
              child.1 child.2))))

/-- Complete finite trace below one provenance row. -/
def pointOneOneRowTrace (row : ProvenancedRow n L data hn) :
    RewriteTrace (Occurrence n L) :=
  (pointOneOneRewrite_wellFounded n L data hn).fix
    (pointOneOneRowTraceStep n L data hn) row

theorem pointOneOneRowTrace_eq
    (row : ProvenancedRow n L data hn) :
    pointOneOneRowTrace n L data hn row =
      pointOneOneRowTraceStep n L data hn row
        (fun child _ ↦ pointOneOneRowTrace n L data hn child) := by
  rw [pointOneOneRowTrace,
    (pointOneOneRewrite_wellFounded n L data hn).fix_eq]
  congr 1

/-- Packaging recursion never changes the literal word at a row root. -/
@[simp] theorem pointOneOneRowTrace_rootWord
    (row : ProvenancedRow n L data hn) :
    (pointOneOneRowTrace n L data hn row).rootWord =
      ProvenancedRow.value n L data hn row := by
  rw [pointOneOneRowTrace_eq]
  unfold pointOneOneRowTraceStep
  split <;> rfl

/-- Every recursively generated row trace is locally sound.  The only
algebraic step is `pointOneOneRewrite_preserves` from Point 1.1.2. -/
theorem pointOneOneRowTrace_locallySound
    (row : ProvenancedRow n L data hn) :
    (pointOneOneRowTrace n L data hn row).LocallySound := by
  let C := pointOneOneRewriteSystem n L data hn
  induction row using C.wellFounded.induction with
  | h row ih =>
      rw [pointOneOneRowTrace_eq]
      unfold pointOneOneRowTraceStep
      split
      · trivial
      · rename_i children hexpansion
        constructor
        · rw [RewriteForest.immediateValue_ofList]
          calc
            ((children.attach.map fun child ↦
                (child.1.1, pointOneOneRowTrace n L data hn child.1.2)).map
                fun branch ↦ branch.1 • branch.2.rootWord).sum =
                (children.attach.map fun child ↦
                  child.1.1 • ProvenancedRow.value n L data hn
                    child.1.2).sum := by
                  apply congrArg List.sum
                  rw [List.map_map]
                  apply List.map_congr_left
                  intro child hchild
                  simp only [Function.comp_apply]
                  rw [pointOneOneRowTrace_rootWord]
            _ = (children.map fun child ↦ child.1 •
                  ProvenancedRow.value n L data hn child.2).sum := by
                exact congrArg List.sum
                  (List.attach_map_val (l := children)
                    (f := fun child ↦ child.1 •
                      ProvenancedRow.value n L data hn child.2))
            _ = ProvenancedRow.value n L data hn row :=
              pointOneOneRewrite_preserves n L data hn hexpansion
        · rw [RewriteForest.locallySound_ofList_iff]
          intro branch hbranch
          rw [List.mem_map] at hbranch
          obtain ⟨child, hchild, hbranch⟩ := hbranch
          cases hbranch
          exact ih child.1.2
            (pointOneOneRewrite_decreases n L data hn hexpansion
              child.1 child.2)

/-- The signed traces rooted at the finite seed list from Point 1.1.1. -/
def GoverningWitness.pointOneOneSeedTraceForest {a : L}
    (w : GoverningWitness n L data a) : RewriteForest (Occurrence n L) :=
  RewriteForest.ofList
    ((GoverningWitness.pointOneOneSeedList n L data hn w).map fun seed ↦
      (seed.1, pointOneOneRowTrace n L data hn seed.2))

theorem GoverningWitness.pointOneOneSeedTraceForest_value {a : L}
    (w : GoverningWitness n L data a) :
    (GoverningWitness.pointOneOneSeedTraceForest n L data hn w).immediateValue =
      (w.externalMarkedWord n L data hn).word := by
  rw [GoverningWitness.pointOneOneSeedTraceForest,
    RewriteForest.immediateValue_ofList]
  calc
    (((GoverningWitness.pointOneOneSeedList n L data hn w).map fun seed ↦
        (seed.1, pointOneOneRowTrace n L data hn seed.2)).map
        fun branch ↦ branch.1 • branch.2.rootWord).sum =
        ((GoverningWitness.pointOneOneSeedList n L data hn w).map
          fun seed ↦ seed.1 •
            ProvenancedRow.value n L data hn seed.2).sum := by
      apply congrArg List.sum
      rw [List.map_map]
      apply List.map_congr_left
      intro seed hseed
      simp only [Function.comp_apply]
      rw [pointOneOneRowTrace_rootWord]
    _ = (w.externalMarkedWord n L data hn).word :=
      GoverningWitness.pointOneOneSeedList_value n L data hn w

theorem GoverningWitness.pointOneOneSeedTraceForest_locallySound {a : L}
    (w : GoverningWitness n L data a) :
    (GoverningWitness.pointOneOneSeedTraceForest n L data hn w).LocallySound := by
  rw [GoverningWitness.pointOneOneSeedTraceForest,
    RewriteForest.locallySound_ofList_iff]
  intro branch hbranch
  rw [List.mem_map] at hbranch
  obtain ⟨seed, hseed, hbranch⟩ := hbranch
  cases hbranch
  exact pointOneOneRowTrace_locallySound n L data hn seed.2

/-- Complete finite trace for the provenance collector used in this file.
This is only the first stage of the larger closed-square trace required by
Point 1.1. -/
noncomputable def pointOneOneCompleteTrace {a : L}
    (w : GoverningWitness n L data a) :
    PointOneOneTrace (w.externalMarkedWord n L data hn).word where
  trace := .node .root (w.externalMarkedWord n L data hn).word
    (GoverningWitness.pointOneOneSeedTraceForest n L data hn w)
  root_eq := rfl
  locallySound :=
    ⟨GoverningWitness.pointOneOneSeedTraceForest_value n L data hn w,
      GoverningWitness.pointOneOneSeedTraceForest_locallySound
        n L data hn w⟩

/-! ## Point 1.2: root-inclusive tagged cancellation -/

/-- An occurrence tag is its path from the governing root.  Including the
word makes the forgetful evaluation map completely explicit. -/
structure TaggedOccurrence (M : Type v) where
  path : List ℕ
  word : M

noncomputable instance {M : Type v} : DecidableEq (TaggedOccurrence M) :=
  Classical.decEq _

namespace RewriteTrace

/-- The root occurrence of a subtree at a specified path. -/
def taggedRoot {M : Type v} (path : List ℕ) (t : RewriteTrace M) :
    TaggedOccurrence M :=
  ⟨path, t.rootWord⟩

/-- The signed root ledger of a subtree. -/
def rootLedger {M : Type v} (path : List ℕ) (scale : ℤ)
    (t : RewriteTrace M) : TaggedOccurrence M →₀ ℤ :=
  Finsupp.single (t.taggedRoot path) scale

end RewriteTrace

namespace RewriteForest

/-- The signed roots of a child forest.  `next` is the next unused sibling
index, so different children receive definitionally different paths. -/
def childRootLedger {M : Type v} (path : List ℕ) (next : ℕ) (scale : ℤ) :
    RewriteForest M → TaggedOccurrence M →₀ ℤ
  | .nil => 0
  | .cons coefficient trace tail =>
      trace.rootLedger (next :: path) (scale * coefficient) +
        childRootLedger path (next + 1) scale tail

end RewriteForest

/-- The oriented local cell boundary is `outputs - input`.  With this
orientation, adding all cell boundaries to the root produces the final
frontier. -/
def RewriteTrace.localBoundaryLedger {M : Type v}
    (path : List ℕ) (scale : ℤ) :
    RewriteTrace M → TaggedOccurrence M →₀ ℤ
  | .leaf _ => 0
  | .node _ word children =>
      children.childRootLedger path 0 scale -
        Finsupp.single ⟨path, word⟩ scale

/-- At one non-leaf cell, its input cancels literally against the negative
input in `outputs - input`.  This is the atomic incidence cancellation used
by the global theorem. -/
theorem RewriteTrace.root_add_localBoundaryLedger_eq_childRootLedger
    {M : Type v} (path : List ℕ) (scale : ℤ)
    (kind : RewriteKind) (word : M) (children : RewriteForest M) :
    RewriteTrace.rootLedger path scale (.node kind word children) +
        RewriteTrace.localBoundaryLedger path scale
          (.node kind word children) =
      children.childRootLedger path 0 scale := by
  simp only [RewriteTrace.rootLedger, RewriteTrace.taggedRoot,
    RewriteTrace.rootWord, RewriteTrace.localBoundaryLedger]
  abel

/- The complete signed cell-boundary ledger and the external leaf frontier,
defined simultaneously over traces and forests. -/
mutual
  def RewriteTrace.allBoundaryLedger {M : Type v}
      (path : List ℕ) (scale : ℤ) :
      RewriteTrace M → TaggedOccurrence M →₀ ℤ
    | .leaf _ => 0
    | .node kind word children =>
        RewriteTrace.localBoundaryLedger path scale (.node kind word children) +
          children.allBoundaryLedger path 0 scale

  def RewriteForest.allBoundaryLedger {M : Type v}
      (path : List ℕ) (next : ℕ) (scale : ℤ) :
      RewriteForest M → TaggedOccurrence M →₀ ℤ
    | .nil => 0
    | .cons coefficient trace tail =>
        trace.allBoundaryLedger (next :: path) (scale * coefficient) +
          tail.allBoundaryLedger path (next + 1) scale

  def RewriteTrace.externalFrontierLedger {M : Type v}
      (path : List ℕ) (scale : ℤ) :
      RewriteTrace M → TaggedOccurrence M →₀ ℤ
    | .leaf word => Finsupp.single ⟨path, word⟩ scale
    | .node _ _ children => children.externalFrontierLedger path 0 scale

  def RewriteForest.externalFrontierLedger {M : Type v}
      (path : List ℕ) (next : ℕ) (scale : ℤ) :
      RewriteForest M → TaggedOccurrence M →₀ ℤ
    | .nil => 0
    | .cons coefficient trace tail =>
        trace.externalFrontierLedger (next :: path) (scale * coefficient) +
          tail.externalFrontierLedger path (next + 1) scale
end

/- Root-inclusive finite Stokes for a trace, proved mutually with the forest
identity.  Neither theorem assumes any cancellation statement. -/
mutual
  theorem RewriteTrace.root_add_allBoundaryLedger_eq_externalFrontierLedger
      {M : Type v} (path : List ℕ) (scale : ℤ) (t : RewriteTrace M) :
      t.rootLedger path scale + t.allBoundaryLedger path scale =
        t.externalFrontierLedger path scale := by
    cases t with
    | leaf word =>
        simp [RewriteTrace.rootLedger, RewriteTrace.taggedRoot,
          RewriteTrace.rootWord,
          RewriteTrace.allBoundaryLedger,
          RewriteTrace.externalFrontierLedger]
    | node kind word children =>
        have hchildren :=
          children.childRoot_add_allBoundaryLedger_eq_externalFrontierLedger
            path 0 scale
        rw [RewriteTrace.allBoundaryLedger,
          RewriteTrace.localBoundaryLedger,
          RewriteTrace.externalFrontierLedger,
          ← hchildren]
        simp only [RewriteTrace.rootLedger, RewriteTrace.taggedRoot,
          RewriteTrace.rootWord]
        abel

  theorem RewriteForest.childRoot_add_allBoundaryLedger_eq_externalFrontierLedger
      {M : Type v} (path : List ℕ) (next : ℕ) (scale : ℤ)
      (forest : RewriteForest M) :
      forest.childRootLedger path next scale +
          forest.allBoundaryLedger path next scale =
        forest.externalFrontierLedger path next scale := by
    cases forest with
    | nil => simp [RewriteForest.childRootLedger,
        RewriteForest.allBoundaryLedger,
        RewriteForest.externalFrontierLedger]
    | cons coefficient trace tail =>
        have htrace :=
          trace.root_add_allBoundaryLedger_eq_externalFrontierLedger
            (next :: path) (scale * coefficient)
        have htail :=
          tail.childRoot_add_allBoundaryLedger_eq_externalFrontierLedger
            path (next + 1) scale
        rw [RewriteForest.childRootLedger,
          RewriteForest.allBoundaryLedger,
          RewriteForest.externalFrontierLedger,
          ← htrace, ← htail]
        abel
end

/-- Point 1.2's raw external frontier for the complete Point-1.1 trace. -/
def pointOneTwoTaggedExternalFrontier {a : L}
    (w : GoverningWitness n L data a) : TaggedOccurrence (Occurrence n L) →₀ ℤ :=
  let T := pointOneOneCompleteTrace n L data hn w
  T.trace.externalFrontierLedger [] 1

/-- Point 1.2's complete signed tagged cell-boundary ledger. -/
def pointOneTwoTaggedCellBoundaries {a : L}
    (w : GoverningWitness n L data a) : TaggedOccurrence (Occurrence n L) →₀ ℤ :=
  let T := pointOneOneCompleteTrace n L data hn w
  T.trace.allBoundaryLedger [] 1

/-- The governing root is explicitly present with coefficient `+1`. -/
def pointOneTwoTaggedRoot {a : L}
    (w : GoverningWitness n L data a) : TaggedOccurrence (Occurrence n L) →₀ ℤ :=
  Finsupp.single ⟨[], (w.externalMarkedWord n L data hn).word⟩ 1

/-- Exact root-inclusive cancellation for the provenance-stage tagged trace. -/
theorem pointOneTwo_root_add_cellBoundaries_eq_externalFrontier {a : L}
    (w : GoverningWitness n L data a) :
    pointOneTwoTaggedRoot n L data hn w +
        pointOneTwoTaggedCellBoundaries n L data hn w =
      pointOneTwoTaggedExternalFrontier n L data hn w := by
  let T := pointOneOneCompleteTrace n L data hn w
  have h := T.trace.root_add_allBoundaryLedger_eq_externalFrontierLedger [] 1
  change Finsupp.single
      ⟨[], (w.externalMarkedWord n L data hn).word⟩ 1 +
        T.trace.allBoundaryLedger [] 1 =
      T.trace.externalFrontierLedger [] 1
  have hroot : Finsupp.single
        ⟨[], (w.externalMarkedWord n L data hn).word⟩ 1 =
      T.trace.rootLedger [] 1 := by
    simp [RewriteTrace.rootLedger, RewriteTrace.taggedRoot, T.root_eq]
  rw [hroot]
  exact h

/-- Coefficientwise form of Point 1.2.  Thus the global equality is not only
an equality after UEA evaluation: it records the signed cancellation at each
individual tagged occurrence. -/
theorem pointOneTwo_coefficient_identity {a : L}
    (w : GoverningWitness n L data a)
    (occurrence : TaggedOccurrence (Occurrence n L)) :
    pointOneTwoTaggedRoot n L data hn w occurrence +
        pointOneTwoTaggedCellBoundaries n L data hn w occurrence =
      pointOneTwoTaggedExternalFrontier n L data hn w occurrence := by
  have h := congrArg (fun ledger => ledger occurrence)
    (pointOneTwo_root_add_cellBoundaries_eq_externalFrontier
      n L data hn w)
  simpa using h

/-- The coefficient of the distinguished governing occurrence in the root
ledger is literally positive one. -/
@[simp] theorem pointOneTwo_root_coefficient {a : L}
    (w : GoverningWitness n L data a) :
    pointOneTwoTaggedRoot n L data hn w
        ⟨[], (w.externalMarkedWord n L data hn).word⟩ = 1 := by
  simp [pointOneTwoTaggedRoot]

/-! ### Literal evaluation: local soundness, not a second assumption -/

/-- Forget occurrence tags and evaluate the resulting signed ledger. -/
def taggedOccurrenceValue {M : Type v} [AddCommGroup M] :
    (TaggedOccurrence M →₀ ℤ) →ₗ[ℤ] M :=
  Finsupp.linearCombination ℤ TaggedOccurrence.word

theorem RewriteTrace.taggedOccurrenceValue_rootLedger
    {M : Type v} [AddCommGroup M]
    (path : List ℕ) (scale : ℤ) (t : RewriteTrace M) :
    taggedOccurrenceValue (t.rootLedger path scale) =
      scale • t.rootWord := by
  simp [taggedOccurrenceValue, RewriteTrace.rootLedger,
    RewriteTrace.taggedRoot]

theorem RewriteForest.taggedOccurrenceValue_childRootLedger
    {M : Type v} [AddCommGroup M]
    (path : List ℕ) (next : ℕ) (scale : ℤ)
    (forest : RewriteForest M) :
    taggedOccurrenceValue (forest.childRootLedger path next scale) =
      scale • forest.immediateValue := by
  cases forest with
  | nil =>
      rw [RewriteForest.childRootLedger, RewriteForest.immediateValue]
      exact (smul_zero scale : scale • (0 : M) = 0).symm
  | cons coefficient trace tail =>
      rw [RewriteForest.childRootLedger, map_add,
        trace.taggedOccurrenceValue_rootLedger,
        tail.taggedOccurrenceValue_childRootLedger]
      rw [RewriteForest.immediateValue]
      module

theorem RewriteTrace.taggedOccurrenceValue_localBoundaryLedger_eq_zero
    {M : Type v} [AddCommGroup M]
    (path : List ℕ) (scale : ℤ) (t : RewriteTrace M)
    (ht : t.LocallySound) :
    taggedOccurrenceValue (t.localBoundaryLedger path scale) = 0 := by
  cases t with
  | leaf word => simp [RewriteTrace.localBoundaryLedger]
  | node kind word children =>
      rcases ht with ⟨hlocal, hchildren⟩
      rw [RewriteTrace.localBoundaryLedger, map_sub,
        children.taggedOccurrenceValue_childRootLedger]
      simp only [taggedOccurrenceValue,
        Finsupp.linearCombination_single]
      rw [hlocal]
      module

/- Evaluation-zero for all cell boundaries, proved mutually for a trace and
its child forest from recursive local soundness alone. -/
mutual
  theorem RewriteTrace.taggedOccurrenceValue_allBoundaryLedger_eq_zero
      {M : Type v} [AddCommGroup M]
      (path : List ℕ) (scale : ℤ) (t : RewriteTrace M)
      (ht : t.LocallySound) :
      taggedOccurrenceValue (t.allBoundaryLedger path scale) = 0 := by
    cases t with
    | leaf word => simp [RewriteTrace.allBoundaryLedger]
    | node kind word children =>
        rcases ht with ⟨hlocal, hchildren⟩
        rw [RewriteTrace.allBoundaryLedger, map_add,
          RewriteTrace.taggedOccurrenceValue_localBoundaryLedger_eq_zero
            (path := path) (scale := scale)
            (t := .node kind word children) (ht := ⟨hlocal, hchildren⟩),
          children.taggedOccurrenceValue_allBoundaryLedger_eq_zero
            path 0 scale hchildren,
          add_zero]

  theorem RewriteForest.taggedOccurrenceValue_allBoundaryLedger_eq_zero
      {M : Type v} [AddCommGroup M]
      (path : List ℕ) (next : ℕ) (scale : ℤ)
      (forest : RewriteForest M) (hf : forest.LocallySound) :
      taggedOccurrenceValue (forest.allBoundaryLedger path next scale) = 0 := by
    cases forest with
    | nil => simp [RewriteForest.allBoundaryLedger]
    | cons coefficient trace tail =>
        rcases hf with ⟨htrace, htail⟩
        rw [RewriteForest.allBoundaryLedger, map_add,
          trace.taggedOccurrenceValue_allBoundaryLedger_eq_zero
            (next :: path) (scale * coefficient) htrace,
          tail.taggedOccurrenceValue_allBoundaryLedger_eq_zero
            path (next + 1) scale htail,
          add_zero]
end

/-- Every accumulated cell boundary evaluates to zero, derived solely from
the local preservation proofs contained in Point 1.1. -/
theorem pointOneTwo_cellBoundaries_evaluate_eq_zero {a : L}
    (w : GoverningWitness n L data a) :
    taggedOccurrenceValue
        (pointOneTwoTaggedCellBoundaries n L data hn w) = 0 := by
  let T := pointOneOneCompleteTrace n L data hn w
  exact T.trace.taggedOccurrenceValue_allBoundaryLedger_eq_zero [] 1
    T.locallySound

/-- Evaluating the external frontier recovers the governing external word.
This is a consequence of Point 1.2, not an assumption on Point 1.1. -/
theorem pointOneTwo_externalFrontier_evaluate {a : L}
    (w : GoverningWitness n L data a) :
    taggedOccurrenceValue
        (pointOneTwoTaggedExternalFrontier n L data hn w) =
      (w.externalMarkedWord n L data hn).word := by
  have h := congrArg taggedOccurrenceValue
    (pointOneTwo_root_add_cellBoundaries_eq_externalFrontier
      n L data hn w)
  rw [map_add, pointOneTwo_cellBoundaries_evaluate_eq_zero, add_zero] at h
  simpa [pointOneTwoTaggedRoot, taggedOccurrenceValue] using h.symm

end

end LieRings.MetabelianVanishing.ExperimentalPoint12
