import LieRings.Metabelian.FreeNilpotent
import Mathlib.LinearAlgebra.StdBasis
#check FreeMetabelian.Action.apply_zero
#check FreeMetabelian.Action.linear
#check LinearMap.map_zero
#check Module.Basis.pi
#check Module.Basis.piBasis
#check Module.Basis.ofEquivFun
#check Module.Basis.prod
#check Module.Basis.sigma
#check Module.Basis.reindex
#check LinearMap.single
#check LieSubmodule.span
#check LieSubmodule.lieSpan
#check Pi.basis
#check LieSubmodule.lie_eq_bot_iff
#check LieSubmodule.lieIdeal_oper_eq_linear_span'
#check LieSubmodule.lie_mem_lie
#check LieSubmodule.lie_le_left
#check LieSubmodule.lie_le_right
#check lowerCentralSeries_succ
#check lowerCentralSeries_zero
#check LieAlgebra.lowerCentralSeries_succ
#check LieAlgebra.lowerCentralSeries_zero
#check LieSubmodule.mk
#check Submodule.pi
#check Submodule.piSet
#check Submodule.inf
#check LieSubmodule.lieIdeal_oper_eq_linear_span
#check LieSubmodule.lie_le_iff
#check LieSubmodule.mk_eq_mk
#check LieIdeal
#check Pi.single
#check Pi.single_apply
#check Pi.single_eq_same
#check zsmul_apply
#check Pi.zsmul_apply
#check LinearEquiv.ofEq
#check Module.Basis.cast
