import LieRings.Homological.QuadraticUCT

open TensorProduct
open LieRings
open Koszul

#check Module.Basis.ext
#check Module.Basis.ext_elem
#check Module.Basis.sum_repr
#check Module.Basis.repr_self
#check exteriorPower.basis_apply
#check Set.powersetCard.ofFinEmbEquiv
#check Set.powersetCard.ofFinEmbEquiv_symm_apply
#check Finset.orderEmbOfFin_strictMono
#check SymmetricPower.QuadraticExactSequence.exteriorTwoToTensor_range_eq_ker
#check AddCircle.coe_int
#check AddCircle.coe_eq_zero_iff
#check Submodule.Quotient.mk_eq_zero
#check Module.Basis.tensorProduct
#check Module.Basis.tensorProduct_apply
#check Module.Basis.tensorProduct_apply'
#check LinearMap.ker_le_ker_comp
#check TensorProduct.congr
#check TensorProduct.rid
#check TensorProduct.map_injective_of_flat_flat
#check Module.Flat.rTensor_preserves_injective_linearMap
#check Module.Flat.lTensor_preserves_injective_linearMap
#check LinearMap.rTensor
#check LinearMap.lTensor
#check Module.Baer.extension_property
#check Module.Baer.of_divisible
#check LinearEquiv.ofInjective
#check LinearEquiv.ofInjective_apply
#check Module.Basis.exteriorPower
#check LinearMap.ker_eq_bot
#check Module.Baer.extension_property
#check Module.Flat.of_free
#check Module.Flat.rTensor_preserves_injective_linearMap
#check TensorProduct.map_injective_of_flat_flat
#check LinearMap.coe_comp
#check LinearEquiv.trans_apply
#check LinearEquiv.refl
#check SymmetricPower.degreeZeroLinearEquiv
#check SymmetricPower.degreeOneLinearEquiv
#check Int.cast_zsmul
#check ZMod.intCast_zmod_eq_zero_iff_dvd
#check LinearMap.flip
#check exteriorPower.alternatingMapLinearEquiv
#check AlternatingMap.mkPiAlgebraFin2
#check AlternatingMap.ofSubsingleton
#check AlternatingMap.curryLeft
#check LinearMap.toAlternatingMap
#check LinearMap.mk₂
#check LinearMap.liftOfRightInverse
#check Int.ediv_mul_cancel
#check Int.mul_ediv_cancel
#check Int.cast_ediv
