import LieRings
import Mathlib.Util.AssertNoSorry

/-!
# Public-result audit

Every result advertised in `README.md` is checked here against accidental
dependencies on `sorry`.
-/

assert_no_sorry LieRings.PBW.abelianEquivSymmetric
assert_no_sorry LieRings.PBW.orderedPBWMap_surjective
assert_no_sorry LieRings.PBW.TriangularRepresentation.freeModulePBW
assert_no_sorry LieRings.PBW.canonicalMap_injective_int

assert_no_sorry LieRings.UEA.quotientEquivLieIdeal
assert_no_sorry LieRings.dimensionSubring_two_eq_lowerCentralSeries_one
assert_no_sorry LieRings.dimensionSubring_three_eq_lowerCentralSeries_two
assert_no_sorry LieRings.FreeLieDimension.dimensionSubring_succ_eq_lowerCentralSeries
assert_no_sorry LieRings.dimensionSubring_bracket_eq_lowerCentralSeries_of_pos
assert_no_sorry LieRings.bracket_dimensionSubring_le_lowerCentralSeries_of_pos
assert_no_sorry LieRings.UEA.actionSubmodule_augmentationIdeal_pow_eq_lcs
assert_no_sorry LieRings.DegreeFour.twoDeltaFourProperty

assert_no_sorry LieRings.MetabelianTwoFactor.nilpotent_dimensionSubring_eq_bot
assert_no_sorry LieRings.MetabelianTwoFactor.odd_dimensionSubring_le_lowerCentralSeries
assert_no_sorry LieRings.MetabelianTwoFactor.dimensionSubring_five_le_lowerCentralSeries_three

assert_no_sorry LieRings.LieFiltration.AssociatedGraded
assert_no_sorry LieRings.lowerCentralFiltration
assert_no_sorry LieRings.dimensionFiltration
assert_no_sorry LieRings.lowerCentralToDimensionGraded
assert_no_sorry LieRings.dimensionGradedImage
assert_no_sorry LieRings.dimensionGradedImage_isGraded
assert_no_sorry LieRings.DimensionGradedCokernel
assert_no_sorry LieRings.dimensionGradedCokernel_isLieAbelian
