import LieRings.DimensionSubring.DegreeFour
import LieRings.DimensionSubring.FreeLie
import LieRings.DimensionSubring.Graded
import LieRings.DimensionSubring.MetabelianTwoFactor
import LieRings.Homological.DimensionSubring
import LieRings.PBW.Abelian
import LieRings.PBW.HigginsEmbedding
import LieRings.PBW.Surjectivity
import LieRings.PBW.TriangularRepresentation
import LieRings.UniversalEnveloping.Adjoint
import LieRings.UniversalEnveloping.Quotient

/-!
# Main results

This file gives a compiled, explicit formulation of every mathematical result advertised in
the `Main proven results` section of `README.md`. Each assertion is presented as a short
`example ... := ...` proof using the corresponding public theorem.
-/

namespace LieRings.MainResults

noncomputable section

universe u v w

/-! ## PBW and the canonical embedding -/

/-- For an Abelian Lie algebra, its universal enveloping algebra is canonically equivalent to
its symmetric algebra. -/
example (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]
    [IsLieAbelian L] :
    UEA R L ≃ₐ[R] SymmetricAlgebra R L :=
  PBW.abelianEquivSymmetric R L

/-- If the underlying module has an ordered basis, ordered PBW monomials span the universal
enveloping algebra. -/
example (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]
    (ι : Type w) [LinearOrder ι] (b : Module.Basis ι R L) :
    Function.Surjective (PBW.orderedPBWMap R L ι b) :=
  PBW.orderedPBWMap_surjective R L ι b

/-- A triangular representation proves the full ordered-basis PBW statement. -/
example (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]
    (ι : Type w) [LinearOrder ι] (b : Module.Basis ι R L)
    (P : PBW.TriangularRepresentation R L ι b) :
    PBW.FreeModulePBW R L ι b :=
  P.freeModulePBW

/-- Every Lie ring embeds canonically into its universal enveloping algebra over `ℤ`, without
a basis or any auxiliary parameter. -/
example (L : Type v) [LieRing L] :
    Function.Injective
      (UniversalEnvelopingAlgebra.ι ℤ : L → UEA ℤ L) :=
  PBW.canonicalMap_injective_int L

/-! ## Dimension subrings and lower central series -/

/-- The universal enveloping algebra of a Lie quotient is the quotient of the enveloping
algebra by the two-sided ideal generated by the Lie ideal. -/
example (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]
    (I : LieIdeal R L) :
    letI : LieAlgebra R (L ⧸ I) :=
      LieSubmodule.Quotient.lieQuotientLieAlgebra I
    UEA R (L ⧸ I) ≃ₐ[R] UEA R L ⧸ UEA.idealOfLieIdeal R L I :=
  UEA.quotientEquivLieIdeal R L I

/-- For every Lie algebra over a commutative ring, `δ₂(L) = γ₂(L)`. -/
example (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L] :
    dimensionSubring R L 2 = lowerCentralSeries R L 1 :=
  dimensionSubring_two_eq_lowerCentralSeries_one R L

/-- For every Lie ring, `δ₃(L) = γ₃(L)`. -/
example (L : Type v) [LieRing L] :
    dimensionSubring ℤ L 3 = lowerCentralSeries ℤ L 2 :=
  dimensionSubring_three_eq_lowerCentralSeries_two L

/-- In every positive degree, dimension subrings and the lower central series agree for a free
Lie ring. -/
example (X : Type v) (n : ℕ) :
    dimensionSubring ℤ (FreeLieAlgebra ℤ X) (n + 1) =
      lowerCentralSeries ℤ (FreeLieAlgebra ℤ X) n :=
  FreeLieDimension.dimensionSubring_succ_eq_lowerCentralSeries X n

/-- In conventional positive indexing, bracketing `δₙ(L)` with `L` gives `γₙ₊₁(L)`. -/
example (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]
    (n : ℕ) (hn : 1 ≤ n) :
    ⁅dimensionSubring R L n, (⊤ : LieIdeal R L)⁆ =
      lowerCentralSeries R L n :=
  dimensionSubring_bracket_eq_lowerCentralSeries_of_pos R L hn

/-- The dimension filtration is strongly central:
`[δₘ(L), δₙ(L)] ⊆ γₘ₊ₙ(L)` in conventional positive indexing. -/
example (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]
    (m n : ℕ) (hm : 1 ≤ m) (hn : 1 ≤ n) :
    ⁅dimensionSubring R L m, dimensionSubring R L n⁆ ≤
      lowerCentralSeries R L (m + n - 1) :=
  bracket_dimensionSubring_le_lowerCentralSeries_of_pos R L hm hn

/-- Acting by the `n`th power of the augmentation ideal gives the `n`th relative lower-central
term of a Lie submodule. -/
example (R : Type u) (L : Type v) (M : Type w)
    [CommRing R] [LieRing L] [LieAlgebra R L]
    [AddCommGroup M] [Module R M] [LieRingModule L M] [LieModule R L M]
    (A : LieSubmodule R L M) (n : ℕ) :
    UEA.actionSubmodule R L M (UEA.augmentationIdeal R L ^ n) A =
      (A.lcs n : Submodule R M) :=
  UEA.actionSubmodule_augmentationIdeal_pow_eq_lcs R L M A n

/-- Bartholdi--Passi's factor-two theorem: `2δ₄(L) ⊆ γ₄(L)` for every Lie ring. -/
example (L : Type v) [LieRing L] (x : L)
    (hx : x ∈ dimensionSubring ℤ L 4) :
    2 • x ∈ lowerCentralSeries ℤ L 3 :=
  DegreeFour.twoDeltaFourProperty L x hx

/-! ## $H_2$-description -/

open Homological Homological.FreePresentation

/-- For every Lie ring and `n ≥ 2`, the dimension factor `δₙ(L)/γₙ(L)` is the
cokernel of `H₂(L/γₙ(L); ℤ) → H₂(L/δₙ(L); ℤ)`. -/
example (L : Type v) [LieRing L] {n : ℕ} (hn : 2 ≤ n) :
    LinearCokernel (secondHomologyMap
      (dimensionExtensionMap L n (by omega))) ≃ₗ[ℤ]
      DimensionFactor L n :=
  dimensionFactorEquivSecondHomologyCokernel L hn

/-- For every Lie ring and `n ≥ 2`, the quotient `δₙ(L)/γₙ₊₁(L)` is the
cokernel of `H₂(L; ℤ) → H₂(L/δₙ(L); ℤ)`. -/
example (L : Type v) [LieRing L] {n : ℕ} (hn : 2 ≤ n) :
    LinearCokernel (secondHomologyMap
      (quotientMk (dimensionSubring ℤ L n))) ≃ₗ[ℤ]
      IdealQuotient (dimensionSubring ℤ L n)
        (conventionalLowerCentralSeries L (n + 1)) :=
  dimensionSubringModNextLowerCentralEquivSecondHomologyCokernel L hn

/-- For every Lie ring and `n ≥ 2`, the lower-central factor `γₙ(L)/γₙ₊₁(L)` is the
cokernel of `H₂(L; ℤ) → H₂(L/γₙ(L); ℤ)`. -/
example (L : Type v) [LieRing L] {n : ℕ} (hn : 2 ≤ n) :
    LinearCokernel (secondHomologyMap
      (quotientMk (conventionalLowerCentralSeries L n))) ≃ₗ[ℤ]
      IdealQuotient (conventionalLowerCentralSeries L n)
        (conventionalLowerCentralSeries L (n + 1)) :=
  lowerCentralFactorEquivSecondHomologyCokernel L hn

/-! ## Odd-dimensional theorem for metabelian Lie rings -/

/-- If a metabelian Lie ring has nilpotency class at most `c ≥ 2`, then its
`(2c-1)`st dimension subring is zero. -/
example (c : ℕ) (K : Type v) [LieRing K]
    (hc : 2 ≤ c) (hmeta : IsMetabelian K)
    (hclass : lowerCentralSeries ℤ K c = ⊥) :
    dimensionSubring ℤ K (2 * c - 1) = ⊥ :=
  MetabelianTwoFactor.nilpotent_dimensionSubring_eq_bot c K hc hmeta hclass

/-- Consequently, every metabelian Lie ring satisfies
`δ₂ₙ₊₁(L) ⊆ γₙ₊₂(L)` for `n ≥ 1`. -/
example (n : ℕ) (L : Type v) [LieRing L]
    (hn : 1 ≤ n) (hmeta : IsMetabelian L) :
    dimensionSubring ℤ L (2 * n + 1) ≤
      lowerCentralSeries ℤ L (n + 1) :=
  MetabelianTwoFactor.odd_dimensionSubring_le_lowerCentralSeries n L hn hmeta

/-- Consequently, the intersections of all dimension and lower-central terms agree for every
metabelian Lie ring: `δ_ω(L) = γ_ω(L)`. -/
example (L : Type v) [LieRing L] (hmeta : IsMetabelian L) :
    dimensionSubringOmega ℤ L = lowerCentralSeriesOmega ℤ L :=
  MetabelianTwoFactor.dimensionSubringOmega_eq_lowerCentralSeriesOmega L hmeta

/-- For every Lie ring, with no metabelian, finiteness, or torsion assumption,
`δ₅(L) ⊆ γ₄(L)`. This is a corollary of the nilpotent theorem at `c = 3`, not a base case
used in its proof. -/
example (L : Type v) [LieRing L] :
    dimensionSubring ℤ L 5 ≤ lowerCentralSeries ℤ L 3 :=
  MetabelianTwoFactor.dimensionSubring_five_le_lowerCentralSeries_three L

/-! ## Associated graded Lie algebras -/

section AssociatedGraded

variable (R : Type u) (L : Type v)
variable [CommRing R] [LieRing L] [LieAlgebra R L]

/-- A Lie filtration is descending. -/
example (F : LieFiltration R L) : Antitone F :=
  F.antitone

/-- A Lie filtration has the defining strongly central bracket inclusion. -/
example (F : LieFiltration R L) (i j : ℕ+) :
    ⁅F i, F j⁆ ≤ F (i + j) :=
  F.lie_le' i j

/-- The associated graded object is the external direct sum of the successive quotients. -/
example (F : LieFiltration R L) :
    F.AssociatedGraded = DirectSum ℕ+ (fun n ↦ F.GradedPiece n) :=
  rfl

/-- The associated graded object carries its induced Lie-ring structure. -/
example (F : LieFiltration R L) : LieRing F.AssociatedGraded :=
  inferInstance

/-- The associated graded object is a Lie algebra over the original base ring. -/
example (F : LieFiltration R L) : LieAlgebra R F.AssociatedGraded :=
  inferInstance

/-- The lower central series defines a positive Lie filtration. -/
example : LieFiltration R L :=
  lowerCentralFiltration R L

/-- The dimension subrings define a positive Lie filtration. -/
example : LieFiltration R L :=
  dimensionFiltration R L

/-- The standard inclusions `γₙ(L) ⊆ δₙ(L)` compare these two filtrations. -/
example (n : ℕ+) :
    lowerCentralFiltration R L n ≤ dimensionFiltration R L n :=
  lowerCentralFiltration_le_dimensionFiltration R L n

/-- The filtration inclusions induce the canonical graded Lie homomorphism
`gr_γ(L) → gr_δ(L)`. -/
example : LowerCentralGraded R L →ₗ⁅R⁆ DimensionGraded R L :=
  lowerCentralToDimensionGraded R L

/-- The image of the canonical graded map is a Lie ideal. -/
example : LieIdeal R (DimensionGraded R L) :=
  dimensionGradedImage R L

/-- Its underlying submodule is exactly the range of the canonical graded map. -/
example :
    (dimensionGradedImage R L).toSubmodule =
      (lowerCentralToDimensionGraded R L).range.toSubmodule :=
  rfl

/-- The image of the canonical graded map is homogeneous. -/
example :
    (dimensionFiltration R L).IsGradedIdeal (dimensionGradedImage R L) :=
  dimensionGradedImage_isGraded R L

/-- The graded dimension cokernel is definitionally the quotient by the canonical image. -/
example :
    DimensionGradedCokernel R L =
      (DimensionGraded R L ⧸ dimensionGradedImage R L) :=
  rfl

/-- The graded dimension cokernel is an Abelian Lie algebra. -/
example : IsLieAbelian (DimensionGradedCokernel R L) :=
  dimensionGradedCokernel_isLieAbelian R L

end AssociatedGraded

end

end LieRings.MainResults
