import LieRings.PBW.HigginsUniversal
import Mathlib.Algebra.DirectSum.Module
import Mathlib.Algebra.DirectSum.Finsupp
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis

/-!
# Higgins's obstruction for direct sums of cyclic groups

This file formalizes part (iii) of Higgins's Theorem 7.  The hypothesis is expressed intrinsically:
the underlying integral module is the internal direct sum of submodules whose additive groups are
cyclic.  Finite cyclic summands are allowed; no freeness or torsion-freeness is assumed.
-/

namespace LieRings.PBW.Higgins

universe u v w

noncomputable section

variable (M : Type u) [AddCommGroup M]

/-- An integral module is a direct sum of cyclic modules if it has an internal direct-sum
decomposition into submodules generated by one element.  This includes both infinite cyclic
summands and finite cyclic summands. -/
def IsDirectSumOfCyclic : Prop :=
  ∃ (ι : Type u) (_ : DecidableEq ι) (C : ι → Submodule ℤ M),
    DirectSum.IsInternal C ∧ ∀ i, IsAddCyclic (C i)

namespace CyclicPresentation

variable {M}
variable {ι : Type u} [DecidableEq ι]
variable (C : ι → Submodule ℤ M) (hC : DirectSum.IsInternal C)
variable (cyclic : ∀ i, IsAddCyclic (C i))

/-- A chosen generator of every cyclic summand. -/
def generator (i : ι) : C i := by
  letI : IsAddCyclic (C i) := cyclic i
  exact Classical.choose IsAddCyclic.exists_zsmul_surjective

theorem generator_surjective (i : ι) :
    Function.Surjective (fun n : ℤ ↦ n • generator C cyclic i) := by
  letI : IsAddCyclic (C i) := cyclic i
  exact Classical.choose_spec IsAddCyclic.exists_zsmul_surjective

/-- The free module on the set of cyclic summands. -/
abbrev Free := ι →₀ ℤ

/-- The diagonal presentation map from the free module on the chosen cyclic generators. -/
def map : Free (ι := ι) →ₗ[ℤ] M :=
  Finsupp.linearCombination ℤ fun i ↦ (generator C cyclic i : M)

@[simp]
theorem map_single (i : ι) (n : ℤ) :
    map C cyclic (Finsupp.single i n) = n • (generator C cyclic i : M) := by
  simp [map]

/-- The diagonal presentation is onto because the cyclic summands form an internal direct sum. -/
theorem map_surjective (hC : DirectSum.IsInternal C) :
    Function.Surjective (map C cyclic) := by
  intro x
  obtain ⟨dx, rfl⟩ := hC.2 x
  induction dx using DirectSum.induction_on with
  | zero => exact ⟨0, by simp [map]⟩
  | of i x =>
      obtain ⟨n, hn⟩ := generator_surjective C cyclic i x
      refine ⟨Finsupp.single i n, ?_⟩
      rw [map_single]
      have hn' : n • (generator C cyclic i : M) = (x : M) :=
        congrArg Subtype.val hn
      rw [hn']
      exact (DirectSum.coeLinearMap_of C i x).symm
  | add x y hx hy =>
      obtain ⟨p, hp⟩ := hx
      obtain ⟨q, hq⟩ := hy
      exact ⟨p + q, by rw [map_add, hp, hq, map_add]⟩

/-- Multiplication of the chosen generator gives a linear map into its cyclic summand. -/
def coefficientMap (i : ι) : ℤ →ₗ[ℤ] C i where
  toFun n := n • generator C cyclic i
  map_add' a b := add_smul a b _
  map_smul' a b := by
    change (a * b) • generator C cyclic i = a • b • generator C cyclic i
    rw [mul_smul]

/-- The coefficientwise map from the free presentation to the external direct sum. -/
def toDirectSum : Free (ι := ι) →ₗ[ℤ] (DirectSum ι fun i ↦ C i) :=
  (DirectSum.lmap (coefficientMap C cyclic)).comp
    (finsuppLEquivDirectSum ℤ ℤ ι).toLinearMap

@[simp]
theorem toDirectSum_apply (p : Free (ι := ι)) (i : ι) :
    toDirectSum C cyclic p i = p i • generator C cyclic i := by
  change (DirectSum.lmap (coefficientMap C cyclic)
    (finsuppLEquivDirectSum ℤ ℤ ι p)) i = _
  let d := finsuppLEquivDirectSum ℤ ℤ ι p
  calc
    ((DFinsupp.mapRange.linearMap (coefficientMap C cyclic)) d) i =
        (DFinsupp.mapRange (fun i x ↦ coefficientMap C cyclic i x)
          (fun i ↦ (coefficientMap C cyclic i).map_zero) d) i :=
      congrArg (fun x : DirectSum ι (fun i ↦ C i) ↦ x i)
        (DFinsupp.mapRange.linearMap_apply (coefficientMap C cyclic) d)
    _ = coefficientMap C cyclic i (d i) := DFinsupp.mapRange_apply _ _ _ _
    _ = p i • generator C cyclic i := by
      rw [show d i = p i by exact finsuppLEquivDirectSum_apply ℤ ℤ ι p i]
      rfl

theorem coeLinearMap_toDirectSum (p : Free (ι := ι)) :
    DirectSum.coeLinearMap C (toDirectSum C cyclic p) = map C cyclic p := by
  induction p using Finsupp.induction with
  | zero => simp
  | single_add i n p _ _ ih =>
      rw [map_add (toDirectSum C cyclic), map_add (map C cyclic),
        map_add (DirectSum.coeLinearMap C), ih]
      congr 1
      change DirectSum.coeLinearMap C
        (DirectSum.lmap (coefficientMap C cyclic)
          (finsuppLEquivDirectSum ℤ ℤ ι (Finsupp.single i n))) = _
      rw [finsuppLEquivDirectSum_single,
        DirectSum.lmap_lof, DirectSum.coeLinearMap_lof, map_single]
      rfl

/-- A relation in the diagonal presentation is diagonal term by term: each one-coordinate part is
itself a relation. -/
theorem ker_component (hC : DirectSum.IsInternal C)
    (q : LinearMap.ker (map C cyclic)) (i : ι) :
    q.1 i • generator C cyclic i = 0 := by
  have hsum : DirectSum.coeLinearMap C (toDirectSum C cyclic q) = 0 := by
    rw [coeLinearMap_toDirectSum]
    exact q.property
  have hzero : toDirectSum C cyclic q = 0 := hC.1 hsum
  have hi := congrArg (fun d : (DirectSum ι fun i ↦ C i) ↦ d i) hzero
  simpa using hi

end CyclicPresentation

section LiftCongruence

variable {M}

/-- The tensor-algebra endomorphism induced by an endomorphism of the canonical free module. -/
def tensorLiftEndomorphism (M : Type u) [AddCommGroup M]
    (h : FreePresentation M →ₗ[ℤ] FreePresentation M) :
    PresentationTensor M →ₐ[ℤ] PresentationTensor M :=
  TensorAlgebra.lift ℤ ((TensorAlgebra.ι ℤ).comp h)

@[simp]
theorem tensorLiftEndomorphism_ι
    (h : FreePresentation M →ₗ[ℤ] FreePresentation M) (p : FreePresentation M) :
    tensorLiftEndomorphism M h (TensorAlgebra.ι ℤ p) = TensorAlgebra.ι ℤ (h p) := by
  simp [tensorLiftEndomorphism]

/-- Two lifts of the identity presentation induce the same map on the commutator ideal modulo
Higgins's relation ideal `Z`.  This is the presentation-change calculation used below. -/
theorem commutator_sub_tensorLiftEndomorphism_mem_relationCommutatorIdeal
    (h : FreePresentation M →ₗ[ℤ] FreePresentation M)
    (hh : (presentationMap M).comp h = presentationMap M)
    (k : commutatorIdeal M) :
    (k : PresentationTensor M) - tensorLiftEndomorphism M h k ∈
      relationCommutatorIdeal M := by
  let generatorIdeal := TwoSidedIdeal.span
    (Set.range fun xy : FreePresentation M × FreePresentation M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)
  have hk : (k : PresentationTensor M) ∈ generatorIdeal := by
    change (k : PresentationTensor M) ∈ elementaryCommutatorIdeal (FreePresentation M)
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact k.property
  have hrelation (p : FreePresentation M) :
      TensorAlgebra.ι ℤ (p - h p) ∈ relationIdeal M := by
    let q : PresentationRelations M := ⟨p - h p, by
      rw [LinearMap.mem_ker]
      have hp := LinearMap.congr_fun hh p
      change presentationMap M (h p) = presentationMap M p at hp
      rw [map_sub]
      rw [hp, sub_self]⟩
    exact ι_relation_mem_relationIdeal M q
  have hspan : ∀ (u : PresentationTensor M) (hu : u ∈ generatorIdeal),
      u - tensorLiftEndomorphism M h u ∈ relationCommutatorIdeal M := by
    intro u hu
    induction hu using TwoSidedIdeal.span_induction with
    | mem u hu =>
        obtain ⟨⟨x, y⟩, rfl⟩ := hu
        let qx : relationIdeal M :=
          ⟨TensorAlgebra.ι ℤ (x - h x), hrelation x⟩
        let qy : relationIdeal M :=
          ⟨TensorAlgebra.ι ℤ (y - h y), hrelation y⟩
        have hx := (relationCommutatorIdeal M).neg_mem
          (relation_commutator_mem M (TensorAlgebra.ι ℤ y) qx)
        have hy := relation_commutator_mem M (TensorAlgebra.ι ℤ (h x)) qy
        have hz := (relationCommutatorIdeal M).add_mem hx hy
        have hid :
            ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ -
                tensorLiftEndomorphism M h
                  ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ =
              -⁅TensorAlgebra.ι ℤ y, (qx : PresentationTensor M)⁆ +
                ⁅TensorAlgebra.ι ℤ (h x), (qy : PresentationTensor M)⁆ := by
          simp only [map_sub, map_mul, tensorLiftEndomorphism_ι,
            LieRing.of_associative_ring_bracket, qx, qy]
          noncomm_ring
        rw [hid]
        exact hz
    | zero => simp
    | add x y _ _ hx hy =>
        have hz := (relationCommutatorIdeal M).add_mem hx hy
        convert hz using 1 <;> simp only [map_add] <;> abel
    | neg x _ hx =>
        have hz := (relationCommutatorIdeal M).neg_mem hx
        convert hz using 1 <;> simp only [map_neg] <;> abel
    | left_absorb a x hxmem hx =>
        let qa : relationIdeal M :=
          ⟨a - tensorLiftEndomorphism M h a, by
            rw [relationIdeal_eq_ker_tensorPresentationMap, RingHom.mem_ker]
            rw [map_sub]
            have hcomm : (tensorPresentationMap M).comp (tensorLiftEndomorphism M h) =
                tensorPresentationMap M := by
              apply TensorAlgebra.hom_ext
              apply LinearMap.ext
              intro p
              have hp : tensorPresentationMap M
                    (tensorLiftEndomorphism M h (TensorAlgebra.ι ℤ p)) =
                  tensorPresentationMap M (TensorAlgebra.ι ℤ p) := by
                rw [tensorLiftEndomorphism_ι, tensorPresentationMap_ι,
                  tensorPresentationMap_ι]
                exact congrArg (TensorAlgebra.ι ℤ)
                  (by simpa only [LinearMap.comp_apply] using LinearMap.congr_fun hh p)
              simpa only [LinearMap.comp_apply] using hp
            have ha := DFunLike.congr_fun hcomm a
            change tensorPresentationMap M (tensorLiftEndomorphism M h a) =
              tensorPresentationMap M a at ha
            change tensorPresentationMap M a -
              tensorPresentationMap M (tensorLiftEndomorphism M h a) = 0
            rw [ha, sub_self]⟩
        let kx : commutatorIdeal M := ⟨x, by
          change x ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hxmem⟩
        have hleft := relation_mul_commutator_mem M qa kx
        have hright := (relationCommutatorIdeal M).mul_mem_left
          (tensorLiftEndomorphism M h a) hx
        have hz := (relationCommutatorIdeal M).add_mem hleft hright
        have hid :
            a * x - tensorLiftEndomorphism M h (a * x) =
              (qa : PresentationTensor M) * x +
                tensorLiftEndomorphism M h a *
                  (x - tensorLiftEndomorphism M h x) := by
          simp only [qa, map_mul]
          noncomm_ring
        rw [hid]
        exact hz
    | right_absorb b x hxmem hx =>
        let qb : relationIdeal M :=
          ⟨b - tensorLiftEndomorphism M h b, by
            rw [relationIdeal_eq_ker_tensorPresentationMap, RingHom.mem_ker]
            rw [map_sub]
            have hcomm : (tensorPresentationMap M).comp (tensorLiftEndomorphism M h) =
                tensorPresentationMap M := by
              apply TensorAlgebra.hom_ext
              apply LinearMap.ext
              intro p
              have hp : tensorPresentationMap M
                    (tensorLiftEndomorphism M h (TensorAlgebra.ι ℤ p)) =
                  tensorPresentationMap M (TensorAlgebra.ι ℤ p) := by
                rw [tensorLiftEndomorphism_ι, tensorPresentationMap_ι,
                  tensorPresentationMap_ι]
                exact congrArg (TensorAlgebra.ι ℤ)
                  (by simpa only [LinearMap.comp_apply] using LinearMap.congr_fun hh p)
              simpa only [LinearMap.comp_apply] using hp
            have hb := DFunLike.congr_fun hcomm b
            change tensorPresentationMap M (tensorLiftEndomorphism M h b) =
              tensorPresentationMap M b at hb
            change tensorPresentationMap M b -
              tensorPresentationMap M (tensorLiftEndomorphism M h b) = 0
            rw [hb, sub_self]⟩
        have hdiffK : x - tensorLiftEndomorphism M h x ∈ commutatorIdeal M :=
          relationCommutatorIdeal_le_commutatorIdeal_public M hx
        let krx : commutatorIdeal M :=
          ⟨tensorLiftEndomorphism M h x, by
            have hxK : x ∈ commutatorIdeal M := by
              change x ∈ tensorCommutatorIdeal (FreePresentation M)
              rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
              exact hxmem
            have := (commutatorIdeal M).sub_mem hxK hdiffK
            convert this using 1 <;> abel⟩
        have hleft := (relationCommutatorIdeal M).mul_mem_right b hx
        have hright := commutator_mul_relation_mem M krx qb
        have hz := (relationCommutatorIdeal M).add_mem hleft hright
        have hid :
            x * b - tensorLiftEndomorphism M h (x * b) =
              (x - tensorLiftEndomorphism M h x) * b +
                tensorLiftEndomorphism M h x * (qb : PresentationTensor M) := by
          simp only [qb, map_mul]
          noncomm_ring
        rw [hid]
        exact hz
  exact hspan k hk

end LiftCongruence

namespace AuxiliaryPresentation

variable {M}
variable {P : Type v} [AddCommGroup P]

/-- Tensor evaluation attached to an arbitrary integral presentation. -/
def tensorMap (ε : P →ₗ[ℤ] M) : TensorAlgebra ℤ P →ₐ[ℤ] TensorAlgebra ℤ M :=
  TensorAlgebra.lift ℤ ((TensorAlgebra.ι ℤ).comp ε)

@[simp]
theorem tensorMap_ι (ε : P →ₗ[ℤ] M) (p : P) :
    tensorMap ε (TensorAlgebra.ι ℤ p) = TensorAlgebra.ι ℤ (ε p) := by
  simp [tensorMap, LinearMap.comp_apply]

/-- The tensor ideal generated by the degree-one relations of an arbitrary presentation. -/
def relationIdeal (ε : P →ₗ[ℤ] M) : Ideal (TensorAlgebra ℤ P) :=
  (TwoSidedIdeal.span (Set.range fun q : LinearMap.ker ε ↦
    TensorAlgebra.ι ℤ (q : P))).asIdeal

instance relationIdeal_isTwoSided (ε : P →ₗ[ℤ] M) :
    (relationIdeal ε).IsTwoSided :=
  show ((TwoSidedIdeal.span (Set.range fun q : LinearMap.ker ε ↦
    TensorAlgebra.ι ℤ (q : P))).asIdeal).IsTwoSided from inferInstance

/-- The Higgins relation ideal for an arbitrary presentation. -/
def relationCommutatorIdeal (ε : P →ₗ[ℤ] M) : Ideal (TensorAlgebra ℤ P) :=
  (TwoSidedIdeal.span
    (Set.range fun tq : TensorAlgebra ℤ P × relationIdeal ε ↦
      ⁅tq.1, (tq.2 : TensorAlgebra ℤ P)⁆)).asIdeal

instance relationCommutatorIdeal_isTwoSided (ε : P →ₗ[ℤ] M) :
    (relationCommutatorIdeal ε).IsTwoSided :=
  show ((TwoSidedIdeal.span
    (Set.range fun tq : TensorAlgebra ℤ P × relationIdeal ε ↦
      ⁅tq.1, (tq.2 : TensorAlgebra ℤ P)⁆)).asIdeal).IsTwoSided from inferInstance

theorem relation_commutator_mem (ε : P →ₗ[ℤ] M)
    (t : TensorAlgebra ℤ P) (q : relationIdeal ε) :
    ⁅t, (q : TensorAlgebra ℤ P)⁆ ∈ relationCommutatorIdeal ε :=
  TwoSidedIdeal.subset_span ⟨(t, q), rfl⟩

/-- For an arbitrary presentation, a commutator-ideal element times a relation belongs to
the relation--commutator ideal. -/
theorem commutator_mul_relation_mem (ε : P →ₗ[ℤ] M)
    (k : tensorCommutatorIdeal P) (q : relationIdeal ε) :
    (k : TensorAlgebra ℤ P) * (q : TensorAlgebra ℤ P) ∈ relationCommutatorIdeal ε := by
  let t : TensorAlgebra ℤ P := k
  have ht : t ∈ elementaryCommutatorIdeal P := by
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact k.property
  change t ∈ TwoSidedIdeal.span
    (Set.range fun xy : P × P ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆) at ht
  have hspan {u : TensorAlgebra ℤ P}
      (hu : u ∈ TwoSidedIdeal.span (Set.range fun xy : P × P ↦
        ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)) :
      ∀ q : relationIdeal ε, u * (q : TensorAlgebra ℤ P) ∈
        relationCommutatorIdeal ε := by
    induction hu using TwoSidedIdeal.span_induction with
    | mem u hu =>
      intro q
      obtain ⟨⟨x, y⟩, rfl⟩ := hu
      let yq : relationIdeal ε :=
        ⟨TensorAlgebra.ι ℤ y * (q : TensorAlgebra ℤ P),
          (relationIdeal ε).mul_mem_left (TensorAlgebra.ι ℤ y) q.property⟩
      have hxyq := relation_commutator_mem ε (TensorAlgebra.ι ℤ x) yq
      have hxq := (relationCommutatorIdeal ε).mul_mem_left
        (TensorAlgebra.ι ℤ y) (relation_commutator_mem ε (TensorAlgebra.ι ℤ x) q)
      have h := (relationCommutatorIdeal ε).sub_mem hxyq hxq
      convert h using 1 <;>
        simp only [yq, LieRing.of_associative_ring_bracket] <;> noncomm_ring
    | zero => intro q; simp
    | add x y _ _ hx hy =>
      intro q
      simpa [add_mul] using (relationCommutatorIdeal ε).add_mem (hx q) (hy q)
    | neg x _ hx => intro q; simpa using (relationCommutatorIdeal ε).neg_mem (hx q)
    | left_absorb a x _ hx =>
      intro q
      simpa [mul_assoc] using (relationCommutatorIdeal ε).mul_mem_left a (hx q)
    | right_absorb b x _ hx =>
      intro q
      let bq : relationIdeal ε :=
        ⟨b * (q : TensorAlgebra ℤ P),
          (relationIdeal ε).mul_mem_left b q.property⟩
      simpa [bq, mul_assoc] using hx bq
  exact hspan ht q

/-- For an arbitrary presentation, a relation times a commutator-ideal element belongs to
the relation--commutator ideal. -/
theorem relation_mul_commutator_mem (ε : P →ₗ[ℤ] M)
    (q : relationIdeal ε) (k : tensorCommutatorIdeal P) :
    (q : TensorAlgebra ℤ P) * (k : TensorAlgebra ℤ P) ∈ relationCommutatorIdeal ε := by
  let t : TensorAlgebra ℤ P := k
  have ht : t ∈ elementaryCommutatorIdeal P := by
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact k.property
  change t ∈ TwoSidedIdeal.span
    (Set.range fun xy : P × P ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆) at ht
  have hspan {u : TensorAlgebra ℤ P}
      (hu : u ∈ TwoSidedIdeal.span (Set.range fun xy : P × P ↦
        ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)) :
      ∀ q : relationIdeal ε, (q : TensorAlgebra ℤ P) * u ∈
        relationCommutatorIdeal ε := by
    induction hu using TwoSidedIdeal.span_induction with
    | mem u hu =>
      intro q
      obtain ⟨⟨x, y⟩, rfl⟩ := hu
      let qx : relationIdeal ε :=
        ⟨(q : TensorAlgebra ℤ P) * TensorAlgebra.ι ℤ x,
          (relationIdeal ε).mul_mem_right (TensorAlgebra.ι ℤ x) q.property⟩
      have hqxy := relation_commutator_mem ε (TensorAlgebra.ι ℤ y) qx
      have hqy := (relationCommutatorIdeal ε).mul_mem_right
        (TensorAlgebra.ι ℤ x) (relation_commutator_mem ε (TensorAlgebra.ι ℤ y) q)
      have h := (relationCommutatorIdeal ε).add_mem
        ((relationCommutatorIdeal ε).neg_mem hqxy) hqy
      convert h using 1 <;>
        simp only [qx, LieRing.of_associative_ring_bracket] <;> noncomm_ring
    | zero => intro q; simp
    | add x y _ _ hx hy =>
      intro q
      simpa [mul_add] using (relationCommutatorIdeal ε).add_mem (hx q) (hy q)
    | neg x _ hx => intro q; simpa using (relationCommutatorIdeal ε).neg_mem (hx q)
    | left_absorb a x _ hx =>
      intro q
      let qa : relationIdeal ε :=
        ⟨(q : TensorAlgebra ℤ P) * a,
          (relationIdeal ε).mul_mem_right a q.property⟩
      simpa [qa, mul_assoc] using hx qa
    | right_absorb b x _ hx =>
      intro q
      simpa [mul_assoc] using (relationCommutatorIdeal ε).mul_mem_right b (hx q)
  exact hspan ht q

/-- The Baer numerator for an arbitrary free presentation. -/
def baerNumerator (ε : P →ₗ[ℤ] M) : Ideal (TensorAlgebra ℤ P) :=
  tensorCommutatorIdeal P ⊓ relationIdeal ε

/-- Vanishing of the presentation-level Baer obstruction. -/
def ObstructionVanishes (ε : P →ₗ[ℤ] M) : Prop :=
  baerNumerator ε ≤ relationCommutatorIdeal ε

/-- A linear normalizer proves presentation-level vanishing if it kills the commutator ideal and
is congruent to the identity modulo `Z` on the relation ideal. -/
theorem obstructionVanishes_of_normalizer (ε : P →ₗ[ℤ] M)
    (θ : TensorAlgebra ℤ P →ₗ[ℤ] TensorAlgebra ℤ P)
    (hK : ∀ k, k ∈ tensorCommutatorIdeal P → θ k = 0)
    (hQ : ∀ q, q ∈ relationIdeal ε → q - θ q ∈ relationCommutatorIdeal ε) :
    ObstructionVanishes ε := by
  intro u hu
  have hz := hQ u hu.2
  rw [hK u hu.1, sub_zero] at hz
  exact hz

end AuxiliaryPresentation

namespace OrderedCyclic

variable {M}
variable {ι : Type v} [DecidableEq ι] [LinearOrder ι]

abbrev P := ι →₀ ℤ
abbrev T := TensorAlgebra ℤ (P (ι := ι))

/-- The word basis of the tensor algebra on the free module with basis `ι`. -/
noncomputable def wordBasis : Module.Basis (FreeMonoid ι) ℤ (T (ι := ι)) :=
  (Finsupp.basisSingleOne (R := ℤ) (ι := ι)).tensorAlgebra

theorem wordBasis_apply (w : FreeMonoid ι) :
    wordBasis (ι := ι) w =
      lieWord (P (ι := ι))
        ((FreeMonoid.toList w).map fun i ↦ Finsupp.single i 1) := by
  let b := Finsupp.basisSingleOne (R := ℤ) (ι := ι)
  change (TensorAlgebra.equivFreeAlgebra b).symm
      (FreeAlgebra.basisFreeMonoid ℤ ι w) = _
  apply (TensorAlgebra.equivFreeAlgebra b).injective
  rw [AlgEquiv.apply_symm_apply]
  simp only [lieWord, map_list_prod, List.map_map, Function.comp_apply]
  have hgen : ∀ i : ι,
      TensorAlgebra.equivFreeAlgebra b
          (TensorAlgebra.ι ℤ (Finsupp.single i 1)) = FreeAlgebra.ι ℤ i := by
    intro i
    exact TensorAlgebra.equivFreeAlgebra_ι_apply b i
  rw [show (↑(TensorAlgebra.equivFreeAlgebra b) ∘ ↑(TensorAlgebra.ι ℤ) ∘
      fun i ↦ Finsupp.single i 1) = FreeAlgebra.ι ℤ from funext hgen]
  rw [FreeAlgebra.basisFreeMonoid, Module.Basis.map_apply]
  apply FreeAlgebra.equivMonoidAlgebraFreeMonoid.injective
  change FreeAlgebra.equivMonoidAlgebraFreeMonoid
      (FreeAlgebra.equivMonoidAlgebraFreeMonoid.symm (Finsupp.single w 1)) = _
  rw [AlgEquiv.apply_symm_apply]
  induction w using FreeMonoid.recOn with
  | h0 => simp [MonoidAlgebra.one_def]
  | ih i w ih =>
      simp only [FreeMonoid.toList_of_mul, List.map_cons, List.prod_cons, map_mul]
      rw [← ih]
      have hι : FreeAlgebra.equivMonoidAlgebraFreeMonoid (FreeAlgebra.ι ℤ i) =
          Finsupp.single (FreeMonoid.of i) 1 := by
        simp [FreeAlgebra.equivMonoidAlgebraFreeMonoid]
      rw [hι]
      simp

@[simp]
theorem wordBasis_of (i : ι) :
    wordBasis (ι := ι) (FreeMonoid.of i) =
      TensorAlgebra.ι ℤ (Finsupp.single i 1) := by
  rw [wordBasis_apply]
  simp [lieWord]

@[simp]
theorem wordBasis_mul (w₁ w₂ : FreeMonoid ι) :
    wordBasis (ι := ι) w₁ * wordBasis (ι := ι) w₂ =
      wordBasis (ι := ι) (w₁ * w₂) := by
  rw [wordBasis_apply, wordBasis_apply, wordBasis_apply]
  simp only [FreeMonoid.toList_mul, List.map_append, lieWord_append]

/-- The tensor word attached to a list of basis indices. -/
noncomputable def word (xs : List ι) : T (ι := ι) :=
  wordBasis (ι := ι) (FreeMonoid.ofList xs)

@[simp] theorem word_nil : word (ι := ι) [] = 1 := by
  rw [word, wordBasis_apply]
  simp [lieWord]

@[simp] theorem word_singleton (i : ι) :
    word (ι := ι) [i] = TensorAlgebra.ι ℤ (Finsupp.single i 1) := by
  simp [word]

theorem word_append (xs ys : List ι) :
    word (ι := ι) (xs ++ ys) = word (ι := ι) xs * word (ι := ι) ys := by
  simp only [word, FreeMonoid.ofList_append, wordBasis_mul]

@[simp] theorem word_cons (i : ι) (xs : List ι) :
    word (ι := ι) (i :: xs) =
      TensorAlgebra.ι ℤ (Finsupp.single i 1) * word (ι := ι) xs := by
  rw [show i :: xs = [i] ++ xs by rfl, word_append, word_singleton]

theorem smul_word_split (c : ℤ) (xs ys : List ι) (i : ι) :
    c • word (ι := ι) (xs ++ i :: ys) =
      word (ι := ι) xs *
        TensorAlgebra.ι ℤ (c • Finsupp.single i 1) * word (ι := ι) ys := by
  rw [show xs ++ i :: ys = xs ++ [i] ++ ys by simp, word_append, word_append,
    word_singleton, map_smul]
  noncomm_ring

/-- The ordered word representing an exponent vector. -/
def exponentWord (e : ι →₀ ℕ) : FreeMonoid ι :=
  FreeMonoid.ofList ((Finsupp.toMultiset e).sort (· ≤ ·))

/-- The linear ordered-word section of the symmetric quotient. -/
noncomputable def symmetricSection :
    SymmetricAlgebra ℤ (P (ι := ι)) →ₗ[ℤ] T (ι := ι) :=
  ((Finsupp.basisSingleOne (R := ℤ) (ι := ι)).symmetricAlgebra.constr ℤ)
    (fun e ↦ wordBasis (ι := ι) (exponentWord e))

@[simp]
theorem equivMvPolynomial_symmetricBasis (e : ι →₀ ℕ) :
    SymmetricAlgebra.equivMvPolynomial
        (Finsupp.basisSingleOne (R := ℤ) (ι := ι))
      ((Finsupp.basisSingleOne (R := ℤ) (ι := ι)).symmetricAlgebra e) =
        MvPolynomial.monomial e 1 := by
  rw [Module.Basis.symmetricAlgebra, Module.Basis.map_apply]
  simp

theorem prod_X_eq_monomial_toFinsupp (xs : List ι) :
    (xs.map (MvPolynomial.X : ι → MvPolynomial ι ℤ)).prod =
      MvPolynomial.monomial (Multiset.toFinsupp (xs : Multiset ι)) 1 := by
  induction xs with
  | nil => simp
  | cons i xs ih =>
      rw [List.map_cons, List.prod_cons, ih]
      rw [show Multiset.toFinsupp ((i :: xs : List ι) : Multiset ι) =
          Multiset.toFinsupp (xs : Multiset ι) + Finsupp.single i 1 by
        ext j
        by_cases hji : j = i
        · subst j
          simp
        · simp [hji, Ne.symm hji]]
      rw [MvPolynomial.monomial_add_single]
      simp [mul_comm]

theorem symmetricMap_wordBasis (w : FreeMonoid ι) :
    SymmetricAlgebra.algHom ℤ (P (ι := ι)) (wordBasis (ι := ι) w) =
      (Finsupp.basisSingleOne (R := ℤ) (ι := ι)).symmetricAlgebra
        (Multiset.toFinsupp (FreeMonoid.toList w : Multiset ι)) := by
  apply (SymmetricAlgebra.equivMvPolynomial
    (Finsupp.basisSingleOne (R := ℤ) (ι := ι))).injective
  rw [equivMvPolynomial_symmetricBasis]
  rw [wordBasis_apply]
  simp only [lieWord, map_list_prod, List.map_map, Function.comp_apply, map_list_prod]
  have hgen : ∀ i : ι,
      SymmetricAlgebra.equivMvPolynomial
          (Finsupp.basisSingleOne (R := ℤ) (ι := ι))
        (SymmetricAlgebra.algHom ℤ (P (ι := ι))
          (TensorAlgebra.ι ℤ (Finsupp.single i 1))) = MvPolynomial.X i := by
    intro i
    change SymmetricAlgebra.equivMvPolynomial
        (Finsupp.basisSingleOne (R := ℤ) (ι := ι))
      (SymmetricAlgebra.ι ℤ (P (ι := ι)) (Finsupp.single i 1)) = _
    exact SymmetricAlgebra.equivMvPolynomial_ι_apply
      (Finsupp.basisSingleOne (R := ℤ) (ι := ι)) i
  have hfun : (↑(SymmetricAlgebra.equivMvPolynomial
      (Finsupp.basisSingleOne (R := ℤ) (ι := ι))) ∘
      ↑(SymmetricAlgebra.algHom ℤ (P (ι := ι))) ∘
      ↑(TensorAlgebra.ι ℤ) ∘ fun i ↦ Finsupp.single i 1) = MvPolynomial.X :=
    funext hgen
  rw [hfun]
  exact prod_X_eq_monomial_toFinsupp _

/-- Permuting a tensor word changes it by an element of the tensor commutator ideal. -/
theorem word_sub_word_mem_commutatorIdeal {xs ys : List ι} (h : xs.Perm ys) :
    word (ι := ι) xs - word (ι := ι) ys ∈
      tensorCommutatorIdeal (P (ι := ι)) := by
  rw [tensorCommutatorIdeal, RingHom.mem_ker]
  change SymmetricAlgebra.algHom ℤ (P (ι := ι))
    (word (ι := ι) xs - word (ι := ι) ys) = 0
  rw [map_sub, show word (ι := ι) xs =
      wordBasis (ι := ι) (FreeMonoid.ofList xs) by rfl,
    show word (ι := ι) ys =
      wordBasis (ι := ι) (FreeMonoid.ofList ys) by rfl,
    symmetricMap_wordBasis, symmetricMap_wordBasis,
    FreeMonoid.toList_ofList, FreeMonoid.toList_ofList]
  have hm : (xs : Multiset ι) = (ys : Multiset ι) := Multiset.coe_eq_coe.mpr h
  rw [hm, sub_self]

/-- A scaled word containing a one-coordinate relation belongs to the relation ideal. -/
theorem smul_word_mem_relationIdeal (ε : P (ι := ι) →ₗ[ℤ] M)
    {c : ℤ} {i : ι} {xs : List ι}
    (hrel : ε (c • Finsupp.single i 1) = 0) (hi : i ∈ xs) :
    c • word (ι := ι) xs ∈ AuxiliaryPresentation.relationIdeal ε := by
  obtain ⟨as, bs, rfl⟩ := List.mem_iff_append.mp hi
  let q : LinearMap.ker ε := ⟨c • Finsupp.single i 1, by
    exact (LinearMap.mem_ker).mpr hrel⟩
  have hq : TensorAlgebra.ι ℤ (q : P (ι := ι)) ∈
      AuxiliaryPresentation.relationIdeal ε := by
    change TensorAlgebra.ι ℤ (q : P (ι := ι)) ∈ TwoSidedIdeal.span
      (Set.range fun r : LinearMap.ker ε ↦ TensorAlgebra.ι ℤ (r : P (ι := ι)))
    exact TwoSidedIdeal.subset_span ⟨q, rfl⟩
  rw [smul_word_split]
  exact (AuxiliaryPresentation.relationIdeal ε).mul_mem_right _
    ((AuxiliaryPresentation.relationIdeal ε).mul_mem_left _ hq)

/-- Higgins's permutation lemma: once a word contains a scalar one-coordinate relation, any
permutation of its letters is equal modulo the relation--commutator ideal. -/
theorem smul_word_perm_mod_relationCommutatorIdeal
    (ε : P (ι := ι) →ₗ[ℤ] M) {c : ℤ} {i : ι} {xs ys : List ι}
    (hrel : ε (c • Finsupp.single i 1) = 0) (hi : i ∈ xs) (hp : xs.Perm ys) :
    c • word (ι := ι) xs - c • word (ι := ι) ys ∈
      AuxiliaryPresentation.relationCommutatorIdeal ε := by
  induction hp with
  | nil => simp
  | @cons a xs ys hp ih =>
      rw [word_cons, word_cons]
      rcases List.mem_cons.mp hi with hia | hi
      · subst a
        let q : AuxiliaryPresentation.relationIdeal ε :=
          ⟨TensorAlgebra.ι ℤ (c • Finsupp.single i 1), by
            apply TwoSidedIdeal.subset_span
            exact ⟨⟨c • Finsupp.single i 1, (LinearMap.mem_ker).mpr hrel⟩, rfl⟩⟩
        let k : tensorCommutatorIdeal (P (ι := ι)) :=
          ⟨word (ι := ι) xs - word (ι := ι) ys,
            word_sub_word_mem_commutatorIdeal hp⟩
        have hz := AuxiliaryPresentation.relation_mul_commutator_mem ε q k
        convert hz using 1 <;> simp only [q, k, map_smul] <;> noncomm_ring
      · have hz := (AuxiliaryPresentation.relationCommutatorIdeal ε).mul_mem_left
          (TensorAlgebra.ι ℤ (Finsupp.single a 1)) (ih hi)
        convert hz using 1 <;> noncomm_ring
  | swap a b xs =>
      simp only [List.mem_cons] at hi
      rw [word_cons, word_cons, word_cons, word_cons]
      rcases hi with hib | hia | hi
      · subst b
        let q : AuxiliaryPresentation.relationIdeal ε :=
          ⟨TensorAlgebra.ι ℤ (c • Finsupp.single i 1), by
            apply TwoSidedIdeal.subset_span
            exact ⟨⟨c • Finsupp.single i 1, (LinearMap.mem_ker).mpr hrel⟩, rfl⟩⟩
        have hz := (AuxiliaryPresentation.relationCommutatorIdeal ε).mul_mem_right
          (word (ι := ι) xs)
          ((AuxiliaryPresentation.relationCommutatorIdeal ε).neg_mem
            (AuxiliaryPresentation.relation_commutator_mem ε
              (TensorAlgebra.ι ℤ (Finsupp.single a 1)) q))
        convert hz using 1 <;>
          simp only [q, LieRing.of_associative_ring_bracket, map_smul] <;> noncomm_ring
      · subst a
        let q : AuxiliaryPresentation.relationIdeal ε :=
          ⟨TensorAlgebra.ι ℤ (c • Finsupp.single i 1), by
            apply TwoSidedIdeal.subset_span
            exact ⟨⟨c • Finsupp.single i 1, (LinearMap.mem_ker).mpr hrel⟩, rfl⟩⟩
        have hz := (AuxiliaryPresentation.relationCommutatorIdeal ε).mul_mem_right
          (word (ι := ι) xs)
          (AuxiliaryPresentation.relation_commutator_mem ε
            (TensorAlgebra.ι ℤ (Finsupp.single b 1)) q)
        convert hz using 1 <;>
          simp only [q, LieRing.of_associative_ring_bracket, map_smul] <;> noncomm_ring
      · let k : tensorCommutatorIdeal (P (ι := ι)) :=
          ⟨⁅TensorAlgebra.ι ℤ (Finsupp.single b (1 : ℤ)),
              TensorAlgebra.ι ℤ (Finsupp.single a (1 : ℤ))⁆, by
            have hk := elementary_commutator_mem (P (ι := ι))
              (Finsupp.single b (1 : ℤ)) (Finsupp.single a (1 : ℤ))
            rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal] at hk
            exact hk⟩
        let q : AuxiliaryPresentation.relationIdeal ε :=
          ⟨c • word (ι := ι) xs, smul_word_mem_relationIdeal ε hrel hi⟩
        have hz := AuxiliaryPresentation.commutator_mul_relation_mem ε k q
        have hz' : c • (⁅TensorAlgebra.ι ℤ (Finsupp.single b (1 : ℤ)),
              TensorAlgebra.ι ℤ (Finsupp.single a (1 : ℤ))⁆ * word (ι := ι) xs) ∈
            AuxiliaryPresentation.relationCommutatorIdeal ε := by
          convert hz using 1 <;> simp only [k, q] <;> noncomm_ring
        change c • ((TensorAlgebra.ι ℤ (Finsupp.single b (1 : ℤ)) *
            TensorAlgebra.ι ℤ (Finsupp.single a (1 : ℤ)) -
            TensorAlgebra.ι ℤ (Finsupp.single a (1 : ℤ)) *
              TensorAlgebra.ι ℤ (Finsupp.single b (1 : ℤ))) * word (ι := ι) xs) ∈
          AuxiliaryPresentation.relationCommutatorIdeal ε at hz'
        simpa only [sub_mul, mul_assoc, smul_sub, smul_add, smul_neg,
          neg_one_smul] using hz'
  | @trans xs ys zs hxy hyz ihxy ihyz =>
      have h₁ := ihxy hi
      have h₂ := ihyz ((hxy.mem_iff).mp hi)
      have hz := (AuxiliaryPresentation.relationCommutatorIdeal ε).add_mem h₁ h₂
      convert hz using 1 <;> abel

/-- Higgins's ordering map `θ`: pass to the symmetric algebra, then choose the ordered word. -/
noncomputable def normalizer : T (ι := ι) →ₗ[ℤ] T (ι := ι) :=
  (symmetricSection (ι := ι)).comp
    (SymmetricAlgebra.algHom ℤ (P (ι := ι))).toLinearMap

@[simp]
theorem normalizer_wordBasis (w : FreeMonoid ι) :
    normalizer (ι := ι) (wordBasis (ι := ι) w) =
      wordBasis (ι := ι)
        (exponentWord (Multiset.toFinsupp (FreeMonoid.toList w : Multiset ι))) := by
  rw [normalizer, LinearMap.comp_apply]
  change symmetricSection (ι := ι)
      (SymmetricAlgebra.algHom ℤ (P (ι := ι)) (wordBasis (ι := ι) w)) = _
  rw [symmetricMap_wordBasis, symmetricSection]
  exact Module.Basis.constr_basis
    ((Finsupp.basisSingleOne (R := ℤ) (ι := ι)).symmetricAlgebra) ℤ
    (fun e ↦ wordBasis (ι := ι) (exponentWord e)) _

@[simp]
theorem normalizer_word (xs : List ι) :
    normalizer (ι := ι) (word (ι := ι) xs) =
      word (ι := ι) ((xs : Multiset ι).sort (· ≤ ·)) := by
  rw [show word (ι := ι) xs =
      wordBasis (ι := ι) (FreeMonoid.ofList xs) by rfl,
    normalizer_wordBasis, FreeMonoid.toList_ofList]
  change wordBasis (ι := ι)
    (FreeMonoid.ofList
      ((Finsupp.toMultiset (Multiset.toFinsupp (xs : Multiset ι))).sort (· ≤ ·))) = _
  rw [Multiset.toFinsupp_toMultiset]
  rfl

/-- The normalizer calculation for a diagonal relation, with word-basis factors on both sides. -/
theorem word_mul_diagonalRelation_mul_word_mod
    (ε : P (ι := ι) →ₗ[ℤ] M) (p : P (ι := ι))
    (hdiag : ∀ i, ε (p i • Finsupp.single i 1) = 0)
    (as bs : List ι) :
    word (ι := ι) as * TensorAlgebra.ι ℤ p * word (ι := ι) bs -
        normalizer (ι := ι)
          (word (ι := ι) as * TensorAlgebra.ι ℤ p * word (ι := ι) bs) ∈
      AuxiliaryPresentation.relationCommutatorIdeal ε := by
  induction p using Finsupp.induction with
  | zero => simp
  | single_add i c p hip hc ih =>
      have hpi : p i = 0 := Finsupp.notMem_support_iff.mp hip
      have hci : ε (c • Finsupp.single i 1) = 0 := by
        simpa [hpi] using hdiag i
      have hpdiag : ∀ j, ε (p j • Finsupp.single j 1) = 0 := by
        intro j
        by_cases hji : j = i
        · subst j
          simp [hpi]
        · simpa [hji] using hdiag j
      have hp := ih hpdiag
      have hall : (as ++ i :: bs).Perm
          (((as ++ i :: bs : List ι) : Multiset ι).sort (· ≤ ·)) := by
        exact (List.mergeSort_perm (as ++ i :: bs) _).symm
      have hcmod := smul_word_perm_mod_relationCommutatorIdeal ε hci
        (by simp) hall
      have hsingle :
          word (ι := ι) as *
                TensorAlgebra.ι ℤ (Finsupp.single i c) * word (ι := ι) bs -
              normalizer (ι := ι)
                (word (ι := ι) as *
                  TensorAlgebra.ι ℤ (Finsupp.single i c) * word (ι := ι) bs) ∈
            AuxiliaryPresentation.relationCommutatorIdeal ε := by
        have heq : word (ι := ι) as *
              TensorAlgebra.ι ℤ (Finsupp.single i c) * word (ι := ι) bs =
            c • word (ι := ι) (as ++ i :: bs) := by
          rw [show Finsupp.single i c = c • Finsupp.single i 1 by
            ext j
            by_cases hji : j = i <;> simp [hji], smul_word_split]
        rw [heq, map_smul, normalizer_word]
        exact hcmod
      have hz := (AuxiliaryPresentation.relationCommutatorIdeal ε).add_mem hsingle hp
      convert hz using 1 <;>
        simp only [map_add, map_mul, add_mul, mul_add] <;> abel

/-- The preceding word calculation extends by linearity to arbitrary tensor factors. -/
theorem mul_diagonalRelation_mul_mod
    (ε : P (ι := ι) →ₗ[ℤ] M) (p : P (ι := ι))
    (hdiag : ∀ i, ε (p i • Finsupp.single i 1) = 0)
    (a b : T (ι := ι)) :
    a * TensorAlgebra.ι ℤ p * b -
        normalizer (ι := ι) (a * TensorAlgebra.ι ℤ p * b) ∈
      AuxiliaryPresentation.relationCommutatorIdeal ε := by
  let Z := AuxiliaryPresentation.relationCommutatorIdeal ε
  let π : T (ι := ι) →ₗ[ℤ] T (ι := ι) ⧸ Z :=
    (Ideal.Quotient.mkₐ ℤ Z).toLinearMap
  let defect : T (ι := ι) →ₗ[ℤ] T (ι := ι) →ₗ[ℤ] T (ι := ι) ⧸ Z :=
    { toFun := fun a ↦
        { toFun := fun b ↦ π (a * TensorAlgebra.ι ℤ p * b -
              normalizer (ι := ι) (a * TensorAlgebra.ι ℤ p * b))
          map_add' := by
            intro x y
            simp only [mul_add, map_add, map_sub]
            abel
          map_smul' := by
            intro c x
            simp only [mul_smul_comm, map_smul, map_sub, RingHom.id_apply,
              smul_sub]
            module }
      map_add' := by
        intro x y
        apply LinearMap.ext
        intro b
        change π ((x + y) * TensorAlgebra.ι ℤ p * b -
            normalizer (ι := ι) ((x + y) * TensorAlgebra.ι ℤ p * b)) =
          π (x * TensorAlgebra.ι ℤ p * b -
              normalizer (ι := ι) (x * TensorAlgebra.ι ℤ p * b)) +
            π (y * TensorAlgebra.ι ℤ p * b -
              normalizer (ι := ι) (y * TensorAlgebra.ι ℤ p * b))
        simp only [add_mul, map_add, map_sub, LinearMap.add_apply]
        module
      map_smul' := by
        intro c x
        apply LinearMap.ext
        intro b
        change π ((c • x) * TensorAlgebra.ι ℤ p * b -
            normalizer (ι := ι) ((c • x) * TensorAlgebra.ι ℤ p * b)) =
          c • π (x * TensorAlgebra.ι ℤ p * b -
            normalizer (ι := ι) (x * TensorAlgebra.ι ℤ p * b))
        simp only [smul_mul_assoc, map_smul, map_sub, LinearMap.smul_apply,
          RingHom.id_apply, smul_sub]
        module }
  have hdefect : defect = 0 := by
    apply (wordBasis (ι := ι)).ext
    intro wa
    apply (wordBasis (ι := ι)).ext
    intro wb
    change π (wordBasis (ι := ι) wa * TensorAlgebra.ι ℤ p *
        wordBasis (ι := ι) wb - normalizer (ι := ι)
          (wordBasis (ι := ι) wa * TensorAlgebra.ι ℤ p *
            wordBasis (ι := ι) wb)) = 0
    rw [show wordBasis (ι := ι) wa =
        word (ι := ι) (FreeMonoid.toList wa) by
          simp only [word, FreeMonoid.ofList_toList],
      show wordBasis (ι := ι) wb =
        word (ι := ι) (FreeMonoid.toList wb) by
          simp only [word, FreeMonoid.ofList_toList]]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr
      (word_mul_diagonalRelation_mul_word_mod ε p hdiag _ _)
  have hab := LinearMap.congr_fun (LinearMap.congr_fun hdefect a) b
  change π (a * TensorAlgebra.ι ℤ p * b -
    normalizer (ι := ι) (a * TensorAlgebra.ι ℤ p * b)) = 0 at hab
  exact Ideal.Quotient.eq_zero_iff_mem.mp hab

/-- The ordered normalizer kills the commutator ideal. -/
theorem normalizer_eq_zero_of_mem_commutatorIdeal
    {u : T (ι := ι)} (hu : u ∈ tensorCommutatorIdeal (P (ι := ι))) :
    normalizer (ι := ι) u = 0 := by
  rw [tensorCommutatorIdeal, RingHom.mem_ker] at hu
  change SymmetricAlgebra.algHom ℤ (P (ι := ι)) u = 0 at hu
  rw [normalizer, LinearMap.comp_apply]
  change symmetricSection (ι := ι)
    (SymmetricAlgebra.algHom ℤ (P (ι := ι)) u) = 0
  rw [hu, map_zero]

/-- Higgins's ordered-word argument for any presentation whose relations are diagonal term by
term in the chosen basis. -/
theorem auxiliaryObstructionVanishes_of_diagonal
    (ε : P (ι := ι) →ₗ[ℤ] M)
    (hdiag : ∀ (q : LinearMap.ker ε) i,
      ε (q.1 i • Finsupp.single i 1) = 0) :
    AuxiliaryPresentation.ObstructionVanishes ε := by
  apply AuxiliaryPresentation.obstructionVanishes_of_normalizer ε
    (normalizer (ι := ι))
  · intro k hk
    exact normalizer_eq_zero_of_mem_commutatorIdeal hk
  · intro q hq
    change q ∈ TwoSidedIdeal.span
      (Set.range fun r : LinearMap.ker ε ↦ TensorAlgebra.ι ℤ (r : P (ι := ι))) at hq
    have hspan {u : T (ι := ι)}
        (hu : u ∈ TwoSidedIdeal.span
          (Set.range fun r : LinearMap.ker ε ↦
            TensorAlgebra.ι ℤ (r : P (ι := ι)))) :
        ∀ a b : T (ι := ι),
          a * u * b - normalizer (ι := ι) (a * u * b) ∈
            AuxiliaryPresentation.relationCommutatorIdeal ε := by
      induction hu using TwoSidedIdeal.span_induction with
      | mem u hu =>
          intro a b
          obtain ⟨r, rfl⟩ := hu
          exact mul_diagonalRelation_mul_mod ε r (hdiag r) a b
      | zero => intro a b; simp
      | add x y _ _ hx hy =>
          intro a b
          have hz := (AuxiliaryPresentation.relationCommutatorIdeal ε).add_mem
            (hx a b) (hy a b)
          convert hz using 1 <;>
            simp only [mul_add, add_mul, map_add] <;> abel
      | neg x _ hx =>
          intro a b
          have hz := (AuxiliaryPresentation.relationCommutatorIdeal ε).neg_mem (hx a b)
          convert hz using 1 <;>
            simp only [mul_neg, neg_mul, map_neg] <;> abel
      | left_absorb c x _ hx =>
          intro a b
          simpa only [mul_assoc] using hx (a * c) b
      | right_absorb c x _ hx =>
          intro a b
          simpa only [mul_assoc] using hx a (c * b)
    simpa using hspan hq 1 1

end OrderedCyclic

namespace AuxiliaryPresentation

variable {M : Type w} [AddCommGroup M]
variable {P : Type u} [AddCommGroup P]
variable {P' : Type v} [AddCommGroup P']

/-- A linear map sends the tensor commutator ideal into the tensor commutator ideal. -/
theorem tensorMap_mem_commutatorIdeal (f : P →ₗ[ℤ] P')
    {u : TensorAlgebra ℤ P} (hu : u ∈ tensorCommutatorIdeal P) :
    tensorMap f u ∈ tensorCommutatorIdeal P' := by
  have hu' : u ∈ elementaryCommutatorIdeal P := by
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact hu
  change u ∈ TwoSidedIdeal.span (Set.range fun xy : P × P ↦
    ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆) at hu'
  have hspan {x : TensorAlgebra ℤ P}
      (hx : x ∈ TwoSidedIdeal.span (Set.range fun xy : P × P ↦
        ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)) :
      tensorMap f x ∈ tensorCommutatorIdeal P' := by
    induction hx using TwoSidedIdeal.span_induction with
    | mem u hu =>
      obtain ⟨⟨x, y⟩, rfl⟩ := hu
      rw [show tensorMap f ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ =
          ⁅TensorAlgebra.ι ℤ (f x), TensorAlgebra.ι ℤ (f y)⁆ by
        simp only [LieRing.of_associative_ring_bracket, map_sub, map_mul,
          tensorMap_ι]]
      rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
      exact elementary_commutator_mem P' (f x) (f y)
    | zero => simp
    | add x y _ _ hx hy => simpa using (tensorCommutatorIdeal P').add_mem hx hy
    | neg x _ hx => simpa using (tensorCommutatorIdeal P').neg_mem hx
    | left_absorb a x _ hx =>
      simpa only [map_mul] using (tensorCommutatorIdeal P').mul_mem_left (tensorMap f a) hx
    | right_absorb b x _ hx =>
      simpa only [map_mul] using (tensorCommutatorIdeal P').mul_mem_right (tensorMap f b) hx
  exact hspan hu'

/-- A compatible map of presentations sends relation ideals into relation ideals. -/
theorem tensorMap_mem_relationIdeal (ε : P →ₗ[ℤ] M) (ε' : P' →ₗ[ℤ] M)
    (f : P →ₗ[ℤ] P') (hf : ε'.comp f = ε)
    {u : TensorAlgebra ℤ P} (hu : u ∈ relationIdeal ε) :
    tensorMap f u ∈ relationIdeal ε' := by
  change u ∈ TwoSidedIdeal.span (Set.range fun q : LinearMap.ker ε ↦
    TensorAlgebra.ι ℤ (q : P)) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨q, rfl⟩ := hu
      let q' : LinearMap.ker ε' := ⟨f q, by
        rw [LinearMap.mem_ker]
        have h := LinearMap.congr_fun hf q
        have h' : ε' (f q) = ε q := by
          simpa only [LinearMap.comp_apply] using h
        exact h'.trans q.property⟩
      rw [tensorMap_ι]
      change TensorAlgebra.ι ℤ (q' : P') ∈ TwoSidedIdeal.span
        (Set.range fun r : LinearMap.ker ε' ↦ TensorAlgebra.ι ℤ (r : P'))
      exact TwoSidedIdeal.subset_span ⟨q', rfl⟩
  | zero => simp
  | add x y _ _ hx hy => simpa using (relationIdeal ε').add_mem hx hy
  | neg x _ hx => simpa using (relationIdeal ε').neg_mem hx
  | left_absorb a x _ hx =>
      simpa only [map_mul] using (relationIdeal ε').mul_mem_left (tensorMap f a) hx
  | right_absorb b x _ hx =>
      simpa only [map_mul] using (relationIdeal ε').mul_mem_right (tensorMap f b) hx

/-- A compatible map of presentations sends Higgins's ideal `Z=[T,Q]` into `Z`. -/
theorem tensorMap_mem_relationCommutatorIdeal
    (ε : P →ₗ[ℤ] M) (ε' : P' →ₗ[ℤ] M)
    (f : P →ₗ[ℤ] P') (hf : ε'.comp f = ε)
    {u : TensorAlgebra ℤ P} (hu : u ∈ relationCommutatorIdeal ε) :
    tensorMap f u ∈ relationCommutatorIdeal ε' := by
  change u ∈ TwoSidedIdeal.span
    (Set.range fun tq : TensorAlgebra ℤ P × relationIdeal ε ↦
      ⁅tq.1, (tq.2 : TensorAlgebra ℤ P)⁆) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨⟨t, q⟩, rfl⟩ := hu
      let q' : relationIdeal ε' :=
        ⟨tensorMap f q, tensorMap_mem_relationIdeal ε ε' f hf q.property⟩
      rw [show tensorMap f ⁅t, (q : TensorAlgebra ℤ P)⁆ =
          ⁅tensorMap f t, (q' : TensorAlgebra ℤ P')⁆ by
        simp only [q', LieRing.of_associative_ring_bracket, map_sub, map_mul]]
      exact relation_commutator_mem ε' (tensorMap f t) q'
  | zero => simp
  | add x y _ _ hx hy => simpa using (relationCommutatorIdeal ε').add_mem hx hy
  | neg x _ hx => simpa using (relationCommutatorIdeal ε').neg_mem hx
  | left_absorb a x _ hx =>
      simpa only [map_mul] using
        (relationCommutatorIdeal ε').mul_mem_left (tensorMap f a) hx
  | right_absorb b x _ hx =>
      simpa only [map_mul] using
        (relationCommutatorIdeal ε').mul_mem_right (tensorMap f b) hx

end AuxiliaryPresentation

section PresentationTransport

variable {M}

/-- Vanishing for a surjective free presentation implies vanishing of Higgins's canonical
obstruction.  The proof uses compatible lifts in both directions and the lift-congruence lemma. -/
theorem obstructionVanishes_of_auxiliary_freePresentation
    {ι : Type v} [DecidableEq ι]
    (ε : (ι →₀ ℤ) →ₗ[ℤ] M) (hε : Function.Surjective ε)
    (haux : AuxiliaryPresentation.ObstructionVanishes ε) :
    ObstructionVanishes M := by
  let σ : FreePresentation M →ₗ[ℤ] (ι →₀ ℤ) :=
    Classical.choose (Module.projective_lifting_property ε (presentationMap M) hε)
  have hσ : ε.comp σ = presentationMap M :=
    Classical.choose_spec (Module.projective_lifting_property ε (presentationMap M) hε)
  let τ : (ι →₀ ℤ) →ₗ[ℤ] FreePresentation M :=
    Classical.choose (Module.projective_lifting_property (presentationMap M) ε
      (presentationMap_surjective M))
  have hτ : (presentationMap M).comp τ = ε :=
    Classical.choose_spec (Module.projective_lifting_property (presentationMap M) ε
      (presentationMap_surjective M))
  rw [obstructionVanishes_iff]
  intro u hu
  let Φ := AuxiliaryPresentation.tensorMap σ
  let Ψ := AuxiliaryPresentation.tensorMap τ
  have hΦK : Φ u ∈ tensorCommutatorIdeal (ι →₀ ℤ) :=
    AuxiliaryPresentation.tensorMap_mem_commutatorIdeal σ hu.1
  have hΦQ : Φ u ∈ AuxiliaryPresentation.relationIdeal ε := by
    exact AuxiliaryPresentation.tensorMap_mem_relationIdeal
      (presentationMap M) ε σ hσ hu.2
  have hΦZ : Φ u ∈ AuxiliaryPresentation.relationCommutatorIdeal ε :=
    haux ⟨hΦK, hΦQ⟩
  have hΨZ : Ψ (Φ u) ∈ relationCommutatorIdeal M := by
    exact AuxiliaryPresentation.tensorMap_mem_relationCommutatorIdeal
      ε (presentationMap M) τ hτ hΦZ
  have hcomp : Ψ.comp Φ = tensorLiftEndomorphism M (τ.comp σ) := by
    apply TensorAlgebra.hom_ext
    apply LinearMap.ext
    intro p
    simp only [LinearMap.comp_apply, AlgHom.toLinearMap_apply]
    rw [AlgHom.comp_apply, show Φ (TensorAlgebra.ι ℤ p) =
        TensorAlgebra.ι ℤ (σ p) by
          exact AuxiliaryPresentation.tensorMap_ι σ p,
      show Ψ (TensorAlgebra.ι ℤ (σ p)) = TensorAlgebra.ι ℤ (τ (σ p)) by
          exact AuxiliaryPresentation.tensorMap_ι τ (σ p),
      tensorLiftEndomorphism_ι]
    rfl
  have hlift : (presentationMap M).comp (τ.comp σ) = presentationMap M := by
    apply LinearMap.ext
    intro p
    change presentationMap M (τ (σ p)) = presentationMap M p
    rw [show presentationMap M (τ (σ p)) = ε (σ p) by
        exact LinearMap.congr_fun hτ (σ p),
      show ε (σ p) = presentationMap M p by
        exact LinearMap.congr_fun hσ p]
  let k : commutatorIdeal M := ⟨u, hu.1⟩
  have hdiff :=
    commutator_sub_tensorLiftEndomorphism_mem_relationCommutatorIdeal (M := M)
      (τ.comp σ) hlift k
  change u - tensorLiftEndomorphism M (τ.comp σ) u ∈ relationCommutatorIdeal M at hdiff
  have hΨΦ : Ψ (Φ u) = tensorLiftEndomorphism M (τ.comp σ) u :=
    DFunLike.congr_fun hcomp u
  rw [← hΨΦ] at hdiff
  have hz := (relationCommutatorIdeal M).add_mem hdiff hΨZ
  convert hz using 1 <;> abel

end PresentationTransport

/-- **Higgins's cyclic-sum theorem.** If the underlying abelian group of `M` is an internal
direct sum of cyclic groups, then its Baer obstruction `B(M)` vanishes.  Equivalently, the
canonical numerator `K(P) ∩ Q` is contained in `Z = [T(P),Q]`. -/
theorem obstructionVanishes_of_directSumOfCyclic
    (h : IsDirectSumOfCyclic M) : ObstructionVanishes M := by
  obtain ⟨ι, decι, C, hC, cyclic⟩ := h
  letI : DecidableEq ι := decι
  letI : LinearOrder ι := WellOrderingRel.isWellOrder.linearOrder
  let ε := CyclicPresentation.map C cyclic
  have hdiag : ∀ (q : LinearMap.ker ε) i,
      ε (q.1 i • Finsupp.single i 1) = 0 := by
    intro q i
    rw [show q.1 i • Finsupp.single i 1 = Finsupp.single i (q.1 i) by
      ext j
      by_cases hji : j = i <;> simp [hji], CyclicPresentation.map_single]
    exact congrArg Subtype.val (CyclicPresentation.ker_component C cyclic hC q i)
  have haux : AuxiliaryPresentation.ObstructionVanishes ε :=
    OrderedCyclic.auxiliaryObstructionVanishes_of_diagonal ε hdiag
  exact obstructionVanishes_of_auxiliary_freePresentation ε
    (CyclicPresentation.map_surjective C cyclic hC) haux

end

end LieRings.PBW.Higgins
