import Mathlib.Algebra.Lie.OfAssociative
import Mathlib.Algebra.Module.Projective
import Mathlib.Algebra.Module.TransferInstance
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basic
import Mathlib.LinearAlgebra.Isomorphisms
import Mathlib.RingTheory.TwoSidedIdeal.Operations
import Mathlib.Tactic.NoncommRing

/-!
# The Higgins obstruction for integral PBW

This file begins the proof of the unconditional integral PBW theorem following P. J. Higgins,
*Baer Invariants and the Birkhoff--Witt Theorem* (1969).

For an Abelian group `M`, Higgins associates an obstruction `B(M)` depending only on the
underlying `ℤ`-module.  Its vanishing implies PBW, and hence injectivity of the canonical map
`L → U(L)`, for every Lie-ring structure on `M`.  The decisive integral facts are that the
obstruction vanishes on direct sums of cyclic groups and commutes with directed limits.

We use the canonical free presentation

`Q(M) → (M →₀ ℤ) → M`,

so all constructions below are definitionally functorial in the chosen presentation.  In the
tensor algebra of the free module, `K` is the commutator ideal, `Q̃` is the two-sided ideal
generated by the presentation relations, and `Z` is the two-sided ideal generated by their
commutators with arbitrary tensors.  The Baer numerator is `K ∩ Q̃` and the obstruction is
`(K ∩ Q̃) / Z`.
-/

namespace LieRings.PBW.Higgins

universe u

noncomputable section

variable (M : Type u) [AddCommGroup M]

/-- The canonical free `ℤ`-module on the underlying set of `M`. -/
abbrev FreePresentation := M →₀ ℤ

/-- Evaluation of the canonical free presentation. -/
noncomputable def presentationMap : FreePresentation M →ₗ[ℤ] M :=
  Finsupp.linearCombination ℤ id

@[simp]
theorem presentationMap_single (x : M) :
    presentationMap M (Finsupp.single x 1) = x := by
  simp [presentationMap]

/-- The canonical presentation map is onto. -/
theorem presentationMap_surjective : Function.Surjective (presentationMap M) := by
  intro x
  exact ⟨Finsupp.single x 1, presentationMap_single M x⟩

/-- Relations in the canonical free presentation of `M`. -/
abbrev PresentationRelations := LinearMap.ker (presentationMap M)

/-- The tensor algebra on the canonical free presentation. -/
abbrev PresentationTensor := TensorAlgebra ℤ (FreePresentation M)

/-- The tensor-algebra map induced by evaluation of the free presentation. -/
def tensorPresentationMap : PresentationTensor M →ₐ[ℤ] TensorAlgebra ℤ M :=
  TensorAlgebra.lift ℤ ((TensorAlgebra.ι ℤ).comp (presentationMap M))

@[simp]
theorem tensorPresentationMap_ι (p : FreePresentation M) :
    tensorPresentationMap M (TensorAlgebra.ι ℤ p) =
      TensorAlgebra.ι ℤ (presentationMap M p) := by
  simp [tensorPresentationMap]

/-- Higgins's `K(P)`: the commutator ideal of the tensor algebra on the free presentation. -/
def commutatorIdeal : Ideal (PresentationTensor M) :=
  RingHom.ker (SymmetricAlgebra.algHom ℤ (FreePresentation M)).toRingHom

instance commutatorIdeal_isTwoSided : (commutatorIdeal M).IsTwoSided :=
  show (RingHom.ker
    (SymmetricAlgebra.algHom ℤ (FreePresentation M)).toRingHom).IsTwoSided from inferInstance

/-- Higgins's `Q̃`: the two-sided tensor-algebra ideal generated by the presentation relations. -/
def relationIdeal : Ideal (PresentationTensor M) :=
  (TwoSidedIdeal.span
    (Set.range fun q : PresentationRelations M ↦
      TensorAlgebra.ι ℤ (q : FreePresentation M))).asIdeal

instance relationIdeal_isTwoSided : (relationIdeal M).IsTwoSided :=
  show ((TwoSidedIdeal.span
    (Set.range fun q : PresentationRelations M ↦
      TensorAlgebra.ι ℤ (q : FreePresentation M))).asIdeal).IsTwoSided from inferInstance

/-- A presentation relation, inserted in tensor degree one, belongs to `Q̃`. -/
theorem ι_relation_mem_relationIdeal (q : PresentationRelations M) :
    TensorAlgebra.ι ℤ (q : FreePresentation M) ∈ relationIdeal M := by
  exact TwoSidedIdeal.subset_span ⟨q, rfl⟩

/-- The relation ideal is killed by the tensor-algebra presentation map. -/
theorem relationIdeal_le_ker_tensorPresentationMap :
    relationIdeal M ≤ RingHom.ker (tensorPresentationMap M).toRingHom := by
  intro u hu
  change u ∈ TwoSidedIdeal.span
    (Set.range fun q : PresentationRelations M ↦
      TensorAlgebra.ι ℤ (q : FreePresentation M)) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨q, rfl⟩ := hu
      rw [RingHom.mem_ker]
      change tensorPresentationMap M (TensorAlgebra.ι ℤ (q : FreePresentation M)) = 0
      rw [tensorPresentationMap_ι]
      have hq : presentationMap M (q : FreePresentation M) = 0 := q.property
      rw [hq, map_zero]
  | zero => simp
  | add x y _ _ hx hy =>
      simpa using congrArg₂ (· + ·) hx hy
  | neg x _ hx =>
      simpa using congrArg Neg.neg hx
  | left_absorb a x _ hx =>
      rw [RingHom.mem_ker] at hx ⊢
      rw [map_mul, hx, mul_zero]
  | right_absorb a x _ hx =>
      rw [RingHom.mem_ker] at hx ⊢
      rw [map_mul, hx, zero_mul]

/-- The tensor algebra of the presentation, modulo its relation ideal. -/
abbrev PresentationTensorQuotient := PresentationTensor M ⧸ relationIdeal M

/-- A presentation generator followed by the quotient map on tensor algebras. -/
def presentationToTensorQuotient :
    FreePresentation M →ₗ[ℤ] PresentationTensorQuotient M :=
  (Ideal.Quotient.mkₐ ℤ (relationIdeal M)).toLinearMap.comp (TensorAlgebra.ι ℤ)

@[simp]
theorem presentationToTensorQuotient_apply (p : FreePresentation M) :
    presentationToTensorQuotient M p =
      Ideal.Quotient.mk (relationIdeal M) (TensorAlgebra.ι ℤ p) :=
  rfl

/-- The degree-one map `M → T(P)/Q̃` obtained by descending the free presentation. -/
def quotientPresentationGenerator :
    M →ₗ[ℤ] PresentationTensorQuotient M :=
  ((PresentationRelations M).liftQ (presentationToTensorQuotient M) (by
      intro p hp
      rw [LinearMap.mem_ker]
      exact Ideal.Quotient.eq_zero_iff_mem.mpr
        (ι_relation_mem_relationIdeal M ⟨p, hp⟩))).comp
    ((presentationMap M).quotKerEquivOfSurjective
      (presentationMap_surjective M)).symm.toLinearMap

@[simp]
theorem quotientPresentationGenerator_presentationMap (p : FreePresentation M) :
    quotientPresentationGenerator M (presentationMap M p) =
      Ideal.Quotient.mk (relationIdeal M) (TensorAlgebra.ι ℤ p) := by
  simp [quotientPresentationGenerator, presentationToTensorQuotient]
  rfl

/-- The inverse candidate to the tensor-presentation quotient map. -/
def fromTensorPresentation :
    TensorAlgebra ℤ M →ₐ[ℤ] PresentationTensorQuotient M :=
  TensorAlgebra.lift ℤ (quotientPresentationGenerator M)

@[simp]
theorem fromTensorPresentation_ι (x : M) :
    fromTensorPresentation M (TensorAlgebra.ι ℤ x) =
      quotientPresentationGenerator M x := by
  exact TensorAlgebra.lift_ι_apply (quotientPresentationGenerator M) x

/-- Evaluation descends through the relation ideal. -/
def toTensorPresentation :
    PresentationTensorQuotient M →ₐ[ℤ] TensorAlgebra ℤ M :=
  Ideal.Quotient.liftₐ (relationIdeal M) (tensorPresentationMap M)
    (fun _ hu ↦ RingHom.mem_ker.mp (relationIdeal_le_ker_tensorPresentationMap M hu))

@[simp]
theorem toTensorPresentation_mk (u : PresentationTensor M) :
    toTensorPresentation M (Ideal.Quotient.mk (relationIdeal M) u) =
      tensorPresentationMap M u := by
  rfl

@[simp]
theorem toTensorPresentation_quotientPresentationGenerator (x : M) :
    toTensorPresentation M (quotientPresentationGenerator M x) =
      TensorAlgebra.ι ℤ x := by
  obtain ⟨p, rfl⟩ := presentationMap_surjective M x
  rw [quotientPresentationGenerator_presentationMap, toTensorPresentation_mk,
    tensorPresentationMap_ι]

/-- Lifting back after evaluating a tensor word gives its class modulo the relation ideal. -/
theorem fromTensorPresentation_tensorPresentationMap (u : PresentationTensor M) :
    fromTensorPresentation M (tensorPresentationMap M u) =
      Ideal.Quotient.mk (relationIdeal M) u := by
  induction u using TensorAlgebra.induction with
  | algebraMap r => simp
  | ι p =>
      rw [tensorPresentationMap_ι, fromTensorPresentation_ι,
        quotientPresentationGenerator_presentationMap]
  | mul x y hx hy => simpa using congrArg₂ (· * ·) hx hy
  | add x y hx hy => simpa using congrArg₂ (· + ·) hx hy

/-- The two tensor-presentation maps are inverse in the direction starting at `T(M)`. -/
theorem toTensorPresentation_fromTensorPresentation (u : TensorAlgebra ℤ M) :
    toTensorPresentation M (fromTensorPresentation M u) = u := by
  let f := (toTensorPresentation M).comp (fromTensorPresentation M)
  have hf : f = AlgHom.id ℤ (TensorAlgebra ℤ M) := by
    apply TensorAlgebra.hom_ext
    ext x
    change toTensorPresentation M
      (fromTensorPresentation M (TensorAlgebra.ι ℤ x)) = TensorAlgebra.ι ℤ x
    rw [fromTensorPresentation_ι,
      toTensorPresentation_quotientPresentationGenerator]
  exact AlgHom.congr_fun hf u

/-- The two tensor-presentation maps are inverse in the direction starting at `T(P)/Q̃`. -/
theorem fromTensorPresentation_toTensorPresentation (u : PresentationTensorQuotient M) :
    fromTensorPresentation M (toTensorPresentation M u) = u := by
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mkₐ_surjective ℤ (relationIdeal M) u
  change fromTensorPresentation M
    (toTensorPresentation M (Ideal.Quotient.mk (relationIdeal M) p)) =
      Ideal.Quotient.mk (relationIdeal M) p
  rw [toTensorPresentation_mk, fromTensorPresentation_tensorPresentationMap]

/-- The exact tensor-presentation comparison `T(P)/Q̃ ≃ T(M)`. -/
noncomputable def tensorPresentationEquiv :
    PresentationTensorQuotient M ≃ₐ[ℤ] TensorAlgebra ℤ M :=
  AlgEquiv.ofBijective (toTensorPresentation M)
    ⟨Function.LeftInverse.injective (fromTensorPresentation_toTensorPresentation M),
      Function.RightInverse.surjective (toTensorPresentation_fromTensorPresentation M)⟩

@[simp]
theorem tensorPresentationEquiv_apply (u : PresentationTensorQuotient M) :
    tensorPresentationEquiv M u = toTensorPresentation M u :=
  rfl

/-- Exactness of the tensor-presentation row: `Q̃` is precisely the kernel of evaluation. -/
theorem relationIdeal_eq_ker_tensorPresentationMap :
    relationIdeal M = RingHom.ker (tensorPresentationMap M).toRingHom := by
  apply le_antisymm (relationIdeal_le_ker_tensorPresentationMap M)
  intro u hu
  rw [RingHom.mem_ker] at hu
  change tensorPresentationMap M u = 0 at hu
  apply Ideal.Quotient.eq_zero_iff_mem.mp
  rw [← fromTensorPresentation_tensorPresentationMap M u, hu, map_zero]

/-- The commutator ideal `K(M)` in the tensor algebra of `M` itself. -/
def tensorCommutatorIdeal : Ideal (TensorAlgebra ℤ M) :=
  RingHom.ker (SymmetricAlgebra.algHom ℤ M).toRingHom

instance tensorCommutatorIdeal_isTwoSided : (tensorCommutatorIdeal M).IsTwoSided :=
  show (RingHom.ker (SymmetricAlgebra.algHom ℤ M).toRingHom).IsTwoSided from inferInstance

/-- The two-sided ideal generated by the elementary degree-one commutators
`[ι(x), ι(y)]` in the tensor algebra. -/
def elementaryCommutatorIdeal : Ideal (TensorAlgebra ℤ M) :=
  (TwoSidedIdeal.span
    (Set.range fun xy : M × M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)).asIdeal

instance elementaryCommutatorIdeal_isTwoSided :
    (elementaryCommutatorIdeal M).IsTwoSided :=
  show ((TwoSidedIdeal.span
    (Set.range fun xy : M × M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)).asIdeal).IsTwoSided from
    inferInstance

/-- An elementary degree-one commutator belongs to the ideal it generates. -/
theorem elementary_commutator_mem (x y : M) :
    ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ ∈ elementaryCommutatorIdeal M := by
  exact TwoSidedIdeal.subset_span ⟨(x, y), rfl⟩

private theorem elementaryCommutatorIdeal_le_tensorCommutatorIdeal :
    elementaryCommutatorIdeal M ≤ tensorCommutatorIdeal M := by
  intro u hu
  change u ∈ TwoSidedIdeal.span
    (Set.range fun xy : M × M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨⟨x, y⟩, rfl⟩ := hu
      rw [tensorCommutatorIdeal, RingHom.mem_ker]
      simp [LieRing.of_associative_ring_bracket, mul_comm]
  | zero => exact (tensorCommutatorIdeal M).zero_mem
  | add x y _ _ hx hy => exact (tensorCommutatorIdeal M).add_mem hx hy
  | neg x _ hx => exact (tensorCommutatorIdeal M).neg_mem hx
  | left_absorb a x _ hx => exact (tensorCommutatorIdeal M).mul_mem_left a hx
  | right_absorb a x _ hx => exact (tensorCommutatorIdeal M).mul_mem_right a hx

/-- The tensor algebra modulo its elementary degree-one commutators. -/
abbrev ElementaryCommutatorQuotient :=
  TensorAlgebra ℤ M ⧸ elementaryCommutatorIdeal M

/-- The symmetric algebra maps back to the quotient of the tensor algebra by the elementary
commutators.  This is the inverse map hidden in the usual presentation of the symmetric algebra
as a relation quotient. -/
def symmetricToElementaryCommutatorQuotient :
    SymmetricAlgebra ℤ M →ₐ[ℤ] ElementaryCommutatorQuotient M :=
  RingQuot.liftAlgHom ℤ
    ⟨Ideal.Quotient.mkₐ ℤ (elementaryCommutatorIdeal M), by
      intro a b hab
      induction hab with
      | mul_comm x y =>
          apply Ideal.Quotient.eq.mpr
          simpa [LieRing.of_associative_ring_bracket] using
            elementary_commutator_mem M x y⟩

@[simp]
theorem symmetricToElementaryCommutatorQuotient_algHom
    (u : TensorAlgebra ℤ M) :
    symmetricToElementaryCommutatorQuotient M
        (SymmetricAlgebra.algHom ℤ M u) =
      Ideal.Quotient.mk (elementaryCommutatorIdeal M) u := by
  exact RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _

/-- The quotient by elementary commutators maps to the symmetric algebra. -/
def elementaryCommutatorQuotientToSymmetric :
    ElementaryCommutatorQuotient M →ₐ[ℤ] SymmetricAlgebra ℤ M :=
  Ideal.Quotient.liftₐ (elementaryCommutatorIdeal M)
    (SymmetricAlgebra.algHom ℤ M)
    (fun _ hu ↦ RingHom.mem_ker.mp
      (elementaryCommutatorIdeal_le_tensorCommutatorIdeal M hu))

@[simp]
theorem elementaryCommutatorQuotientToSymmetric_mk
    (u : TensorAlgebra ℤ M) :
    elementaryCommutatorQuotientToSymmetric M
        (Ideal.Quotient.mk (elementaryCommutatorIdeal M) u) =
      SymmetricAlgebra.algHom ℤ M u := by
  rfl

/-- The two quotient comparison maps are inverse in the direction starting at the elementary
commutator quotient. -/
theorem symmetricToElementaryCommutatorQuotient_leftInverse
    (u : ElementaryCommutatorQuotient M) :
    symmetricToElementaryCommutatorQuotient M
      (elementaryCommutatorQuotientToSymmetric M u) = u := by
  obtain ⟨t, rfl⟩ := Ideal.Quotient.mkₐ_surjective ℤ (elementaryCommutatorIdeal M) u
  change symmetricToElementaryCommutatorQuotient M
      (elementaryCommutatorQuotientToSymmetric M
        (Ideal.Quotient.mk (elementaryCommutatorIdeal M) t)) =
    Ideal.Quotient.mk (elementaryCommutatorIdeal M) t
  rw [elementaryCommutatorQuotientToSymmetric_mk,
    symmetricToElementaryCommutatorQuotient_algHom]

/-- The two quotient comparison maps are inverse in the direction starting at the symmetric
algebra. -/
theorem symmetricToElementaryCommutatorQuotient_rightInverse
    (s : SymmetricAlgebra ℤ M) :
    elementaryCommutatorQuotientToSymmetric M
        (symmetricToElementaryCommutatorQuotient M s) = s := by
  obtain ⟨t, rfl⟩ := SymmetricAlgebra.algHom_surjective ℤ M s
  rw [symmetricToElementaryCommutatorQuotient_algHom,
    elementaryCommutatorQuotientToSymmetric_mk]

/-- The symmetric algebra is exactly the quotient of the tensor algebra by its elementary
degree-one commutators. -/
noncomputable def elementaryCommutatorQuotientEquivSymmetric :
    ElementaryCommutatorQuotient M ≃ₐ[ℤ] SymmetricAlgebra ℤ M :=
  AlgEquiv.ofBijective (elementaryCommutatorQuotientToSymmetric M)
    ⟨Function.LeftInverse.injective
        (symmetricToElementaryCommutatorQuotient_leftInverse M),
      Function.RightInverse.surjective
        (symmetricToElementaryCommutatorQuotient_rightInverse M)⟩

/-- The kernel of tensor abelianization is generated, as a two-sided ideal, by the elementary
degree-one commutators.  This is the generation statement used in Higgins's comparison of free
presentations. -/
theorem elementaryCommutatorIdeal_eq_tensorCommutatorIdeal :
    elementaryCommutatorIdeal M = tensorCommutatorIdeal M := by
  apply le_antisymm (elementaryCommutatorIdeal_le_tensorCommutatorIdeal M)
  intro u hu
  rw [tensorCommutatorIdeal, RingHom.mem_ker] at hu
  change SymmetricAlgebra.algHom ℤ M u = 0 at hu
  apply Ideal.Quotient.eq_zero_iff_mem.mp
  rw [← symmetricToElementaryCommutatorQuotient_algHom M u, hu, map_zero]

/-- The symmetric-algebra map induced by evaluation of the free presentation. -/
def symmetricPresentationMap :
    SymmetricAlgebra ℤ (FreePresentation M) →ₐ[ℤ] SymmetricAlgebra ℤ M :=
  SymmetricAlgebra.lift ((SymmetricAlgebra.ι ℤ M).comp (presentationMap M))

@[simp]
theorem symmetricPresentationMap_ι (p : FreePresentation M) :
    symmetricPresentationMap M (SymmetricAlgebra.ι ℤ _ p) =
      SymmetricAlgebra.ι ℤ M (presentationMap M p) := by
  simp [symmetricPresentationMap]

/-- The ideal of `S(P)` generated by the presentation relations. -/
def symmetricRelationIdeal : Ideal (SymmetricAlgebra ℤ (FreePresentation M)) :=
  Ideal.span (Set.range fun q : PresentationRelations M ↦
    SymmetricAlgebra.ι ℤ (FreePresentation M) (q : FreePresentation M))

/-- The symmetric presentation map kills its relation ideal. -/
theorem symmetricRelationIdeal_le_ker :
    symmetricRelationIdeal M ≤ RingHom.ker (symmetricPresentationMap M).toRingHom := by
  rw [symmetricRelationIdeal, Ideal.span_le]
  rintro _ ⟨q, rfl⟩
  change symmetricPresentationMap M
    (SymmetricAlgebra.ι ℤ (FreePresentation M) (q : FreePresentation M)) = 0
  rw [symmetricPresentationMap_ι]
  have hq : presentationMap M (q : FreePresentation M) = 0 := q.property
  rw [hq, map_zero]

/-- The quotient of the symmetric algebra of `P` by the presentation relations. -/
abbrev PresentationSymmetricQuotient :=
  SymmetricAlgebra ℤ (FreePresentation M) ⧸ symmetricRelationIdeal M

def presentationToSymmetricQuotient :
    FreePresentation M →ₗ[ℤ] PresentationSymmetricQuotient M :=
  (Ideal.Quotient.mkₐ ℤ (symmetricRelationIdeal M)).toLinearMap.comp
    (SymmetricAlgebra.ι ℤ (FreePresentation M))

def quotientSymmetricGenerator :
    M →ₗ[ℤ] PresentationSymmetricQuotient M :=
  ((PresentationRelations M).liftQ (presentationToSymmetricQuotient M) (by
      intro p hp
      rw [LinearMap.mem_ker]
      exact Ideal.Quotient.eq_zero_iff_mem.mpr
        (Ideal.subset_span ⟨⟨p, hp⟩, rfl⟩))).comp
    ((presentationMap M).quotKerEquivOfSurjective
      (presentationMap_surjective M)).symm.toLinearMap

@[simp]
theorem quotientSymmetricGenerator_presentationMap (p : FreePresentation M) :
    quotientSymmetricGenerator M (presentationMap M p) =
      Ideal.Quotient.mk (symmetricRelationIdeal M)
        (SymmetricAlgebra.ι ℤ (FreePresentation M) p) := by
  simp [quotientSymmetricGenerator, presentationToSymmetricQuotient]
  rfl

def fromSymmetricPresentation :
    SymmetricAlgebra ℤ M →ₐ[ℤ] PresentationSymmetricQuotient M :=
  SymmetricAlgebra.lift (quotientSymmetricGenerator M)

def toSymmetricPresentation :
    PresentationSymmetricQuotient M →ₐ[ℤ] SymmetricAlgebra ℤ M :=
  Ideal.Quotient.liftₐ (symmetricRelationIdeal M) (symmetricPresentationMap M)
    (fun _ hu ↦ RingHom.mem_ker.mp (symmetricRelationIdeal_le_ker M hu))

@[simp]
theorem toSymmetricPresentation_mk (s : SymmetricAlgebra ℤ (FreePresentation M)) :
    toSymmetricPresentation M (Ideal.Quotient.mk (symmetricRelationIdeal M) s) =
      symmetricPresentationMap M s := by
  rfl

@[simp]
theorem toSymmetricPresentation_quotientGenerator (x : M) :
    toSymmetricPresentation M (quotientSymmetricGenerator M x) =
      SymmetricAlgebra.ι ℤ M x := by
  obtain ⟨p, rfl⟩ := presentationMap_surjective M x
  rw [quotientSymmetricGenerator_presentationMap, toSymmetricPresentation_mk,
    symmetricPresentationMap_ι]

theorem fromSymmetricPresentation_symmetricPresentationMap
    (s : SymmetricAlgebra ℤ (FreePresentation M)) :
    fromSymmetricPresentation M (symmetricPresentationMap M s) =
      Ideal.Quotient.mk (symmetricRelationIdeal M) s := by
  let f := (fromSymmetricPresentation M).comp (symmetricPresentationMap M)
  let g := Ideal.Quotient.mkₐ ℤ (symmetricRelationIdeal M)
  have hfg : f = g := by
    apply SymmetricAlgebra.algHom_ext
    apply LinearMap.ext
    intro p
    dsimp [f, g]
    rw [symmetricPresentationMap_ι]
    rw [fromSymmetricPresentation, SymmetricAlgebra.lift_ι_apply]
    change quotientSymmetricGenerator M (presentationMap M p) = _
    rw [quotientSymmetricGenerator_presentationMap]
  exact AlgHom.congr_fun hfg s

theorem toSymmetricPresentation_fromSymmetricPresentation
    (s : SymmetricAlgebra ℤ M) :
    toSymmetricPresentation M (fromSymmetricPresentation M s) = s := by
  let f := (toSymmetricPresentation M).comp (fromSymmetricPresentation M)
  have hf : f = AlgHom.id ℤ (SymmetricAlgebra ℤ M) := by
    apply SymmetricAlgebra.algHom_ext
    apply LinearMap.ext
    intro x
    dsimp [f]
    change toSymmetricPresentation M
      (fromSymmetricPresentation M (SymmetricAlgebra.ι ℤ M x)) = _
    rw [fromSymmetricPresentation, SymmetricAlgebra.lift_ι_apply]
    exact toSymmetricPresentation_quotientGenerator M x
  exact AlgHom.congr_fun hf s

theorem fromSymmetricPresentation_toSymmetricPresentation
    (s : PresentationSymmetricQuotient M) :
    fromSymmetricPresentation M (toSymmetricPresentation M s) = s := by
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mkₐ_surjective ℤ (symmetricRelationIdeal M) s
  change fromSymmetricPresentation M
    (toSymmetricPresentation M (Ideal.Quotient.mk (symmetricRelationIdeal M) p)) =
      Ideal.Quotient.mk (symmetricRelationIdeal M) p
  rw [toSymmetricPresentation_mk,
    fromSymmetricPresentation_symmetricPresentationMap]

/-- Exactness of the symmetric-presentation row. -/
theorem symmetricRelationIdeal_eq_ker :
    symmetricRelationIdeal M = RingHom.ker (symmetricPresentationMap M).toRingHom := by
  apply le_antisymm (symmetricRelationIdeal_le_ker M)
  intro s hs
  rw [RingHom.mem_ker] at hs
  change symmetricPresentationMap M s = 0 at hs
  apply Ideal.Quotient.eq_zero_iff_mem.mp
  rw [← fromSymmetricPresentation_symmetricPresentationMap M s, hs, map_zero]

/-- Every symmetric presentation relation lifts to an element of the tensor relation ideal. -/
theorem symmetricRelationIdeal_has_tensorLift
    {s : SymmetricAlgebra ℤ (FreePresentation M)} (hs : s ∈ symmetricRelationIdeal M) :
    ∃ q : PresentationTensor M, q ∈ relationIdeal M ∧
      SymmetricAlgebra.algHom ℤ (FreePresentation M) q = s := by
  change s ∈ Submodule.span (SymmetricAlgebra ℤ (FreePresentation M))
    (Set.range fun q : PresentationRelations M ↦
      SymmetricAlgebra.ι ℤ (FreePresentation M) (q : FreePresentation M)) at hs
  induction hs using Submodule.span_induction with
  | mem s hs =>
      obtain ⟨q, rfl⟩ := hs
      refine ⟨TensorAlgebra.ι ℤ (q : FreePresentation M),
        ι_relation_mem_relationIdeal M q, ?_⟩
      rfl
  | zero => exact ⟨0, (relationIdeal M).zero_mem, map_zero _⟩
  | add x y _ _ hx hy =>
      obtain ⟨a, ha, rfl⟩ := hx
      obtain ⟨b, hb, rfl⟩ := hy
      exact ⟨a + b, (relationIdeal M).add_mem ha hb, by simp⟩
  | smul a x _ hx =>
      obtain ⟨t, rfl⟩ := SymmetricAlgebra.algHom_surjective ℤ (FreePresentation M) a
      obtain ⟨q, hq, rfl⟩ := hx
      refine ⟨t * q, (relationIdeal M).mul_mem_left t hq, ?_⟩
      simp

/-- Evaluation `T(P) → T(M)` is onto. -/
theorem tensorPresentationMap_surjective :
    Function.Surjective (tensorPresentationMap M) := by
  intro u
  let q := fromTensorPresentation M u
  obtain ⟨p, hp⟩ := Ideal.Quotient.mkₐ_surjective ℤ (relationIdeal M) q
  refine ⟨p, ?_⟩
  calc
    tensorPresentationMap M p =
        toTensorPresentation M (Ideal.Quotient.mk (relationIdeal M) p) := rfl
    _ = toTensorPresentation M q := congrArg (toTensorPresentation M) hp
    _ = u := toTensorPresentation_fromTensorPresentation M u

/-- Naturality of tensor-to-symmetric abelianization for the presentation map. -/
theorem tensor_symmetric_presentation_commutes (u : PresentationTensor M) :
    SymmetricAlgebra.algHom ℤ M (tensorPresentationMap M u) =
      symmetricPresentationMap M
        (SymmetricAlgebra.algHom ℤ (FreePresentation M) u) := by
  let f := (SymmetricAlgebra.algHom ℤ M).comp (tensorPresentationMap M)
  let g := (symmetricPresentationMap M).comp
    (SymmetricAlgebra.algHom ℤ (FreePresentation M))
  have hfg : f = g := by
    apply TensorAlgebra.hom_ext
    apply LinearMap.ext
    intro p
    dsimp [f, g]
    rw [tensorPresentationMap_ι]
    change SymmetricAlgebra.ι ℤ M (presentationMap M p) =
      symmetricPresentationMap M
        (SymmetricAlgebra.ι ℤ (FreePresentation M) p)
    rw [symmetricPresentationMap_ι]
  exact AlgHom.congr_fun hfg u

/-- Evaluation sends `K(P)` to `K(M)`. -/
def commutatorMap : commutatorIdeal M →ₗ[ℤ] tensorCommutatorIdeal M where
  toFun u := ⟨tensorPresentationMap M u, by
    rw [tensorCommutatorIdeal, RingHom.mem_ker]
    change SymmetricAlgebra.algHom ℤ M (tensorPresentationMap M u) = 0
    rw [tensor_symmetric_presentation_commutes]
    have hu : SymmetricAlgebra.algHom ℤ (FreePresentation M) u = 0 := by
      exact RingHom.mem_ker.mp u.property
    rw [hu, map_zero]⟩
  map_add' x y := by ext; simp
  map_smul' r x := by ext; simp

@[simp]
theorem commutatorMap_apply (u : commutatorIdeal M) :
    (commutatorMap M u : TensorAlgebra ℤ M) = tensorPresentationMap M u :=
  rfl

/-- The commutator comparison `K(P) → K(M)` is onto. -/
theorem commutatorMap_surjective : Function.Surjective (commutatorMap M) := by
  intro u
  obtain ⟨p, hp⟩ := tensorPresentationMap_surjective M (u : TensorAlgebra ℤ M)
  have htarget :
      SymmetricAlgebra.algHom ℤ M (tensorPresentationMap M p) = 0 := by
    rw [hp]
    exact RingHom.mem_ker.mp u.property
  have hsymmetric :
      symmetricPresentationMap M
        (SymmetricAlgebra.algHom ℤ (FreePresentation M) p) = 0 := by
    rw [← tensor_symmetric_presentation_commutes]
    exact htarget
  have hsrel :
      SymmetricAlgebra.algHom ℤ (FreePresentation M) p ∈ symmetricRelationIdeal M := by
    rw [symmetricRelationIdeal_eq_ker, RingHom.mem_ker]
    exact hsymmetric
  obtain ⟨q, hqrel, hq⟩ := symmetricRelationIdeal_has_tensorLift M hsrel
  have hqzero : tensorPresentationMap M q = 0 :=
    RingHom.mem_ker.mp (relationIdeal_le_ker_tensorPresentationMap M hqrel)
  have hcomm : p - q ∈ commutatorIdeal M := by
    rw [commutatorIdeal, RingHom.mem_ker]
    change SymmetricAlgebra.algHom ℤ (FreePresentation M) (p - q) = 0
    rw [map_sub, hq, sub_self]
  refine ⟨⟨p - q, hcomm⟩, ?_⟩
  apply Subtype.ext
  change tensorPresentationMap M (p - q) = (u : TensorAlgebra ℤ M)
  rw [map_sub, hqzero, sub_zero, hp]

/-- Higgins's `Z`: the two-sided ideal generated by commutators `[t,q]`, with
`q ∈ Q̃` in the full tensor ideal generated by the presentation relations.

Higgins originally defines `Z` using derived commutator words and proves that this is the same
ideal.  The full ideal `Q̃`, rather than merely its degree-one generating submodule, is essential:
it gives the containments `K(P) Q̃ + Q̃ K(P) ⊆ Z` used in the universal-Lie-structure argument.
-/
def relationCommutatorIdeal : Ideal (PresentationTensor M) :=
  (TwoSidedIdeal.span
    (Set.range fun tq : PresentationTensor M × relationIdeal M ↦
      ⁅tq.1, (tq.2 : PresentationTensor M)⁆)).asIdeal

instance relationCommutatorIdeal_isTwoSided :
    (relationCommutatorIdeal M).IsTwoSided :=
  show ((TwoSidedIdeal.span
    (Set.range fun tq : PresentationTensor M × relationIdeal M ↦
      ⁅tq.1, (tq.2 : PresentationTensor M)⁆)).asIdeal).IsTwoSided from
    inferInstance

/-- Every defining relation commutator belongs to `Z`. -/
theorem relation_commutator_mem (t : PresentationTensor M) (q : relationIdeal M) :
    ⁅t, (q : PresentationTensor M)⁆ ∈
      relationCommutatorIdeal M := by
  exact TwoSidedIdeal.subset_span ⟨(t, q), rfl⟩

private theorem relationCommutatorIdeal_le_commutatorIdeal :
    relationCommutatorIdeal M ≤ commutatorIdeal M := by
  intro u hu
  change u ∈ TwoSidedIdeal.span
    (Set.range fun tq : PresentationTensor M × relationIdeal M ↦
      ⁅tq.1, (tq.2 : PresentationTensor M)⁆) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨⟨t, q⟩, rfl⟩ := hu
      rw [commutatorIdeal, RingHom.mem_ker]
      simp [LieRing.of_associative_ring_bracket, mul_comm]
  | zero => exact (commutatorIdeal M).zero_mem
  | add x y _ _ hx hy => exact (commutatorIdeal M).add_mem hx hy
  | neg x _ hx => exact (commutatorIdeal M).neg_mem hx
  | left_absorb a x _ hx => exact (commutatorIdeal M).mul_mem_left a hx
  | right_absorb a x _ hx => exact (commutatorIdeal M).mul_mem_right a hx

private theorem relationCommutatorIdeal_le_relationIdeal :
    relationCommutatorIdeal M ≤ relationIdeal M := by
  intro u hu
  change u ∈ TwoSidedIdeal.span
    (Set.range fun tq : PresentationTensor M × relationIdeal M ↦
      ⁅tq.1, (tq.2 : PresentationTensor M)⁆) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨⟨t, q⟩, rfl⟩ := hu
      change ⁅t, (q : PresentationTensor M)⁆ ∈ relationIdeal M
      rw [LieRing.of_associative_ring_bracket]
      exact (relationIdeal M).sub_mem
        ((relationIdeal M).mul_mem_left t q.property)
        ((relationIdeal M).mul_mem_right t q.property)
  | zero => exact (relationIdeal M).zero_mem
  | add x y _ _ hx hy => exact (relationIdeal M).add_mem hx hy
  | neg x _ hx => exact (relationIdeal M).neg_mem hx
  | left_absorb a x _ hx => exact (relationIdeal M).mul_mem_left a hx
  | right_absorb a x _ hx => exact (relationIdeal M).mul_mem_right a hx

/-- The first product containment used by Higgins: `K(P) Q̃ ⊆ Z`.

The proof reduces `K(P)` to elementary commutators and uses
`[x,y]q = [x,yq] - y[x,q]`.
-/
theorem commutator_mul_relation_mem
    (k : commutatorIdeal M) (q : relationIdeal M) :
    (k : PresentationTensor M) * (q : PresentationTensor M) ∈
      relationCommutatorIdeal M := by
  let t : PresentationTensor M := k
  have ht : t ∈
      elementaryCommutatorIdeal (FreePresentation M) := by
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact k.property
  change t ∈ TwoSidedIdeal.span
    (Set.range fun xy : FreePresentation M × FreePresentation M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆) at ht
  have hspan {u : PresentationTensor M}
      (hu : u ∈ TwoSidedIdeal.span
        (Set.range fun xy : FreePresentation M × FreePresentation M ↦
          ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)) :
      ∀ q : relationIdeal M,
        u * (q : PresentationTensor M) ∈ relationCommutatorIdeal M := by
    induction hu using TwoSidedIdeal.span_induction with
    | mem u hu =>
      intro q
      obtain ⟨⟨x, y⟩, rfl⟩ := hu
      let yq : relationIdeal M :=
        ⟨TensorAlgebra.ι ℤ y * (q : PresentationTensor M),
          (relationIdeal M).mul_mem_left (TensorAlgebra.ι ℤ y) q.property⟩
      have hxyq := relation_commutator_mem M (TensorAlgebra.ι ℤ x) yq
      have hxq := (relationCommutatorIdeal M).mul_mem_left
        (TensorAlgebra.ι ℤ y) (relation_commutator_mem M (TensorAlgebra.ι ℤ x) q)
      have h := (relationCommutatorIdeal M).sub_mem hxyq hxq
      have hid :
          ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * (q : PresentationTensor M) =
            ⁅TensorAlgebra.ι ℤ x, (yq : PresentationTensor M)⁆ -
              TensorAlgebra.ι ℤ y *
                ⁅TensorAlgebra.ι ℤ x, (q : PresentationTensor M)⁆ := by
        simp only [yq, LieRing.of_associative_ring_bracket]
        noncomm_ring
      rw [hid]
      exact h
    | zero =>
      intro q
      simp
    | add x y _ _ hx hy =>
      intro q
      simpa [add_mul] using (relationCommutatorIdeal M).add_mem (hx q) (hy q)
    | neg x _ hx =>
      intro q
      simpa using (relationCommutatorIdeal M).neg_mem (hx q)
    | left_absorb a x _ hx =>
      intro q
      simpa [mul_assoc] using (relationCommutatorIdeal M).mul_mem_left a (hx q)
    | right_absorb b x _ hx =>
      intro q
      let bq : relationIdeal M :=
        ⟨b * (q : PresentationTensor M),
          (relationIdeal M).mul_mem_left b q.property⟩
      simpa [bq, mul_assoc] using hx bq
  exact hspan ht q

/-- The second product containment used by Higgins: `Q̃ K(P) ⊆ Z`.

The proof reduces `K(P)` to elementary commutators and uses
`q[x,y] = [qx,y] - [q,y]x`.
-/
theorem relation_mul_commutator_mem
    (q : relationIdeal M) (k : commutatorIdeal M) :
    (q : PresentationTensor M) * (k : PresentationTensor M) ∈
      relationCommutatorIdeal M := by
  let t : PresentationTensor M := k
  have ht : t ∈
      elementaryCommutatorIdeal (FreePresentation M) := by
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact k.property
  change t ∈ TwoSidedIdeal.span
    (Set.range fun xy : FreePresentation M × FreePresentation M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆) at ht
  have hspan {u : PresentationTensor M}
      (hu : u ∈ TwoSidedIdeal.span
        (Set.range fun xy : FreePresentation M × FreePresentation M ↦
          ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)) :
      ∀ q : relationIdeal M,
        (q : PresentationTensor M) * u ∈ relationCommutatorIdeal M := by
    induction hu using TwoSidedIdeal.span_induction with
    | mem u hu =>
      intro q
      obtain ⟨⟨x, y⟩, rfl⟩ := hu
      let qx : relationIdeal M :=
        ⟨(q : PresentationTensor M) * TensorAlgebra.ι ℤ x,
          (relationIdeal M).mul_mem_right (TensorAlgebra.ι ℤ x) q.property⟩
      have hqxy := relation_commutator_mem M (TensorAlgebra.ι ℤ y) qx
      have hqy := (relationCommutatorIdeal M).mul_mem_right
        (TensorAlgebra.ι ℤ x) (relation_commutator_mem M (TensorAlgebra.ι ℤ y) q)
      have h := (relationCommutatorIdeal M).add_mem
        ((relationCommutatorIdeal M).neg_mem hqxy) hqy
      have hid :
          (q : PresentationTensor M) *
              ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ =
            -⁅TensorAlgebra.ι ℤ y, (qx : PresentationTensor M)⁆ +
              ⁅TensorAlgebra.ι ℤ y, (q : PresentationTensor M)⁆ *
                TensorAlgebra.ι ℤ x := by
        simp only [qx, LieRing.of_associative_ring_bracket]
        noncomm_ring
      rw [hid]
      exact h
    | zero =>
      intro q
      simp
    | add x y _ _ hx hy =>
      intro q
      simpa [mul_add] using (relationCommutatorIdeal M).add_mem (hx q) (hy q)
    | neg x _ hx =>
      intro q
      simpa using (relationCommutatorIdeal M).neg_mem (hx q)
    | left_absorb a x _ hx =>
      intro q
      let qa : relationIdeal M :=
        ⟨(q : PresentationTensor M) * a,
          (relationIdeal M).mul_mem_right a q.property⟩
      simpa [qa, mul_assoc] using hx qa
    | right_absorb b x _ hx =>
      intro q
      simpa [mul_assoc] using (relationCommutatorIdeal M).mul_mem_right b (hx q)
  exact hspan ht q

section Projective

variable [Module.Projective ℤ M]

/-- A chosen linear section of the canonical free presentation of a projective module. -/
noncomputable def presentationSection : M →ₗ[ℤ] FreePresentation M :=
  Classical.choose (Module.projective_lifting_property
    (presentationMap M) LinearMap.id (presentationMap_surjective M))

theorem presentationMap_comp_presentationSection :
    (presentationMap M).comp (presentationSection M) = LinearMap.id :=
  Classical.choose_spec (Module.projective_lifting_property
    (presentationMap M) LinearMap.id (presentationMap_surjective M))

@[simp]
theorem presentationMap_presentationSection (x : M) :
    presentationMap M (presentationSection M x) = x := by
  exact LinearMap.congr_fun (presentationMap_comp_presentationSection M) x

/-- The idempotent-like endomorphism of the free presentation obtained from a section. -/
noncomputable def presentationRetraction :
    FreePresentation M →ₗ[ℤ] FreePresentation M :=
  (presentationSection M).comp (presentationMap M)

@[simp]
theorem presentationMap_presentationRetraction (p : FreePresentation M) :
    presentationMap M (presentationRetraction M p) = presentationMap M p := by
  simp [presentationRetraction]

/-- The algebra endomorphism of `T(P)` induced by the presentation retraction. -/
noncomputable def tensorRetraction : PresentationTensor M →ₐ[ℤ] PresentationTensor M :=
  TensorAlgebra.lift ℤ ((TensorAlgebra.ι ℤ).comp (presentationRetraction M))

@[simp]
theorem tensorRetraction_ι (p : FreePresentation M) :
    tensorRetraction M (TensorAlgebra.ι ℤ p) =
      TensorAlgebra.ι ℤ (presentationRetraction M p) := by
  simp [tensorRetraction]

/-- Evaluation is unchanged by the tensor retraction. -/
theorem tensorPresentationMap_tensorRetraction (u : PresentationTensor M) :
    tensorPresentationMap M (tensorRetraction M u) = tensorPresentationMap M u := by
  let f := (tensorPresentationMap M).comp (tensorRetraction M)
  have hf : f = tensorPresentationMap M := by
    apply TensorAlgebra.hom_ext
    apply LinearMap.ext
    intro p
    dsimp [f]
    rw [tensorRetraction_ι, tensorPresentationMap_ι, tensorPresentationMap_ι,
      presentationMap_presentationRetraction]
  exact AlgHom.congr_fun hf u

/-- Every tensor differs from its retraction by a presentation relation. -/
theorem sub_tensorRetraction_mem_relationIdeal (u : PresentationTensor M) :
    u - tensorRetraction M u ∈ relationIdeal M := by
  rw [relationIdeal_eq_ker_tensorPresentationMap, RingHom.mem_ker]
  change tensorPresentationMap M (u - tensorRetraction M u) = 0
  rw [map_sub, tensorPresentationMap_tensorRetraction, sub_self]

/-- The tensor retraction kills the full presentation relation ideal. -/
theorem tensorRetraction_eq_zero_of_mem_relationIdeal
    {u : PresentationTensor M} (hu : u ∈ relationIdeal M) :
    tensorRetraction M u = 0 := by
  change u ∈ TwoSidedIdeal.span
    (Set.range fun q : PresentationRelations M ↦
      TensorAlgebra.ι ℤ (q : FreePresentation M)) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨q, rfl⟩ := hu
      rw [tensorRetraction_ι]
      have hq : presentationMap M (q : FreePresentation M) = 0 := q.property
      simp [presentationRetraction, hq]
  | zero => exact map_zero _
  | add x y _ _ hx hy => simpa using congrArg₂ (· + ·) hx hy
  | neg x _ hx => simpa using congrArg Neg.neg hx
  | left_absorb a x _ hx => rw [map_mul, hx, mul_zero]
  | right_absorb a x _ hx => rw [map_mul, hx, zero_mul]

/-- On `K(P)`, the tensor retraction is congruent to the identity modulo Higgins's `Z`. -/
theorem commutator_sub_tensorRetraction_mem_relationCommutatorIdeal
    (k : commutatorIdeal M) :
    (k : PresentationTensor M) - tensorRetraction M k ∈
      relationCommutatorIdeal M := by
  let t : PresentationTensor M := k
  have ht : t ∈ elementaryCommutatorIdeal (FreePresentation M) := by
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact k.property
  change t ∈ TwoSidedIdeal.span
    (Set.range fun xy : FreePresentation M × FreePresentation M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆) at ht
  have hspan {u : PresentationTensor M}
      (hu : u ∈ TwoSidedIdeal.span
        (Set.range fun xy : FreePresentation M × FreePresentation M ↦
          ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)) :
      u - tensorRetraction M u ∈ relationCommutatorIdeal M := by
    induction hu using TwoSidedIdeal.span_induction with
    | mem u hu =>
      obtain ⟨⟨x, y⟩, rfl⟩ := hu
      let qx : PresentationRelations M :=
        ⟨x - presentationRetraction M x, by
          rw [LinearMap.mem_ker]
          rw [map_sub, presentationMap_presentationRetraction, sub_self]⟩
      let qy : PresentationRelations M :=
        ⟨y - presentationRetraction M y, by
          rw [LinearMap.mem_ker]
          rw [map_sub, presentationMap_presentationRetraction, sub_self]⟩
      let iqx : relationIdeal M :=
        ⟨TensorAlgebra.ι ℤ (qx : FreePresentation M),
          ι_relation_mem_relationIdeal M qx⟩
      let iqy : relationIdeal M :=
        ⟨TensorAlgebra.ι ℤ (qy : FreePresentation M),
          ι_relation_mem_relationIdeal M qy⟩
      have hx := (relationCommutatorIdeal M).neg_mem
        (relation_commutator_mem M (TensorAlgebra.ι ℤ y) iqx)
      have hy := relation_commutator_mem M
        (TensorAlgebra.ι ℤ (presentationRetraction M x)) iqy
      have h := (relationCommutatorIdeal M).add_mem hx hy
      have hid :
          ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ -
              tensorRetraction M ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ =
            -⁅TensorAlgebra.ι ℤ y, (iqx : PresentationTensor M)⁆ +
              ⁅TensorAlgebra.ι ℤ (presentationRetraction M x),
                (iqy : PresentationTensor M)⁆ := by
        simp only [map_sub, map_mul, tensorRetraction_ι,
          LieRing.of_associative_ring_bracket, iqx, iqy, qx, qy, map_sub]
        noncomm_ring
      rw [hid]
      exact h
    | zero => simp
    | add x y _ _ hx hy =>
      have h := (relationCommutatorIdeal M).add_mem hx hy
      have hid :
          x + y - tensorRetraction M (x + y) =
            (x - tensorRetraction M x) + (y - tensorRetraction M y) := by
        rw [map_add]
        abel
      rw [hid]
      exact h
    | neg x _ hx =>
      have h := (relationCommutatorIdeal M).neg_mem hx
      have hid :
          -x - tensorRetraction M (-x) = -(x - tensorRetraction M x) := by
        rw [map_neg]
        abel
      rw [hid]
      exact h
    | left_absorb a x hxmem hx =>
      let qa : relationIdeal M :=
        ⟨a - tensorRetraction M a, sub_tensorRetraction_mem_relationIdeal M a⟩
      let kx : commutatorIdeal M := ⟨x, by
        change x ∈ tensorCommutatorIdeal (FreePresentation M)
        rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
        exact hxmem⟩
      have hleft := relation_mul_commutator_mem M qa kx
      have hright := (relationCommutatorIdeal M).mul_mem_left
        (tensorRetraction M a) hx
      have h := (relationCommutatorIdeal M).add_mem hleft hright
      have hid :
          a * x - tensorRetraction M (a * x) =
            (qa : PresentationTensor M) * x +
              tensorRetraction M a * (x - tensorRetraction M x) := by
        simp only [qa, map_mul]
        noncomm_ring
      rw [hid]
      exact h
    | right_absorb b x hxmem hx =>
      let qb : relationIdeal M :=
        ⟨b - tensorRetraction M b, sub_tensorRetraction_mem_relationIdeal M b⟩
      have hdiffK : x - tensorRetraction M x ∈ commutatorIdeal M :=
        relationCommutatorIdeal_le_commutatorIdeal M hx
      let krx : commutatorIdeal M :=
        ⟨tensorRetraction M x, by
          have hxK : x ∈ commutatorIdeal M := by
            change x ∈ tensorCommutatorIdeal (FreePresentation M)
            rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
            exact hxmem
          have hsub := (commutatorIdeal M).sub_mem hxK hdiffK
          convert hsub using 1; abel⟩
      have hleft := (relationCommutatorIdeal M).mul_mem_right b hx
      have hright := commutator_mul_relation_mem M krx qb
      have h := (relationCommutatorIdeal M).add_mem hleft hright
      have hid :
          x * b - tensorRetraction M (x * b) =
            (x - tensorRetraction M x) * b +
              tensorRetraction M x * (qb : PresentationTensor M) := by
        simp only [qb, map_mul]
        noncomm_ring
      rw [hid]
      exact h
  exact hspan ht

end Projective

/-- Higgins's numerator `K(P) ∩ Q̃`. -/
def baerNumerator : Ideal (PresentationTensor M) :=
  commutatorIdeal M ⊓ relationIdeal M

instance baerNumerator_isTwoSided : (baerNumerator M).IsTwoSided := by
  constructor
  intro a b hb
  exact ⟨(commutatorIdeal M).mul_mem_right b hb.1,
    (relationIdeal M).mul_mem_right b hb.2⟩

/-- The defining ideal `Z` lies in the Baer numerator `K(P) ∩ Q̃`. -/
theorem relationCommutatorIdeal_le_baerNumerator :
    relationCommutatorIdeal M ≤ baerNumerator M := by
  exact le_inf (relationCommutatorIdeal_le_commutatorIdeal M)
    (relationCommutatorIdeal_le_relationIdeal M)

/-- The submodule of the Baer numerator corresponding to `Z`. -/
def baerRelations : Submodule ℤ (baerNumerator M) :=
  ((relationCommutatorIdeal M).restrictScalars ℤ).comap
    ((baerNumerator M).subtype.restrictScalars ℤ)

/-- Higgins's module-only obstruction `B(M) = (K(P) ∩ Q̃) / Z`. -/
abbrev BaerObstruction := baerNumerator M ⧸ baerRelations M

/-- Vanishing of the Higgins obstruction, stated as a proposition for downstream PBW theorems. -/
def ObstructionVanishes : Prop := Subsingleton (BaerObstruction M)

/-- The obstruction vanishes exactly when every element of `K(P) ∩ Q̃` already belongs to `Z`.

This is the form used in Higgins's direct-sum-of-cyclic calculation.
-/
theorem obstructionVanishes_iff :
    ObstructionVanishes M ↔ baerNumerator M ≤ relationCommutatorIdeal M := by
  rw [ObstructionVanishes, Submodule.Quotient.subsingleton_iff]
  constructor
  · intro h x hx
    have hmem : (⟨x, hx⟩ : baerNumerator M) ∈ baerRelations M := by
      rw [h]
      trivial
    exact hmem
  · intro h
    apply top_unique
    rintro ⟨x, hx⟩ _
    exact h hx

/-- Higgins's projective case: the Baer obstruction vanishes for every projective integral
module.  In particular this applies to every free Abelian group.

The proof uses a splitting of the canonical free presentation.  Its induced tensor retraction
kills `Q̃`, while it is congruent to the identity on `K(P)` modulo `Z`.
-/
theorem obstructionVanishes_of_projective [Module.Projective ℤ M] :
    ObstructionVanishes M := by
  rw [obstructionVanishes_iff]
  intro u hu
  let k : commutatorIdeal M := ⟨u, hu.1⟩
  have hk := commutator_sub_tensorRetraction_mem_relationCommutatorIdeal M k
  have hzero : tensorRetraction M u = 0 :=
    tensorRetraction_eq_zero_of_mem_relationIdeal M hu.2
  change u - tensorRetraction M u ∈ relationCommutatorIdeal M at hk
  rw [hzero, sub_zero] at hk
  exact hk

/-- The free-module specialization of `obstructionVanishes_of_projective`. -/
theorem obstructionVanishes_of_free [Module.Free ℤ M] : ObstructionVanishes M :=
  obstructionVanishes_of_projective M

/-- The copy of `Z` inside `K(P)`, retained as a submodule over the full presentation tensor
algebra.  This scalar structure is what makes the quotient carry the left tensor action. -/
def commutatorRelationsTensor :
    Submodule (PresentationTensor M) (commutatorIdeal M) where
  carrier := {u | (u : PresentationTensor M) ∈ relationCommutatorIdeal M}
  zero_mem' := (relationCommutatorIdeal M).zero_mem
  add_mem' hx hy := (relationCommutatorIdeal M).add_mem hx hy
  smul_mem' a u hu := by
    change a * (u : PresentationTensor M) ∈ relationCommutatorIdeal M
    exact (relationCommutatorIdeal M).mul_mem_left a hu

/-- The copy of `Z` inside `K(P)`, viewed as an integral submodule. -/
def commutatorRelations : Submodule ℤ (commutatorIdeal M) :=
  (commutatorRelationsTensor M).restrictScalars ℤ

/-- Higgins's universal-Lie-structure candidate `C(M) = K(P)/Z`. -/
abbrev UniversalLieCarrier := commutatorIdeal M ⧸ commutatorRelations M

/-- The same carrier `C(M)=K(P)/Z`, formed as a quotient module over `T(P)`. -/
abbrev UniversalLieCarrierTensor :=
  commutatorIdeal M ⧸ commutatorRelationsTensor M

/-- Forgetting the `T(P)`-module structure on `C(M)` recovers its original integral-module
presentation. -/
noncomputable def universalLieCarrierRestrictScalarsEquiv :
    UniversalLieCarrier M ≃ₗ[ℤ] UniversalLieCarrierTensor M :=
  Submodule.Quotient.restrictScalarsEquiv ℤ (commutatorRelationsTensor M)

@[simp]
theorem universalLieCarrierRestrictScalarsEquiv_mk (u : commutatorIdeal M) :
    universalLieCarrierRestrictScalarsEquiv M (Submodule.Quotient.mk u) =
      Submodule.Quotient.mk u :=
  rfl

/-- The presentation relation ideal annihilates the left `T(P)`-action on `C(M)`. -/
theorem relationIdeal_annihilates_universalLieCarrierTensor :
    Module.IsTorsionBySet (PresentationTensor M) (UniversalLieCarrierTensor M)
      (relationIdeal M) := by
  rw [Module.isTorsionBySet_quotient_iff]
  intro k q hq
  change (q : PresentationTensor M) * (k : PresentationTensor M) ∈
    relationCommutatorIdeal M
  exact relation_mul_commutator_mem M ⟨q, hq⟩ k

/-- The left `T(P)`-action on `C(M)` descends through `T(P)/Q̃`. -/
@[implicit_reducible] noncomputable def universalLieCarrierTensorModuleOverPresentationQuotient :
    Module (PresentationTensorQuotient M) (UniversalLieCarrierTensor M) :=
  (relationIdeal_annihilates_universalLieCarrierTensor M).module

/-- Transporting along `T(P)/Q̃ ≃ T(M)` gives Higgins's canonical left `T(M)`-action on
`C(M)`. -/
@[implicit_reducible] noncomputable def universalLieCarrierTensorModuleOverTensor :
    Module (TensorAlgebra ℤ M) (UniversalLieCarrierTensor M) := by
  letI := universalLieCarrierTensorModuleOverPresentationQuotient M
  exact Module.compHom (UniversalLieCarrierTensor M)
    (tensorPresentationEquiv M).symm.toRingEquiv.toRingHom

/-- The commutator ideal, viewed as a right `T(P)`-module, equivalently as a left module over the
opposite ring. -/
def commutatorIdealOpposite :
    Submodule (PresentationTensor M)ᵐᵒᵖ (PresentationTensor M) where
  carrier := commutatorIdeal M
  zero_mem' := (commutatorIdeal M).zero_mem
  add_mem' hx hy := (commutatorIdeal M).add_mem hx hy
  smul_mem' a u hu := by
    change u * a.unop ∈ commutatorIdeal M
    exact (commutatorIdeal M).mul_mem_right a.unop hu

/-- The standard right multiplication action on `K(P)`. -/
@[implicit_reducible] noncomputable instance commutatorIdealModuleOpposite :
    Module (PresentationTensor M)ᵐᵒᵖ (commutatorIdeal M) :=
  inferInstanceAs (Module (PresentationTensor M)ᵐᵒᵖ (commutatorIdealOpposite M))

/-- The copy of `Z` inside the right `T(P)`-module `K(P)`. -/
def commutatorRelationsTensorOpposite :
    Submodule (PresentationTensor M)ᵐᵒᵖ (commutatorIdeal M) where
  carrier := {u | (u : PresentationTensor M) ∈ relationCommutatorIdeal M}
  zero_mem' := (relationCommutatorIdeal M).zero_mem
  add_mem' hx hy := (relationCommutatorIdeal M).add_mem hx hy
  smul_mem' a u hu := by
    change (u : PresentationTensor M) * a.unop ∈ relationCommutatorIdeal M
    exact (relationCommutatorIdeal M).mul_mem_right a.unop hu

/-- The right-module presentation of `C(M)=K(P)/Z`. -/
abbrev UniversalLieCarrierTensorOpposite :=
  commutatorIdeal M ⧸ commutatorRelationsTensorOpposite M

theorem commutatorRelationsTensorOpposite_restrictScalars :
    (commutatorRelationsTensorOpposite M).restrictScalars ℤ =
      commutatorRelations M := by
  ext u
  rfl

/-- The integral carrier `C(M)` is the same quotient as its right-module presentation. -/
noncomputable def universalLieCarrierRestrictScalarsOppositeEquiv :
    UniversalLieCarrier M ≃ₗ[ℤ] UniversalLieCarrierTensorOpposite M :=
  (Submodule.quotEquivOfEq (commutatorRelations M)
      ((commutatorRelationsTensorOpposite M).restrictScalars ℤ)
      (commutatorRelationsTensorOpposite_restrictScalars M).symm).trans
    (Submodule.Quotient.restrictScalarsEquiv ℤ
      (commutatorRelationsTensorOpposite M))

@[simp]
theorem universalLieCarrierRestrictScalarsOppositeEquiv_mk
    (u : commutatorIdeal M) :
    universalLieCarrierRestrictScalarsOppositeEquiv M (Submodule.Quotient.mk u) =
      Submodule.Quotient.mk u :=
  rfl

/-- The opposite ideal corresponding to the two-sided presentation relation ideal. -/
def relationIdealOpposite : Ideal (PresentationTensor M)ᵐᵒᵖ :=
  (relationIdeal M).toTwoSided.asIdealOpposite

@[simp]
theorem mem_relationIdealOpposite_iff (u : (PresentationTensor M)ᵐᵒᵖ) :
    u ∈ relationIdealOpposite M ↔ u.unop ∈ relationIdeal M := by
  rw [relationIdealOpposite, TwoSidedIdeal.mem_asIdealOpposite,
    Ideal.mem_toTwoSided]

instance relationIdealOpposite_isTwoSided : (relationIdealOpposite M).IsTwoSided := by
  constructor
  intro a b hb
  rw [mem_relationIdealOpposite_iff] at hb ⊢
  change b.unop * a.unop ∈ relationIdeal M
  exact (relationIdeal M).mul_mem_left b.unop hb

/-- The relation ideal annihilates the right `T(P)`-action on `C(M)`. -/
theorem relationIdealOpposite_annihilates_universalLieCarrierTensorOpposite :
    Module.IsTorsionBySet (PresentationTensor M)ᵐᵒᵖ
      (UniversalLieCarrierTensorOpposite M) (relationIdealOpposite M) := by
  rw [Module.isTorsionBySet_quotient_iff]
  intro k q hq
  change (k : PresentationTensor M) * q.unop ∈ relationCommutatorIdeal M
  exact commutator_mul_relation_mem M k
    ⟨q.unop, (mem_relationIdealOpposite_iff M q).mp hq⟩

/-- The right `T(P)`-action descends through the opposite presentation quotient. -/
@[implicit_reducible] noncomputable def
    universalLieCarrierTensorOppositeModuleOverPresentationQuotient :
    Module ((PresentationTensor M)ᵐᵒᵖ ⧸ relationIdealOpposite M)
      (UniversalLieCarrierTensorOpposite M) :=
  (relationIdealOpposite_annihilates_universalLieCarrierTensorOpposite M).module

/-- The canonical map from the opposite presentation quotient to the opposite of the presentation
quotient. -/
def oppositePresentationQuotientMap :
    ((PresentationTensor M)ᵐᵒᵖ ⧸ relationIdealOpposite M) →+*
      (PresentationTensorQuotient M)ᵐᵒᵖ :=
  Ideal.Quotient.lift (relationIdealOpposite M)
    (RingHom.op (Ideal.Quotient.mk (relationIdeal M))) (by
      intro u hu
      change MulOpposite.op (Ideal.Quotient.mk (relationIdeal M) u.unop) = 0
      rw [Ideal.Quotient.eq_zero_iff_mem.mpr
        ((mem_relationIdealOpposite_iff M u).mp hu)]
      rfl)

@[simp]
theorem oppositePresentationQuotientMap_mk (u : (PresentationTensor M)ᵐᵒᵖ) :
    oppositePresentationQuotientMap M
        (Ideal.Quotient.mk (relationIdealOpposite M) u) =
      MulOpposite.op (Ideal.Quotient.mk (relationIdeal M) u.unop) :=
  rfl

/-- Quotienting commutes with passing to the opposite ring. -/
noncomputable def oppositePresentationQuotientEquiv :
    ((PresentationTensor M)ᵐᵒᵖ ⧸ relationIdealOpposite M) ≃+*
      (PresentationTensorQuotient M)ᵐᵒᵖ :=
  RingEquiv.ofBijective (oppositePresentationQuotientMap M) ⟨by
    intro x y hxy
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective x
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective y
    apply Ideal.Quotient.eq.mpr
    rw [oppositePresentationQuotientMap_mk,
      oppositePresentationQuotientMap_mk] at hxy
    have hab : Ideal.Quotient.mk (relationIdeal M) a.unop =
        Ideal.Quotient.mk (relationIdeal M) b.unop :=
      MulOpposite.op_injective hxy
    have habmem : a.unop - b.unop ∈ relationIdeal M :=
      Ideal.Quotient.eq.mp hab
    rw [mem_relationIdealOpposite_iff]
    simpa using habmem
  , by
    intro y
    let z : PresentationTensorQuotient M := y.unop
    obtain ⟨a, ha⟩ := Ideal.Quotient.mk_surjective z
    refine ⟨Ideal.Quotient.mk (relationIdealOpposite M) (MulOpposite.op a), ?_⟩
    rw [oppositePresentationQuotientMap_mk]
    apply MulOpposite.unop_injective
    simpa [z] using ha⟩

/-- A ring equivalence induces an equivalence of the opposite rings. -/
noncomputable def oppositeRingEquiv {R S : Type*} [Ring R] [Ring S]
    (e : R ≃+* S) : Rᵐᵒᵖ ≃+* Sᵐᵒᵖ :=
  RingEquiv.ofBijective (RingHom.op e.toRingHom) ⟨by
    intro x y hxy
    apply MulOpposite.unop_injective
    apply e.injective
    exact MulOpposite.op_injective hxy
  , by
    intro y
    refine ⟨MulOpposite.op (e.symm y.unop), ?_⟩
    apply MulOpposite.unop_injective
    simp⟩

/-- The opposite presentation quotient is canonically the opposite tensor algebra `T(M)ᵐᵒᵖ`. -/
noncomputable def oppositePresentationTensorEquiv :
    ((PresentationTensor M)ᵐᵒᵖ ⧸ relationIdealOpposite M) ≃+*
      (TensorAlgebra ℤ M)ᵐᵒᵖ :=
  (oppositePresentationQuotientEquiv M).trans
    (oppositeRingEquiv (tensorPresentationEquiv M).toRingEquiv)

/-- Higgins's canonical right `T(M)`-action on the right-module presentation of `C(M)`. -/
@[implicit_reducible] noncomputable def
    universalLieCarrierTensorOppositeModuleOverTensor :
    Module (TensorAlgebra ℤ M)ᵐᵒᵖ (UniversalLieCarrierTensorOpposite M) := by
  letI := universalLieCarrierTensorOppositeModuleOverPresentationQuotient M
  exact Module.compHom (UniversalLieCarrierTensorOpposite M)
    (oppositePresentationTensorEquiv M).symm.toRingHom

/-- The canonical left `T(M)`-action transported to the common integral carrier `C(M)`. -/
@[implicit_reducible] noncomputable def universalLieCarrierModuleOverTensor :
    Module (TensorAlgebra ℤ M) (UniversalLieCarrier M) := by
  letI := universalLieCarrierTensorModuleOverTensor M
  exact (universalLieCarrierRestrictScalarsEquiv M).toAddEquiv.module
    (TensorAlgebra ℤ M)

/-- The canonical right `T(M)`-action transported to the common integral carrier `C(M)`. -/
@[implicit_reducible] noncomputable def universalLieCarrierModuleOverTensorOpposite :
    Module (TensorAlgebra ℤ M)ᵐᵒᵖ (UniversalLieCarrier M) := by
  letI := universalLieCarrierTensorOppositeModuleOverTensor M
  exact (universalLieCarrierRestrictScalarsOppositeEquiv M).toAddEquiv.module
    (TensorAlgebra ℤ M)ᵐᵒᵖ

/-- Concrete formula for the descended left action on a quotient representative. -/
theorem tensorPresentationMap_smul_universalLieCarrier_mk
    (a : PresentationTensor M) (k : commutatorIdeal M) :
    letI := universalLieCarrierModuleOverTensor M
    tensorPresentationMap M a • (Submodule.Quotient.mk k : UniversalLieCarrier M) =
      Submodule.Quotient.mk
        (⟨a * (k : PresentationTensor M),
          (commutatorIdeal M).mul_mem_left a k.property⟩ : commutatorIdeal M) := by
  letI := universalLieCarrierTensorModuleOverPresentationQuotient M
  change (universalLieCarrierRestrictScalarsEquiv M).symm
      ((tensorPresentationEquiv M).symm (tensorPresentationMap M a) •
        universalLieCarrierRestrictScalarsEquiv M (Submodule.Quotient.mk k)) = _
  rw [universalLieCarrierRestrictScalarsEquiv_mk]
  have hscalar :
      (tensorPresentationEquiv M).symm (tensorPresentationMap M a) =
        Ideal.Quotient.mk (relationIdeal M) a := by
    apply (tensorPresentationEquiv M).injective
    rw [AlgEquiv.apply_symm_apply]
    rfl
  rw [hscalar]
  rfl

/-- Concrete formula for the descended right action on a quotient representative. -/
theorem op_tensorPresentationMap_smul_universalLieCarrier_mk
    (b : PresentationTensor M) (k : commutatorIdeal M) :
    letI := universalLieCarrierModuleOverTensorOpposite M
    MulOpposite.op (tensorPresentationMap M b) •
        (Submodule.Quotient.mk k : UniversalLieCarrier M) =
      Submodule.Quotient.mk
        (⟨(k : PresentationTensor M) * b,
          (commutatorIdeal M).mul_mem_right b k.property⟩ : commutatorIdeal M) := by
  letI := universalLieCarrierTensorOppositeModuleOverPresentationQuotient M
  change (universalLieCarrierRestrictScalarsOppositeEquiv M).symm
      ((oppositePresentationTensorEquiv M).symm
          (MulOpposite.op (tensorPresentationMap M b)) •
        universalLieCarrierRestrictScalarsOppositeEquiv M
          (Submodule.Quotient.mk k)) = _
  rw [universalLieCarrierRestrictScalarsOppositeEquiv_mk]
  have hscalar :
      (oppositePresentationTensorEquiv M).symm
          (MulOpposite.op (tensorPresentationMap M b)) =
        Ideal.Quotient.mk (relationIdealOpposite M) (MulOpposite.op b) := by
    apply (oppositePresentationTensorEquiv M).injective
    rw [RingEquiv.apply_symm_apply]
    rfl
  rw [hscalar]
  rfl

/-- The descended left and right tensor actions on `C(M)` commute.  Thus `C(M)` is genuinely a
`T(M)`-bimodule. -/
@[implicit_reducible] noncomputable def universalLieCarrierSMulCommClass :
    letI := universalLieCarrierModuleOverTensor M
    letI := universalLieCarrierModuleOverTensorOpposite M
    SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ
      (UniversalLieCarrier M) := by
  letI := universalLieCarrierModuleOverTensor M
  letI := universalLieCarrierModuleOverTensorOpposite M
  constructor
  intro a b c
  induction b using MulOpposite.rec' with
  | _ b =>
      obtain ⟨pa, rfl⟩ := tensorPresentationMap_surjective M a
      obtain ⟨pb, rfl⟩ := tensorPresentationMap_surjective M b
      obtain ⟨k, rfl⟩ := Submodule.Quotient.mk_surjective (commutatorRelations M) c
      rw [op_tensorPresentationMap_smul_universalLieCarrier_mk,
        tensorPresentationMap_smul_universalLieCarrier_mk,
        tensorPresentationMap_smul_universalLieCarrier_mk,
        op_tensorPresentationMap_smul_universalLieCarrier_mk]
      apply congrArg Submodule.Quotient.mk
      apply Subtype.ext
      simp only [mul_assoc]

/-- Higgins's notion of a Lie structure over the integral module `M`.

The carrier is a `T(M)`-bimodule and `bracket x y` is an integral bilinear map satisfying the
three identities (L1)--(L3) from Higgins's paper.  Right multiplication by `t` is written as the
left action of `MulOpposite.op t`.
-/
structure LieStructure (A : Type*) [AddCommGroup A] [Module ℤ A]
    [Module (TensorAlgebra ℤ M) A] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ A] where
  bracket : M →ₗ[ℤ] M →ₗ[ℤ] A
  lie_self : ∀ x, bracket x x = 0
  balance : ∀ x y u v t,
    MulOpposite.op
        ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ •
          (MulOpposite.op t • bracket x y) =
      (⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * t) • bracket u v
  jacobi : ∀ x y z,
    (MulOpposite.op (TensorAlgebra.ι ℤ z) • bracket x y -
        TensorAlgebra.ι ℤ z • bracket x y) +
      (MulOpposite.op (TensorAlgebra.ι ℤ x) • bracket y z -
        TensorAlgebra.ι ℤ x • bracket y z) +
      (MulOpposite.op (TensorAlgebra.ι ℤ y) • bracket z x -
        TensorAlgebra.ι ℤ y • bracket z x) = 0

/-- A morphism of Higgins Lie structures: a bimodule map preserving the distinguished bracket. -/
structure LieStructure.Hom {A B : Type*}
    [AddCommGroup A] [Module ℤ A]
    [Module (TensorAlgebra ℤ M) A] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [AddCommGroup B] [Module ℤ B]
    [Module (TensorAlgebra ℤ M) B] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    (source : LieStructure M A) (target : LieStructure M B) where
  toLinearMap : A →ₗ[TensorAlgebra ℤ M] B
  map_smul_right : ∀ a : (TensorAlgebra ℤ M)ᵐᵒᵖ, ∀ c,
    toLinearMap (a • c) = a • toLinearMap c
  map_bracket : ∀ x y, toLinearMap (source.bracket x y) = target.bracket x y

namespace LieStructure.Hom

instance {A B : Type*}
    [AddCommGroup A] [Module ℤ A]
    [Module (TensorAlgebra ℤ M) A] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [AddCommGroup B] [Module ℤ B]
    [Module (TensorAlgebra ℤ M) B] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    {source : LieStructure M A} {target : LieStructure M B} :
    CoeFun (LieStructure.Hom M source target) fun _ ↦ A → B :=
  ⟨fun f ↦ f.toLinearMap⟩

@[ext]
theorem ext {A B : Type*}
    [AddCommGroup A] [Module ℤ A]
    [Module (TensorAlgebra ℤ M) A] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [AddCommGroup B] [Module ℤ B]
    [Module (TensorAlgebra ℤ M) B] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    {source : LieStructure M A} {target : LieStructure M B}
    {f g : LieStructure.Hom M source target}
    (h : f.toLinearMap = g.toLinearMap) : f = g := by
  cases f
  cases g
  cases h
  rfl

end LieStructure.Hom

/-- A Higgins Lie structure is universal when it admits a unique structure morphism to every
other Lie structure over the same module. -/
def LieStructure.IsUniversal {A : Type*}
    [AddCommGroup A] [Module ℤ A]
    [Module (TensorAlgebra ℤ M) A] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ A]
  (source : LieStructure M A) : Prop :=
  ∀ (B : Type*) [AddCommGroup B] [Module ℤ B]
    [Module (TensorAlgebra ℤ M) B] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ B]
    (target : LieStructure M B),
    ∃ f : LieStructure.Hom M source target, ∀ g, g = f

/-- The distinguished lift of an element of `M` in the canonical free presentation. -/
def canonicalPresentationLift (x : M) : FreePresentation M :=
  Finsupp.single x 1

@[simp]
theorem presentationMap_canonicalPresentationLift (x : M) :
    presentationMap M (canonicalPresentationLift M x) = x :=
  presentationMap_single M x

/-- The elementary commutator associated with two canonical presentation lifts. -/
def canonicalPresentationCommutator (x y : M) : commutatorIdeal M :=
  ⟨⁅TensorAlgebra.ι ℤ (canonicalPresentationLift M x),
      TensorAlgebra.ι ℤ (canonicalPresentationLift M y)⁆, by
    rw [commutatorIdeal, RingHom.mem_ker]
    simp [LieRing.of_associative_ring_bracket, mul_comm]⟩

/-- The prospective universal Lie bracket, as an element of `C(M)=K(P)/Z`. -/
def universalLieBracketValue (x y : M) : UniversalLieCarrier M :=
  Submodule.Quotient.mk (canonicalPresentationCommutator M x y)

theorem universalLieBracketValue_add_left (x₁ x₂ y : M) :
    universalLieBracketValue M (x₁ + x₂) y =
      universalLieBracketValue M x₁ y + universalLieBracketValue M x₂ y := by
  apply (Submodule.Quotient.eq (commutatorRelations M)).mpr
  let q : PresentationRelations M :=
    ⟨canonicalPresentationLift M (x₁ + x₂) -
        canonicalPresentationLift M x₁ - canonicalPresentationLift M x₂, by
      rw [LinearMap.mem_ker]
      simp⟩
  let iq : relationIdeal M :=
    ⟨TensorAlgebra.ι ℤ (q : FreePresentation M),
      ι_relation_mem_relationIdeal M q⟩
  have h := (relationCommutatorIdeal M).neg_mem
    (relation_commutator_mem M
      (TensorAlgebra.ι ℤ (canonicalPresentationLift M y)) iq)
  change (canonicalPresentationCommutator M (x₁ + x₂) y : PresentationTensor M) -
      ((canonicalPresentationCommutator M x₁ y : PresentationTensor M) +
        (canonicalPresentationCommutator M x₂ y : PresentationTensor M)) ∈
    relationCommutatorIdeal M
  have hid :
      (canonicalPresentationCommutator M (x₁ + x₂) y : PresentationTensor M) -
          ((canonicalPresentationCommutator M x₁ y : PresentationTensor M) +
            (canonicalPresentationCommutator M x₂ y : PresentationTensor M)) =
        -⁅TensorAlgebra.ι ℤ (canonicalPresentationLift M y),
          (iq : PresentationTensor M)⁆ := by
    simp only [canonicalPresentationCommutator, iq, q, map_sub,
      LieRing.of_associative_ring_bracket]
    noncomm_ring
  rw [hid]
  exact h

theorem universalLieBracketValue_add_right (x y₁ y₂ : M) :
    universalLieBracketValue M x (y₁ + y₂) =
      universalLieBracketValue M x y₁ + universalLieBracketValue M x y₂ := by
  apply (Submodule.Quotient.eq (commutatorRelations M)).mpr
  let q : PresentationRelations M :=
    ⟨canonicalPresentationLift M (y₁ + y₂) -
        canonicalPresentationLift M y₁ - canonicalPresentationLift M y₂, by
      rw [LinearMap.mem_ker]
      simp⟩
  let iq : relationIdeal M :=
    ⟨TensorAlgebra.ι ℤ (q : FreePresentation M),
      ι_relation_mem_relationIdeal M q⟩
  have h := relation_commutator_mem M
    (TensorAlgebra.ι ℤ (canonicalPresentationLift M x)) iq
  change (canonicalPresentationCommutator M x (y₁ + y₂) : PresentationTensor M) -
      ((canonicalPresentationCommutator M x y₁ : PresentationTensor M) +
        (canonicalPresentationCommutator M x y₂ : PresentationTensor M)) ∈
    relationCommutatorIdeal M
  have hid :
      (canonicalPresentationCommutator M x (y₁ + y₂) : PresentationTensor M) -
          ((canonicalPresentationCommutator M x y₁ : PresentationTensor M) +
            (canonicalPresentationCommutator M x y₂ : PresentationTensor M)) =
        ⁅TensorAlgebra.ι ℤ (canonicalPresentationLift M x),
          (iq : PresentationTensor M)⁆ := by
    simp only [canonicalPresentationCommutator, iq, q, map_sub,
      LieRing.of_associative_ring_bracket]
    noncomm_ring
  rw [hid]
  exact h

theorem universalLieBracketValue_smul_left (r : ℤ) (x y : M) :
    universalLieBracketValue M (r • x) y =
      r • universalLieBracketValue M x y := by
  apply (Submodule.Quotient.eq (commutatorRelations M)).mpr
  let q : PresentationRelations M :=
    ⟨canonicalPresentationLift M (r • x) -
        r • canonicalPresentationLift M x, by
      rw [LinearMap.mem_ker]
      simp⟩
  let iq : relationIdeal M :=
    ⟨TensorAlgebra.ι ℤ (q : FreePresentation M),
      ι_relation_mem_relationIdeal M q⟩
  have h := (relationCommutatorIdeal M).neg_mem
    (relation_commutator_mem M
      (TensorAlgebra.ι ℤ (canonicalPresentationLift M y)) iq)
  change (canonicalPresentationCommutator M (r • x) y : PresentationTensor M) -
      r • (canonicalPresentationCommutator M x y : PresentationTensor M) ∈
    relationCommutatorIdeal M
  have hid :
      (canonicalPresentationCommutator M (r • x) y : PresentationTensor M) -
          r • (canonicalPresentationCommutator M x y : PresentationTensor M) =
        -⁅TensorAlgebra.ι ℤ (canonicalPresentationLift M y),
          (iq : PresentationTensor M)⁆ := by
    simp only [canonicalPresentationCommutator, iq, q, map_sub, map_smul,
      LieRing.of_associative_ring_bracket, smul_sub, sub_mul, mul_sub,
      smul_mul_assoc, mul_smul_comm]
    abel
  rw [hid]
  exact h

theorem universalLieBracketValue_smul_right (r : ℤ) (x y : M) :
    universalLieBracketValue M x (r • y) =
      r • universalLieBracketValue M x y := by
  apply (Submodule.Quotient.eq (commutatorRelations M)).mpr
  let q : PresentationRelations M :=
    ⟨canonicalPresentationLift M (r • y) -
        r • canonicalPresentationLift M y, by
      rw [LinearMap.mem_ker]
      simp⟩
  let iq : relationIdeal M :=
    ⟨TensorAlgebra.ι ℤ (q : FreePresentation M),
      ι_relation_mem_relationIdeal M q⟩
  have h := relation_commutator_mem M
    (TensorAlgebra.ι ℤ (canonicalPresentationLift M x)) iq
  change (canonicalPresentationCommutator M x (r • y) : PresentationTensor M) -
      r • (canonicalPresentationCommutator M x y : PresentationTensor M) ∈
    relationCommutatorIdeal M
  have hid :
      (canonicalPresentationCommutator M x (r • y) : PresentationTensor M) -
          r • (canonicalPresentationCommutator M x y : PresentationTensor M) =
        ⁅TensorAlgebra.ι ℤ (canonicalPresentationLift M x),
          (iq : PresentationTensor M)⁆ := by
    simp only [canonicalPresentationCommutator, iq, q, map_sub, map_smul,
      LieRing.of_associative_ring_bracket, smul_sub, sub_mul, mul_sub,
      smul_mul_assoc, mul_smul_comm]
    abel
  rw [hid]
  exact h

/-- The canonical bilinear bracket on Higgins's carrier `C(M)`. -/
def universalLieBracket :
    M →ₗ[ℤ] M →ₗ[ℤ] UniversalLieCarrier M where
  toFun x :=
    { toFun := universalLieBracketValue M x
      map_add' := universalLieBracketValue_add_right M x
      map_smul' := fun r y ↦ universalLieBracketValue_smul_right M r x y }
  map_add' x₁ x₂ := by
    apply LinearMap.ext
    intro y
    exact universalLieBracketValue_add_left M x₁ x₂ y
  map_smul' r x := by
    apply LinearMap.ext
    intro y
    exact universalLieBracketValue_smul_left M r x y

@[simp]
theorem universalLieBracket_apply (x y : M) :
    universalLieBracket M x y = universalLieBracketValue M x y :=
  rfl

/-- The bracket in `C(M)` may be computed from any lifts in the free presentation, not only the
distinguished singleton lifts.  This is the lift-independence step in Higgins's construction. -/
theorem universalLieBracket_eq_mk_commutator_of_lifts
    (p q : FreePresentation M) :
    universalLieBracket M (presentationMap M p) (presentationMap M q) =
      Submodule.Quotient.mk
        (⟨⁅TensorAlgebra.ι ℤ p, TensorAlgebra.ι ℤ q⁆, by
          rw [commutatorIdeal, RingHom.mem_ker]
          simp [LieRing.of_associative_ring_bracket, mul_comm]⟩ : commutatorIdeal M) := by
  apply (Submodule.Quotient.eq (commutatorRelations M)).mpr
  let px := canonicalPresentationLift M (presentationMap M p)
  let qx := canonicalPresentationLift M (presentationMap M q)
  let dp : PresentationRelations M := ⟨p - px, by
    rw [LinearMap.mem_ker]
    simp [px]⟩
  let dq : PresentationRelations M := ⟨q - qx, by
    rw [LinearMap.mem_ker]
    simp [qx]⟩
  let idp : relationIdeal M :=
    ⟨TensorAlgebra.ι ℤ (dp : FreePresentation M),
      ι_relation_mem_relationIdeal M dp⟩
  let idq : relationIdeal M :=
    ⟨TensorAlgebra.ι ℤ (dq : FreePresentation M),
      ι_relation_mem_relationIdeal M dq⟩
  have hp := relation_commutator_mem M (TensorAlgebra.ι ℤ q) idp
  have hq := (relationCommutatorIdeal M).neg_mem
    (relation_commutator_mem M (TensorAlgebra.ι ℤ px) idq)
  have h := (relationCommutatorIdeal M).add_mem hp hq
  change
    (canonicalPresentationCommutator M (presentationMap M p) (presentationMap M q) :
        PresentationTensor M) -
      ⁅TensorAlgebra.ι ℤ p, TensorAlgebra.ι ℤ q⁆ ∈ relationCommutatorIdeal M
  have hid :
      (canonicalPresentationCommutator M (presentationMap M p) (presentationMap M q) :
          PresentationTensor M) -
          ⁅TensorAlgebra.ι ℤ p, TensorAlgebra.ι ℤ q⁆ =
        ⁅TensorAlgebra.ι ℤ q, (idp : PresentationTensor M)⁆ -
          ⁅TensorAlgebra.ι ℤ px, (idq : PresentationTensor M)⁆ := by
    simp only [canonicalPresentationCommutator, px, qx, idp, idq, dp, dq,
      map_sub, LieRing.of_associative_ring_bracket]
    noncomm_ring
  rw [hid]
  simpa [sub_eq_add_neg] using h

/-- Evaluation sends the presentation commutator of the canonical lifts to the corresponding
degree-one commutator in `T(M)`. -/
theorem tensorPresentationMap_canonicalPresentationCommutator (x y : M) :
    tensorPresentationMap M (canonicalPresentationCommutator M x y) =
      ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ := by
  simp [canonicalPresentationCommutator, LieRing.of_associative_ring_bracket]

theorem universalLieBracket_lie_self (x : M) :
    universalLieBracket M x x = 0 := by
  change Submodule.Quotient.mk (canonicalPresentationCommutator M x x) = 0
  apply (Submodule.Quotient.mk_eq_zero (commutatorRelations M)).mpr
  change ⁅TensorAlgebra.ι ℤ (canonicalPresentationLift M x),
    TensorAlgebra.ι ℤ (canonicalPresentationLift M x)⁆ ∈ relationCommutatorIdeal M
  simp

theorem universalLieBracket_balance (x y u v : M) (t : TensorAlgebra ℤ M) :
    letI := universalLieCarrierModuleOverTensor M
    letI := universalLieCarrierModuleOverTensorOpposite M
    MulOpposite.op
        ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ •
          (MulOpposite.op t • universalLieBracket M x y) =
      (⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * t) •
        universalLieBracket M u v := by
  letI := universalLieCarrierModuleOverTensor M
  letI := universalLieCarrierModuleOverTensorOpposite M
  obtain ⟨p, rfl⟩ := tensorPresentationMap_surjective M t
  rw [← tensorPresentationMap_canonicalPresentationCommutator M u v,
    ← tensorPresentationMap_canonicalPresentationCommutator M x y,
    ← map_mul]
  simp only [universalLieBracket_apply, universalLieBracketValue]
  rw [op_tensorPresentationMap_smul_universalLieCarrier_mk,
    op_tensorPresentationMap_smul_universalLieCarrier_mk,
    tensorPresentationMap_smul_universalLieCarrier_mk]

@[simp]
theorem tensorPresentationMap_ι_canonicalPresentationLift (x : M) :
    tensorPresentationMap M
        (TensorAlgebra.ι ℤ (canonicalPresentationLift M x)) =
      TensorAlgebra.ι ℤ x := by
  rw [tensorPresentationMap_ι, presentationMap_canonicalPresentationLift]

theorem universalLieBracket_jacobi (x y z : M) :
    letI := universalLieCarrierModuleOverTensor M
    letI := universalLieCarrierModuleOverTensorOpposite M
    (MulOpposite.op (TensorAlgebra.ι ℤ z) • universalLieBracket M x y -
        TensorAlgebra.ι ℤ z • universalLieBracket M x y) +
      (MulOpposite.op (TensorAlgebra.ι ℤ x) • universalLieBracket M y z -
        TensorAlgebra.ι ℤ x • universalLieBracket M y z) +
      (MulOpposite.op (TensorAlgebra.ι ℤ y) • universalLieBracket M z x -
        TensorAlgebra.ι ℤ y • universalLieBracket M z x) = 0 := by
  letI := universalLieCarrierModuleOverTensor M
  letI := universalLieCarrierModuleOverTensorOpposite M
  rw [← tensorPresentationMap_ι_canonicalPresentationLift M z,
    ← tensorPresentationMap_ι_canonicalPresentationLift M x,
    ← tensorPresentationMap_ι_canonicalPresentationLift M y]
  simp only [universalLieBracket_apply, universalLieBracketValue]
  rw [op_tensorPresentationMap_smul_universalLieCarrier_mk,
    tensorPresentationMap_smul_universalLieCarrier_mk,
    op_tensorPresentationMap_smul_universalLieCarrier_mk,
    tensorPresentationMap_smul_universalLieCarrier_mk,
    op_tensorPresentationMap_smul_universalLieCarrier_mk,
    tensorPresentationMap_smul_universalLieCarrier_mk]
  apply (Submodule.Quotient.eq (commutatorRelations M)).mpr
  change
    (((canonicalPresentationCommutator M x y : PresentationTensor M) *
          TensorAlgebra.ι ℤ (canonicalPresentationLift M z) -
        TensorAlgebra.ι ℤ (canonicalPresentationLift M z) *
          (canonicalPresentationCommutator M x y : PresentationTensor M)) +
      ((canonicalPresentationCommutator M y z : PresentationTensor M) *
          TensorAlgebra.ι ℤ (canonicalPresentationLift M x) -
        TensorAlgebra.ι ℤ (canonicalPresentationLift M x) *
          (canonicalPresentationCommutator M y z : PresentationTensor M)) +
      ((canonicalPresentationCommutator M z x : PresentationTensor M) *
          TensorAlgebra.ι ℤ (canonicalPresentationLift M y) -
        TensorAlgebra.ι ℤ (canonicalPresentationLift M y) *
          (canonicalPresentationCommutator M z x : PresentationTensor M))) - 0 ∈
        relationCommutatorIdeal M
  have hzero :
      ((canonicalPresentationCommutator M x y : PresentationTensor M) *
            TensorAlgebra.ι ℤ (canonicalPresentationLift M z) -
          TensorAlgebra.ι ℤ (canonicalPresentationLift M z) *
            (canonicalPresentationCommutator M x y : PresentationTensor M)) +
        ((canonicalPresentationCommutator M y z : PresentationTensor M) *
            TensorAlgebra.ι ℤ (canonicalPresentationLift M x) -
          TensorAlgebra.ι ℤ (canonicalPresentationLift M x) *
            (canonicalPresentationCommutator M y z : PresentationTensor M)) +
        ((canonicalPresentationCommutator M z x : PresentationTensor M) *
            TensorAlgebra.ι ℤ (canonicalPresentationLift M y) -
          TensorAlgebra.ι ℤ (canonicalPresentationLift M y) *
            (canonicalPresentationCommutator M z x : PresentationTensor M)) = 0 := by
    simp only [canonicalPresentationCommutator,
      LieRing.of_associative_ring_bracket]
    noncomm_ring
  rw [hzero, sub_zero]
  exact (relationCommutatorIdeal M).zero_mem

/-- Higgins's carrier `C(M)` with its canonical bracket is a Lie structure over `M`. -/
noncomputable def universalLieStructure :
    letI := universalLieCarrierModuleOverTensor M
    letI := universalLieCarrierModuleOverTensorOpposite M
    letI := universalLieCarrierSMulCommClass M
    LieStructure M (UniversalLieCarrier M) := by
  letI := universalLieCarrierModuleOverTensor M
  letI := universalLieCarrierModuleOverTensorOpposite M
  letI := universalLieCarrierSMulCommClass M
  exact
    { bracket := universalLieBracket M
      lie_self := universalLieBracket_lie_self M
      balance := universalLieBracket_balance M
      jacobi := universalLieBracket_jacobi M }

/-- There is at most one morphism from Higgins's canonical structure `C(M)` to any other Lie
structure over `M`.  Thus the uniqueness half of its universal property is completely formal once
lift-independence and generation by elementary commutators are known. -/
theorem universalLieStructure_hom_unique
    {A : Type*} [AddCommGroup A] [Module ℤ A]
    [Module (TensorAlgebra ℤ M) A] [Module (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    [SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ A]
    (target : LieStructure M A) :
    letI := universalLieCarrierModuleOverTensor M
    letI := universalLieCarrierModuleOverTensorOpposite M
    letI := universalLieCarrierSMulCommClass M
    ∀ f g : LieStructure.Hom M (universalLieStructure M) target, f = g := by
  letI := universalLieCarrierModuleOverTensor M
  letI := universalLieCarrierModuleOverTensorOpposite M
  letI := universalLieCarrierSMulCommClass M
  intro f g
  apply LieStructure.Hom.ext
  apply LinearMap.ext
  intro c
  obtain ⟨k, rfl⟩ := Submodule.Quotient.mk_surjective (commutatorRelations M) c
  let generatorIdeal := TwoSidedIdeal.span
    (Set.range fun xy : FreePresentation M × FreePresentation M ↦
      ⁅TensorAlgebra.ι ℤ xy.1, TensorAlgebra.ι ℤ xy.2⁆)
  have hk : (k : PresentationTensor M) ∈ generatorIdeal := by
    change (k : PresentationTensor M) ∈ elementaryCommutatorIdeal (FreePresentation M)
    rw [elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
    exact k.property
  have hspan : ∀ (u : PresentationTensor M) (hu : u ∈ generatorIdeal),
      f (Submodule.Quotient.mk
        (⟨u, by
          change u ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hu⟩ : commutatorIdeal M)) =
      g (Submodule.Quotient.mk
        (⟨u, by
          change u ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hu⟩ : commutatorIdeal M)) := by
    intro u hu
    induction hu using TwoSidedIdeal.span_induction with
    | mem u hu =>
        obtain ⟨⟨p, q⟩, rfl⟩ := hu
        rw [← universalLieBracket_eq_mk_commutator_of_lifts M p q]
        exact (f.map_bracket (presentationMap M p) (presentationMap M q)).trans
          (g.map_bracket (presentationMap M p) (presentationMap M q)).symm
    | zero =>
        change f.toLinearMap 0 = g.toLinearMap 0
        rw [map_zero, map_zero]
    | add x y hxmem hymem hx hy =>
        let kx : commutatorIdeal M := ⟨x, by
          change x ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hxmem⟩
        let ky : commutatorIdeal M := ⟨y, by
          change y ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hymem⟩
        change f.toLinearMap (Submodule.Quotient.mk kx + Submodule.Quotient.mk ky) =
          g.toLinearMap (Submodule.Quotient.mk kx + Submodule.Quotient.mk ky)
        rw [map_add, map_add]
        exact congrArg₂ (· + ·) hx hy
    | neg x hxmem hx =>
        let kx : commutatorIdeal M := ⟨x, by
          change x ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hxmem⟩
        change f.toLinearMap (-Submodule.Quotient.mk kx) =
          g.toLinearMap (-Submodule.Quotient.mk kx)
        rw [map_neg, map_neg]
        exact congrArg Neg.neg hx
    | left_absorb a x hxmem hx =>
        let kx : commutatorIdeal M := ⟨x, by
          change x ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hxmem⟩
        rw [← tensorPresentationMap_smul_universalLieCarrier_mk M a kx,
          map_smul, map_smul, hx]
    | right_absorb b x hxmem hx =>
        let kx : commutatorIdeal M := ⟨x, by
          change x ∈ tensorCommutatorIdeal (FreePresentation M)
          rw [← elementaryCommutatorIdeal_eq_tensorCommutatorIdeal]
          exact hxmem⟩
        rw [← op_tensorPresentationMap_smul_universalLieCarrier_mk M b kx,
          f.map_smul_right, g.map_smul_right, hx]
  exact hspan (k : PresentationTensor M) hk

/-- The commutator ideal `K(M)`, viewed as a right `T(M)`-module. -/
def tensorCommutatorIdealOpposite :
    Submodule (TensorAlgebra ℤ M)ᵐᵒᵖ (TensorAlgebra ℤ M) where
  carrier := tensorCommutatorIdeal M
  zero_mem' := (tensorCommutatorIdeal M).zero_mem
  add_mem' hx hy := (tensorCommutatorIdeal M).add_mem hx hy
  smul_mem' a u hu := by
    change u * a.unop ∈ tensorCommutatorIdeal M
    exact (tensorCommutatorIdeal M).mul_mem_right a.unop hu

@[implicit_reducible] noncomputable instance tensorCommutatorIdealModuleOpposite :
    Module (TensorAlgebra ℤ M)ᵐᵒᵖ (tensorCommutatorIdeal M) :=
  inferInstanceAs
    (Module (TensorAlgebra ℤ M)ᵐᵒᵖ (tensorCommutatorIdealOpposite M))

/-- Left and right multiplication commute on the concrete commutator ideal. -/
@[implicit_reducible] noncomputable def tensorCommutatorIdealSMulCommClass :
    SMulCommClass (TensorAlgebra ℤ M) (TensorAlgebra ℤ M)ᵐᵒᵖ
      (tensorCommutatorIdeal M) := by
  constructor
  intro a b k
  induction b using MulOpposite.rec' with
  | _ b =>
      apply Subtype.ext
      change a * ((k : TensorAlgebra ℤ M) * b) =
        (a * (k : TensorAlgebra ℤ M)) * b
      rw [mul_assoc]

/-- The elementary degree-one commutator, as an element of `K(M)`. -/
def tensorCommutatorBracketValue (x y : M) : tensorCommutatorIdeal M :=
  ⟨⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆, by
    rw [tensorCommutatorIdeal, RingHom.mem_ker]
    simp [LieRing.of_associative_ring_bracket, mul_comm]⟩

/-- The concrete bilinear commutator bracket on `K(M)`. -/
def tensorCommutatorBracket :
    M →ₗ[ℤ] M →ₗ[ℤ] tensorCommutatorIdeal M where
  toFun x :=
    { toFun := tensorCommutatorBracketValue M x
      map_add' := by
        intro y z
        apply Subtype.ext
        simp [tensorCommutatorBracketValue, lie_add]
      map_smul' := by
        intro r y
        apply Subtype.ext
        simp only [tensorCommutatorBracketValue, map_smul]
        change
          ⁅TensorAlgebra.ι ℤ x, r • TensorAlgebra.ι ℤ y⁆ =
            r • ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆
        rw [lie_smul] }
  map_add' := by
    intro x y
    apply LinearMap.ext
    intro z
    apply Subtype.ext
    simp [tensorCommutatorBracketValue, add_lie]
  map_smul' := by
    intro r x
    apply LinearMap.ext
    intro y
    apply Subtype.ext
    simp only [LinearMap.coe_mk, AddHom.coe_mk,
      LinearMap.smul_apply, RingHom.id_apply]
    simp only [tensorCommutatorBracketValue, map_smul]
    change
      ⁅r • TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ =
        r • ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆
    rw [smul_lie]

@[simp]
theorem tensorCommutatorBracket_apply (x y : M) :
    tensorCommutatorBracket M x y = tensorCommutatorBracketValue M x y :=
  rfl

/-- The concrete commutator ideal is a Higgins Lie structure. -/
noncomputable def tensorCommutatorLieStructure :
    letI := tensorCommutatorIdealSMulCommClass M
    LieStructure M (tensorCommutatorIdeal M) := by
  letI := tensorCommutatorIdealSMulCommClass M
  refine
    { bracket := tensorCommutatorBracket M
      lie_self := ?_
      balance := ?_
      jacobi := ?_ }
  · intro x
    apply Subtype.ext
    simp [tensorCommutatorBracketValue]
  · intro x y u v t
    apply Subtype.ext
    simp only [tensorCommutatorBracket_apply, tensorCommutatorBracketValue]
    rfl
  · intro x y z
    apply Subtype.ext
    change
      (⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * TensorAlgebra.ι ℤ z -
          TensorAlgebra.ι ℤ z * ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆) +
        (⁅TensorAlgebra.ι ℤ y, TensorAlgebra.ι ℤ z⁆ * TensorAlgebra.ι ℤ x -
          TensorAlgebra.ι ℤ x * ⁅TensorAlgebra.ι ℤ y, TensorAlgebra.ι ℤ z⁆) +
        (⁅TensorAlgebra.ι ℤ z, TensorAlgebra.ι ℤ x⁆ * TensorAlgebra.ι ℤ y -
          TensorAlgebra.ι ℤ y * ⁅TensorAlgebra.ι ℤ z, TensorAlgebra.ι ℤ x⁆) = 0
    simp only [LieRing.of_associative_ring_bracket]
    noncomm_ring

/-- Evaluation on commutator ideals descends from `K(P)` through `C(M)`. -/
def universalCommutatorMap :
    UniversalLieCarrier M →ₗ[ℤ] tensorCommutatorIdeal M :=
  (commutatorRelations M).liftQ (commutatorMap M) (by
    intro u hu
    rw [LinearMap.mem_ker]
    apply Subtype.ext
    change tensorPresentationMap M (u : PresentationTensor M) = 0
    exact RingHom.mem_ker.mp
      (relationIdeal_le_ker_tensorPresentationMap M
        (relationCommutatorIdeal_le_relationIdeal M hu)))

@[simp]
theorem universalCommutatorMap_mk (u : commutatorIdeal M) :
    universalCommutatorMap M (Submodule.Quotient.mk u) = commutatorMap M u :=
  rfl

/-- The canonical comparison `C(M) → K(M)` respects the left `T(M)`-action. -/
theorem universalCommutatorMap_smul_left
    (a : TensorAlgebra ℤ M) (c : UniversalLieCarrier M) :
    letI := universalLieCarrierModuleOverTensor M
    universalCommutatorMap M (a • c) = a • universalCommutatorMap M c := by
  letI := universalLieCarrierModuleOverTensor M
  obtain ⟨p, rfl⟩ := tensorPresentationMap_surjective M a
  obtain ⟨k, rfl⟩ :=
    Submodule.Quotient.mk_surjective (commutatorRelations M) c
  rw [tensorPresentationMap_smul_universalLieCarrier_mk,
    universalCommutatorMap_mk, universalCommutatorMap_mk]
  apply Subtype.ext
  exact map_mul (tensorPresentationMap M) p (k : PresentationTensor M)

/-- The canonical comparison `C(M) → K(M)` respects the right `T(M)`-action. -/
theorem universalCommutatorMap_smul_right
    (a : (TensorAlgebra ℤ M)ᵐᵒᵖ) (c : UniversalLieCarrier M) :
    letI := universalLieCarrierModuleOverTensorOpposite M
    universalCommutatorMap M (a • c) = a • universalCommutatorMap M c := by
  letI := universalLieCarrierModuleOverTensorOpposite M
  induction a using MulOpposite.rec' with
  | _ a =>
      obtain ⟨p, rfl⟩ := tensorPresentationMap_surjective M a
      obtain ⟨k, rfl⟩ :=
        Submodule.Quotient.mk_surjective (commutatorRelations M) c
      rw [op_tensorPresentationMap_smul_universalLieCarrier_mk,
        universalCommutatorMap_mk, universalCommutatorMap_mk]
      apply Subtype.ext
      exact map_mul (tensorPresentationMap M) (k : PresentationTensor M) p

/-- The canonical comparison sends the universal bracket to the concrete tensor commutator. -/
theorem universalCommutatorMap_bracket (x y : M) :
    universalCommutatorMap M (universalLieBracket M x y) =
      tensorCommutatorBracket M x y := by
  rw [universalLieBracket_apply]
  apply Subtype.ext
  exact tensorPresentationMap_canonicalPresentationCommutator M x y

/-- The canonical comparison `C(M) → K(M)`, bundled as a morphism of Higgins Lie structures. -/
noncomputable def universalCommutatorLieStructureHom :
    letI := universalLieCarrierModuleOverTensor M
    letI := universalLieCarrierModuleOverTensorOpposite M
    letI := universalLieCarrierSMulCommClass M
    letI := tensorCommutatorIdealSMulCommClass M
    LieStructure.Hom M (universalLieStructure M)
      (tensorCommutatorLieStructure M) := by
  letI := universalLieCarrierModuleOverTensor M
  letI := universalLieCarrierModuleOverTensorOpposite M
  letI := universalLieCarrierSMulCommClass M
  letI := tensorCommutatorIdealSMulCommClass M
  exact
    { toLinearMap :=
        { toFun := universalCommutatorMap M
          map_add' := map_add (universalCommutatorMap M)
          map_smul' := universalCommutatorMap_smul_left M }
      map_smul_right := universalCommutatorMap_smul_right M
      map_bracket := universalCommutatorMap_bracket M }

/-- The map `C(M) → K(M)` is always onto. -/
theorem universalCommutatorMap_surjective :
    Function.Surjective (universalCommutatorMap M) := by
  intro u
  obtain ⟨p, rfl⟩ := commutatorMap_surjective M u
  exact ⟨Submodule.Quotient.mk p, universalCommutatorMap_mk M p⟩

/-- The kernel part of Higgins's exact sequence:
if `B(M)=0`, then `C(M) → K(M)` is injective. -/
theorem universalCommutatorMap_injective_of_obstructionVanishes
    (hB : ObstructionVanishes M) :
    Function.Injective (universalCommutatorMap M) := by
  rw [← LinearMap.ker_eq_bot]
  apply bot_unique
  intro c hc
  obtain ⟨u, rfl⟩ := Submodule.Quotient.mk_surjective (commutatorRelations M) c
  rw [LinearMap.mem_ker] at hc
  change commutatorMap M u = 0 at hc
  have htensor : tensorPresentationMap M (u : PresentationTensor M) = 0 := by
    exact congrArg Subtype.val hc
  have hrelation : (u : PresentationTensor M) ∈ relationIdeal M := by
    rw [relationIdeal_eq_ker_tensorPresentationMap, RingHom.mem_ker]
    exact htensor
  have hnum : (u : PresentationTensor M) ∈ baerNumerator M :=
    ⟨u.property, hrelation⟩
  have hz : (u : PresentationTensor M) ∈ relationCommutatorIdeal M :=
    (obstructionVanishes_iff M).mp hB hnum
  exact (Submodule.Quotient.mk_eq_zero (commutatorRelations M)).2 hz

/-- Higgins's exact sequence gives `C(M) ≃ K(M)` when the Baer obstruction vanishes. -/
noncomputable def universalCommutatorEquivOfObstructionVanishes
    (hB : ObstructionVanishes M) :
    UniversalLieCarrier M ≃ₗ[ℤ] tensorCommutatorIdeal M :=
  LinearEquiv.ofBijective (universalCommutatorMap M)
    ⟨universalCommutatorMap_injective_of_obstructionVanishes M hB,
      universalCommutatorMap_surjective M⟩

@[simp]
theorem universalCommutatorEquivOfObstructionVanishes_apply
    (hB : ObstructionVanishes M) (c : UniversalLieCarrier M) :
    universalCommutatorEquivOfObstructionVanishes M hB c =
      universalCommutatorMap M c :=
  rfl

/-- When the obstruction vanishes, the comparison equivalence preserves the left tensor action. -/
theorem universalCommutatorEquivOfObstructionVanishes_smul_left
    (hB : ObstructionVanishes M) (a : TensorAlgebra ℤ M)
    (c : UniversalLieCarrier M) :
    letI := universalLieCarrierModuleOverTensor M
    universalCommutatorEquivOfObstructionVanishes M hB (a • c) =
      a • universalCommutatorEquivOfObstructionVanishes M hB c := by
  letI := universalLieCarrierModuleOverTensor M
  exact universalCommutatorMap_smul_left M a c

/-- When the obstruction vanishes, the comparison equivalence preserves the right tensor action. -/
theorem universalCommutatorEquivOfObstructionVanishes_smul_right
    (hB : ObstructionVanishes M) (a : (TensorAlgebra ℤ M)ᵐᵒᵖ)
    (c : UniversalLieCarrier M) :
    letI := universalLieCarrierModuleOverTensorOpposite M
    universalCommutatorEquivOfObstructionVanishes M hB (a • c) =
      a • universalCommutatorEquivOfObstructionVanishes M hB c := by
  letI := universalLieCarrierModuleOverTensorOpposite M
  exact universalCommutatorMap_smul_right M a c

/-- When the obstruction vanishes, the comparison equivalence identifies the universal bracket
with the concrete commutator bracket. -/
theorem universalCommutatorEquivOfObstructionVanishes_bracket
    (hB : ObstructionVanishes M) (x y : M) :
    universalCommutatorEquivOfObstructionVanishes M hB
        (universalLieBracket M x y) =
      tensorCommutatorBracket M x y :=
  universalCommutatorMap_bracket M x y

/-- For a projective integral module, Higgins's canonical comparison is an equivalence without an
extra obstruction hypothesis. -/
noncomputable def universalCommutatorEquivOfProjective [Module.Projective ℤ M] :
    UniversalLieCarrier M ≃ₗ[ℤ] tensorCommutatorIdeal M :=
  universalCommutatorEquivOfObstructionVanishes M (obstructionVanishes_of_projective M)

end

end LieRings.PBW.Higgins
