import LieRings.PBW.HigginsPBW
import LieRings.UniversalEnveloping.Basic
import Mathlib.Algebra.DirectSum.Module

/-!
# Higgins's filtration of the enveloping-algebra relation ideal

For a Lie ring `L`, put `T = T_ℤ(L)` and

`r(x,y) = x y - y x - [x,y] ∈ T`.

The defining ideal `J` of `U(L)` is the two-sided ideal generated by the `r(x,y)`.  Following
Higgins, `J(n)` is spanned by the expressions `a * r(x,y) * b` for which `a` and `b` have tensor
degree at most `p` and `q`, respectively, with `p + q + 2 ≤ n`.

This file establishes the complete filtration API needed by Higgins's Theorem 2: `J(n)` is
increasing, lies in both `J` and tensor degree at most `n`, multiplication by a degree-one
generator raises the index by at most one, and the union of the `J(n)` is all of `J`.
-/

namespace LieRings.PBW.Higgins

universe u

noncomputable section

open scoped DirectSum

variable (L : Type u) [LieRing L] [LieAlgebra ℤ L]

local notation "T" => TensorAlgebra ℤ L

/-- A pure tensor word in the tensor algebra. -/
def tensorWord (xs : List L) : T :=
  (xs.map (TensorAlgebra.ι ℤ)).prod

@[simp]
theorem tensorWord_nil : tensorWord L [] = 1 :=
  rfl

@[simp]
theorem tensorWord_singleton (x : L) :
    tensorWord L [x] = TensorAlgebra.ι ℤ x := by
  simp [tensorWord]

theorem tensorWord_append (xs ys : List L) :
    tensorWord L (xs ++ ys) = tensorWord L xs * tensorWord L ys := by
  simp [tensorWord]

/-- The standard increasing tensor-degree filtration `T₀ ⊆ T₁ ⊆ ⋯`. -/
def tensorDegreeFiltration (n : ℕ) : Submodule ℤ T :=
  Submodule.span ℤ {t | ∃ xs : List L, xs.length ≤ n ∧ t = tensorWord L xs}

theorem tensorWord_mem_tensorDegreeFiltration {xs : List L} {n : ℕ}
    (hxs : xs.length ≤ n) :
    tensorWord L xs ∈ tensorDegreeFiltration L n := by
  apply Submodule.subset_span
  exact ⟨xs, hxs, rfl⟩

theorem tensorDegreeFiltration_mono : Monotone (tensorDegreeFiltration L) := by
  intro m n hmn
  apply Submodule.span_mono
  rintro t ⟨xs, hxs, rfl⟩
  exact ⟨xs, hxs.trans hmn, rfl⟩

theorem one_mem_tensorDegreeFiltration :
    (1 : T) ∈ tensorDegreeFiltration L 0 := by
  simpa using tensorWord_mem_tensorDegreeFiltration L (xs := []) (n := 0) (by simp)

theorem ι_mem_tensorDegreeFiltration (x : L) :
    TensorAlgebra.ι ℤ x ∈ tensorDegreeFiltration L 1 := by
  simpa using tensorWord_mem_tensorDegreeFiltration L (xs := [x]) (n := 1) (by simp)

theorem algebraMap_mem_tensorDegreeFiltration (z : ℤ) :
    algebraMap ℤ T z ∈ tensorDegreeFiltration L 0 := by
  rw [Algebra.algebraMap_eq_smul_one]
  exact (tensorDegreeFiltration L 0).smul_mem z (one_mem_tensorDegreeFiltration L)

/-- Products add tensor-degree bounds. -/
theorem tensorDegreeFiltration_mul {m n : ℕ} {a b : T}
    (ha : a ∈ tensorDegreeFiltration L m)
    (hb : b ∈ tensorDegreeFiltration L n) :
    a * b ∈ tensorDegreeFiltration L (m + n) := by
  induction ha using Submodule.span_induction with
  | mem a ha =>
      obtain ⟨xs, hxs, rfl⟩ := ha
      induction hb using Submodule.span_induction with
      | mem b hb =>
          obtain ⟨ys, hys, rfl⟩ := hb
          rw [← tensorWord_append]
          exact tensorWord_mem_tensorDegreeFiltration L
            (by simpa using Nat.add_le_add hxs hys)
      | zero => simp
      | add x y _ _ hx hy => simpa [mul_add] using (tensorDegreeFiltration L (m + n)).add_mem hx hy
      | smul z x _ hx =>
          rw [mul_smul_comm]
          exact (tensorDegreeFiltration L (m + n)).smul_mem z hx
  | zero => simp
  | add x y _ _ hx hy => simpa [add_mul] using (tensorDegreeFiltration L (m + n)).add_mem hx hy
  | smul z x _ hx =>
      rw [smul_mul_assoc]
      exact (tensorDegreeFiltration L (m + n)).smul_mem z hx

/-- Every tensor has a finite tensor-degree bound. -/
theorem exists_mem_tensorDegreeFiltration (t : T) :
    ∃ n, t ∈ tensorDegreeFiltration L n := by
  induction t using TensorAlgebra.induction with
  | algebraMap z => exact ⟨0, algebraMap_mem_tensorDegreeFiltration L z⟩
  | ι x => exact ⟨1, ι_mem_tensorDegreeFiltration L x⟩
  | mul x y hx hy =>
      obtain ⟨m, hm⟩ := hx
      obtain ⟨n, hn⟩ := hy
      exact ⟨m + n, tensorDegreeFiltration_mul L hm hn⟩
  | add x y hx hy =>
      obtain ⟨m, hm⟩ := hx
      obtain ⟨n, hn⟩ := hy
      refine ⟨max m n, (tensorDegreeFiltration L (max m n)).add_mem ?_ ?_⟩
      · exact tensorDegreeFiltration_mono L (Nat.le_max_left _ _) hm
      · exact tensorDegreeFiltration_mono L (Nat.le_max_right _ _) hn

/-- The tensor-algebra relation defining the universal enveloping algebra. -/
def envelopingRelation (x y : L) : T :=
  TensorAlgebra.ι ℤ x * TensorAlgebra.ι ℤ y -
    TensorAlgebra.ι ℤ y * TensorAlgebra.ι ℤ x -
      TensorAlgebra.ι ℤ ⁅x, y⁆

/-- The two-sided defining ideal `J` of the universal enveloping algebra. -/
def envelopingRelationIdeal : Ideal T :=
  (TwoSidedIdeal.span (Set.range fun xy : L × L ↦ envelopingRelation L xy.1 xy.2)).asIdeal

instance envelopingRelationIdeal_isTwoSided :
    (envelopingRelationIdeal L).IsTwoSided :=
  show (TwoSidedIdeal.span
    (Set.range fun xy : L × L ↦ envelopingRelation L xy.1 xy.2)).asIdeal.IsTwoSided from
    inferInstance

theorem envelopingRelation_mem_ideal (x y : L) :
    envelopingRelation L x y ∈ envelopingRelationIdeal L := by
  exact TwoSidedIdeal.subset_span ⟨(x, y), rfl⟩

theorem envelopingRelation_mem_tensorDegreeFiltration (x y : L) :
    envelopingRelation L x y ∈ tensorDegreeFiltration L 2 := by
  apply (tensorDegreeFiltration L 2).sub_mem
  · apply (tensorDegreeFiltration L 2).sub_mem
    · simpa using tensorDegreeFiltration_mul L (ι_mem_tensorDegreeFiltration L x)
        (ι_mem_tensorDegreeFiltration L y)
    · simpa using tensorDegreeFiltration_mul L (ι_mem_tensorDegreeFiltration L y)
        (ι_mem_tensorDegreeFiltration L x)
  · exact tensorDegreeFiltration_mono L (by omega)
      (ι_mem_tensorDegreeFiltration L ⁅x, y⁆)

/-- Generators used in Higgins's `J(n)`. -/
def higginsFiltrationGenerators (n : ℕ) : Set T :=
  {t | ∃ (p q : ℕ) (x y : L) (a b : T),
    p + q + 2 ≤ n ∧
      a ∈ tensorDegreeFiltration L p ∧
      b ∈ tensorDegreeFiltration L q ∧
      t = a * envelopingRelation L x y * b}

/-- Higgins's filtration `J(n)` of the defining ideal `J`. -/
def higginsFiltration (n : ℕ) : Submodule ℤ T :=
  Submodule.span ℤ (higginsFiltrationGenerators L n)

theorem higginsFiltration_mono : Monotone (higginsFiltration L) := by
  intro m n hmn
  apply Submodule.span_mono
  rintro t ⟨p, q, x, y, a, b, hpq, ha, hb, rfl⟩
  exact ⟨p, q, x, y, a, b, hpq.trans hmn, ha, hb, rfl⟩

@[simp]
theorem higginsFiltration_zero : higginsFiltration L 0 = ⊥ := by
  rw [higginsFiltration]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro t ⟨p, q, x, y, a, b, hpq, ha, hb, rfl⟩
    omega
  · exact bot_le

@[simp]
theorem higginsFiltration_one : higginsFiltration L 1 = ⊥ := by
  rw [higginsFiltration]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro t ⟨p, q, x, y, a, b, hpq, ha, hb, rfl⟩
    omega
  · exact bot_le

theorem envelopingRelation_mem_higginsFiltration_two (x y : L) :
    envelopingRelation L x y ∈ higginsFiltration L 2 := by
  apply Submodule.subset_span
  refine ⟨0, 0, x, y, 1, 1, by omega, one_mem_tensorDegreeFiltration L,
    one_mem_tensorDegreeFiltration L, ?_⟩
  simp

/-- Every `J(n)` lies in the two-sided defining ideal `J`. -/
theorem higginsFiltration_le_envelopingRelationIdeal (n : ℕ) :
    higginsFiltration L n ≤ (envelopingRelationIdeal L).restrictScalars ℤ := by
  rw [higginsFiltration, Submodule.span_le]
  rintro t ⟨p, q, x, y, a, b, hpq, ha, hb, rfl⟩
  exact (envelopingRelationIdeal L).mul_mem_right b
    ((envelopingRelationIdeal L).mul_mem_left a
      (envelopingRelation_mem_ideal L x y))

/-- Every `J(n)` consists of tensors of degree at most `n`. -/
theorem higginsFiltration_le_tensorDegreeFiltration (n : ℕ) :
    higginsFiltration L n ≤ tensorDegreeFiltration L n := by
  rw [higginsFiltration, Submodule.span_le]
  rintro t ⟨p, q, x, y, a, b, hpq, ha, hb, rfl⟩
  apply tensorDegreeFiltration_mono L (by omega : (p + 2) + q ≤ n)
  exact tensorDegreeFiltration_mul L
    (tensorDegreeFiltration_mul L ha
      (envelopingRelation_mem_tensorDegreeFiltration L x y)) hb

/-- Left multiplication by one canonical generator raises Higgins degree by at most one. -/
theorem ι_mul_mem_higginsFiltration_succ {n : ℕ} (z : L) {t : T}
    (ht : t ∈ higginsFiltration L n) :
    TensorAlgebra.ι ℤ z * t ∈ higginsFiltration L (n + 1) := by
  induction ht using Submodule.span_induction with
  | mem t ht =>
      obtain ⟨p, q, x, y, a, b, hpq, ha, hb, rfl⟩ := ht
      apply Submodule.subset_span
      refine ⟨1 + p, q, x, y, TensorAlgebra.ι ℤ z * a, b, by omega, ?_, hb, ?_⟩
      · exact tensorDegreeFiltration_mul L (ι_mem_tensorDegreeFiltration L z) ha
      · simp [mul_assoc]
  | zero => simp
  | add x y _ _ hx hy => simpa [mul_add] using (higginsFiltration L (n + 1)).add_mem hx hy
  | smul a x _ hx =>
      rw [mul_smul_comm]
      exact (higginsFiltration L (n + 1)).smul_mem a hx

/-- Right multiplication by one canonical generator raises Higgins degree by at most one. -/
theorem mul_ι_mem_higginsFiltration_succ {n : ℕ} (z : L) {t : T}
    (ht : t ∈ higginsFiltration L n) :
    t * TensorAlgebra.ι ℤ z ∈ higginsFiltration L (n + 1) := by
  induction ht using Submodule.span_induction with
  | mem t ht =>
      obtain ⟨p, q, x, y, a, b, hpq, ha, hb, rfl⟩ := ht
      apply Submodule.subset_span
      refine ⟨p, q + 1, x, y, a, b * TensorAlgebra.ι ℤ z, by omega, ha, ?_, ?_⟩
      · exact tensorDegreeFiltration_mul L hb (ι_mem_tensorDegreeFiltration L z)
      · simp [mul_assoc]
  | zero => simp
  | add x y _ _ hx hy => simpa [add_mul] using (higginsFiltration L (n + 1)).add_mem hx hy
  | smul a x _ hx =>
      rw [smul_mul_assoc]
      exact (higginsFiltration L (n + 1)).smul_mem a hx

/-- The union of the `J(n)` is the whole defining ideal `J`. -/
theorem exists_higginsFiltration_of_mem_envelopingRelationIdeal {t : T}
    (ht : t ∈ envelopingRelationIdeal L) :
    ∃ n, t ∈ higginsFiltration L n := by
  change t ∈ TwoSidedIdeal.span
    (Set.range fun xy : L × L ↦ envelopingRelation L xy.1 xy.2) at ht
  induction ht using TwoSidedIdeal.span_induction with
  | mem t ht =>
      obtain ⟨⟨x, y⟩, rfl⟩ := ht
      exact ⟨2, envelopingRelation_mem_higginsFiltration_two L x y⟩
  | zero => exact ⟨0, (higginsFiltration L 0).zero_mem⟩
  | add x y _ _ hx hy =>
      obtain ⟨m, hm⟩ := hx
      obtain ⟨n, hn⟩ := hy
      refine ⟨max m n, (higginsFiltration L (max m n)).add_mem ?_ ?_⟩
      · exact higginsFiltration_mono L (Nat.le_max_left _ _) hm
      · exact higginsFiltration_mono L (Nat.le_max_right _ _) hn
  | neg x _ hx =>
      obtain ⟨n, hn⟩ := hx
      exact ⟨n, (higginsFiltration L n).neg_mem hn⟩
  | left_absorb a x _ hx =>
      obtain ⟨m, hm⟩ := exists_mem_tensorDegreeFiltration L a
      obtain ⟨n, hn⟩ := hx
      induction hm using Submodule.span_induction with
      | mem a ha =>
          obtain ⟨xs, hxs, rfl⟩ := ha
          clear hxs
          refine ⟨xs.length + n, ?_⟩
          induction xs with
          | nil => simpa using hn
          | cons z zs ih =>
              rw [tensorWord, List.map_cons, List.prod_cons]
              simpa [tensorWord, mul_assoc, Nat.add_comm, Nat.add_left_comm, Nat.add_assoc] using
                (ι_mul_mem_higginsFiltration_succ L z ih)
      | zero => exact ⟨m + n, by simp⟩
      | add a b _ _ ha hb =>
          obtain ⟨r, hr⟩ := ha
          obtain ⟨s, hs⟩ := hb
          refine ⟨max r s, ?_⟩
          rw [add_mul]
          exact (higginsFiltration L (max r s)).add_mem
            (higginsFiltration_mono L (Nat.le_max_left _ _) hr)
            (higginsFiltration_mono L (Nat.le_max_right _ _) hs)
      | smul z a _ ha =>
          obtain ⟨r, hr⟩ := ha
          refine ⟨r, ?_⟩
          rw [smul_mul_assoc]
          exact (higginsFiltration L r).smul_mem z hr
  | right_absorb a x _ hx =>
      obtain ⟨m, hm⟩ := exists_mem_tensorDegreeFiltration L a
      obtain ⟨n, hn⟩ := hx
      induction hm using Submodule.span_induction with
      | mem a ha =>
          obtain ⟨xs, hxs, rfl⟩ := ha
          clear hxs
          refine ⟨n + xs.length, ?_⟩
          induction xs using List.reverseRecOn with
          | nil => simpa using hn
          | append_singleton xs z ih =>
              rw [tensorWord_append, tensorWord_singleton]
              simpa [mul_assoc, Nat.add_assoc] using
                (mul_ι_mem_higginsFiltration_succ L z ih)
      | zero => exact ⟨n + m, by simp⟩
      | add a b _ _ ha hb =>
          obtain ⟨r, hr⟩ := ha
          obtain ⟨s, hs⟩ := hb
          refine ⟨max r s, ?_⟩
          rw [mul_add]
          exact (higginsFiltration L (max r s)).add_mem
            (higginsFiltration_mono L (Nat.le_max_left _ _) hr)
            (higginsFiltration_mono L (Nat.le_max_right _ _) hs)
      | smul z a _ ha =>
          obtain ⟨r, hr⟩ := ha
          refine ⟨r, ?_⟩
          rw [mul_smul_comm]
          exact (higginsFiltration L r).smul_mem z hr

/-- Lattice form of exhaustion: `J = ⋃ₙ J(n)`. -/
theorem iSup_higginsFiltration :
    ⨆ n, higginsFiltration L n = (envelopingRelationIdeal L).restrictScalars ℤ := by
  apply le_antisymm
  · exact iSup_le (higginsFiltration_le_envelopingRelationIdeal L)
  · intro t ht
    obtain ⟨n, hn⟩ := exists_higginsFiltration_of_mem_envelopingRelationIdeal L ht
    exact Submodule.mem_iSup_of_mem n hn

/-! ## The associated graded module -/

/-- The copy of `J(n-1)` inside `J(n)`. -/
def previousHigginsFiltration (n : ℕ) : Submodule ℤ (higginsFiltration L n) :=
  (higginsFiltration L (n - 1)).comap (higginsFiltration L n).subtype

@[simp]
theorem mem_previousHigginsFiltration {n : ℕ} (t : higginsFiltration L n) :
    t ∈ previousHigginsFiltration L n ↔
      (t : T) ∈ higginsFiltration L (n - 1) :=
  Iff.rfl

/-- The degree-`n` associated graded piece `J(n)/J(n-1)`. -/
abbrev HigginsGradedPiece (n : ℕ) :=
  higginsFiltration L n ⧸ previousHigginsFiltration L n

/-- Higgins's associated graded module `A = ⨁ₙ J(n)/J(n-1)`. -/
abbrev HigginsAssociatedGraded :=
  ⨁ (n : ℕ), HigginsGradedPiece L n

/-- Left multiplication by a generator, before passing to the successive quotient. -/
def leftGeneratorFiltrationMap (n : ℕ) (z : L) :
    higginsFiltration L n →ₗ[ℤ] higginsFiltration L (n + 1) where
  toFun t := ⟨TensorAlgebra.ι ℤ z * (t : T),
    ι_mul_mem_higginsFiltration_succ L z t.property⟩
  map_add' x y := by ext; simp [mul_add]
  map_smul' a x := by
    ext
    change TensorAlgebra.ι ℤ z * (algebraMap ℤ T a * (x : T)) =
      algebraMap ℤ T a * (TensorAlgebra.ι ℤ z * (x : T))
    rw [← mul_assoc, (Algebra.commutes a _).symm, mul_assoc]

/-- Right multiplication by a generator, before passing to the successive quotient. -/
def rightGeneratorFiltrationMap (n : ℕ) (z : L) :
    higginsFiltration L n →ₗ[ℤ] higginsFiltration L (n + 1) where
  toFun t := ⟨(t : T) * TensorAlgebra.ι ℤ z,
    mul_ι_mem_higginsFiltration_succ L z t.property⟩
  map_add' x y := by ext; simp [add_mul]
  map_smul' a x := by
    ext
    change (algebraMap ℤ T a * (x : T)) * TensorAlgebra.ι ℤ z =
      algebraMap ℤ T a * ((x : T) * TensorAlgebra.ι ℤ z)
    rw [mul_assoc]

theorem leftGeneratorFiltrationMap_previous_le_ker (n : ℕ) (z : L) :
    previousHigginsFiltration L n ≤ LinearMap.ker
      ((Submodule.mkQ (previousHigginsFiltration L (n + 1))).comp
        (leftGeneratorFiltrationMap L n z)) := by
  intro t ht
  rw [LinearMap.mem_ker]
  apply (Submodule.Quotient.mk_eq_zero _).mpr
  change TensorAlgebra.ι ℤ z * (t : T) ∈ higginsFiltration L ((n + 1) - 1)
  cases n with
  | zero =>
      have ht0 : (t : T) = 0 := by
        have : (t : T) ∈ higginsFiltration L 0 := t.property
        simpa using this
      rw [ht0, mul_zero]
      exact (higginsFiltration L 0).zero_mem
  | succ n =>
      simpa using ι_mul_mem_higginsFiltration_succ L z
        (show (t : T) ∈ higginsFiltration L n by simpa using ht)

theorem rightGeneratorFiltrationMap_previous_le_ker (n : ℕ) (z : L) :
    previousHigginsFiltration L n ≤ LinearMap.ker
      ((Submodule.mkQ (previousHigginsFiltration L (n + 1))).comp
        (rightGeneratorFiltrationMap L n z)) := by
  intro t ht
  rw [LinearMap.mem_ker]
  apply (Submodule.Quotient.mk_eq_zero _).mpr
  change (t : T) * TensorAlgebra.ι ℤ z ∈ higginsFiltration L ((n + 1) - 1)
  cases n with
  | zero =>
      have ht0 : (t : T) = 0 := by
        have : (t : T) ∈ higginsFiltration L 0 := t.property
        simpa using this
      rw [ht0, zero_mul]
      exact (higginsFiltration L 0).zero_mem
  | succ n =>
      simpa using mul_ι_mem_higginsFiltration_succ L z
        (show (t : T) ∈ higginsFiltration L n by simpa using ht)

/-- The degree-shifting map `[t] ↦ [z t]` on associated graded pieces. -/
def leftGeneratorGradedPiece (n : ℕ) (z : L) :
    HigginsGradedPiece L n →ₗ[ℤ] HigginsGradedPiece L (n + 1) :=
  (previousHigginsFiltration L n).liftQ
    ((Submodule.mkQ (previousHigginsFiltration L (n + 1))).comp
      (leftGeneratorFiltrationMap L n z))
    (leftGeneratorFiltrationMap_previous_le_ker L n z)

/-- The degree-shifting map `[t] ↦ [t z]` on associated graded pieces. -/
def rightGeneratorGradedPiece (n : ℕ) (z : L) :
    HigginsGradedPiece L n →ₗ[ℤ] HigginsGradedPiece L (n + 1) :=
  (previousHigginsFiltration L n).liftQ
    ((Submodule.mkQ (previousHigginsFiltration L (n + 1))).comp
      (rightGeneratorFiltrationMap L n z))
    (rightGeneratorFiltrationMap_previous_le_ker L n z)

@[simp]
theorem leftGeneratorGradedPiece_mk (n : ℕ) (z : L)
    (t : higginsFiltration L n) :
    leftGeneratorGradedPiece L n z (Submodule.Quotient.mk t) =
      Submodule.Quotient.mk (leftGeneratorFiltrationMap L n z t) :=
  rfl

@[simp]
theorem rightGeneratorGradedPiece_mk (n : ℕ) (z : L)
    (t : higginsFiltration L n) :
    rightGeneratorGradedPiece L n z (Submodule.Quotient.mk t) =
      Submodule.Quotient.mk (rightGeneratorFiltrationMap L n z t) :=
  rfl

/-- Left multiplication by `z` on the whole associated graded module. -/
def leftGeneratorAssociatedEnd (z : L) :
    Module.End ℤ (HigginsAssociatedGraded L) :=
  DirectSum.toModule ℤ ℕ (HigginsAssociatedGraded L) fun n ↦
    (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
      (leftGeneratorGradedPiece L n z)

/-- Right multiplication by `z` on the whole associated graded module. -/
def rightGeneratorAssociatedEnd (z : L) :
    Module.End ℤ (HigginsAssociatedGraded L) :=
  DirectSum.toModule ℤ ℕ (HigginsAssociatedGraded L) fun n ↦
    (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
      (rightGeneratorGradedPiece L n z)

@[simp]
theorem leftGeneratorAssociatedEnd_lof (n : ℕ) (z : L)
    (t : HigginsGradedPiece L n) :
    leftGeneratorAssociatedEnd L z
        (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n t) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)
        (leftGeneratorGradedPiece L n z t) := by
  unfold leftGeneratorAssociatedEnd
  exact DirectSum.toModule_lof
    (M := HigginsGradedPiece L)
    (φ := fun n ↦
      (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
        (leftGeneratorGradedPiece L n z)) ℤ n t

@[simp]
theorem rightGeneratorAssociatedEnd_lof (n : ℕ) (z : L)
    (t : HigginsGradedPiece L n) :
    rightGeneratorAssociatedEnd L z
        (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n t) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)
        (rightGeneratorGradedPiece L n z t) := by
  unfold rightGeneratorAssociatedEnd
  exact DirectSum.toModule_lof
    (M := HigginsGradedPiece L)
    (φ := fun n ↦
      (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
        (rightGeneratorGradedPiece L n z)) ℤ n t

theorem leftGeneratorGradedPiece_add (n : ℕ) (x y : L) :
    leftGeneratorGradedPiece L n (x + y) =
      leftGeneratorGradedPiece L n x + leftGeneratorGradedPiece L n y := by
  have hmodule : (inferInstance : Module ℤ (HigginsGradedPiece L (n + 1))) =
      AddCommGroup.toIntModule (HigginsGradedPiece L (n + 1)) := Subsingleton.elim _ _
  cases hmodule
  apply LinearMap.ext
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ t =>
      simp only [leftGeneratorGradedPiece_mk, LinearMap.add_apply]
      rw [← Submodule.Quotient.mk_add]
      apply congrArg Submodule.Quotient.mk
      apply Subtype.ext
      simp [leftGeneratorFiltrationMap, add_mul]

theorem leftGeneratorGradedPiece_zero (n : ℕ) :
    leftGeneratorGradedPiece L n 0 = 0 := by
  apply LinearMap.ext
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ t =>
      simp [leftGeneratorGradedPiece_mk, leftGeneratorFiltrationMap]

theorem rightGeneratorGradedPiece_add (n : ℕ) (x y : L) :
    rightGeneratorGradedPiece L n (x + y) =
      rightGeneratorGradedPiece L n x + rightGeneratorGradedPiece L n y := by
  have hmodule : (inferInstance : Module ℤ (HigginsGradedPiece L (n + 1))) =
      AddCommGroup.toIntModule (HigginsGradedPiece L (n + 1)) := Subsingleton.elim _ _
  cases hmodule
  apply LinearMap.ext
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ t =>
      simp only [rightGeneratorGradedPiece_mk, LinearMap.add_apply]
      rw [← Submodule.Quotient.mk_add]
      apply congrArg Submodule.Quotient.mk
      apply Subtype.ext
      simp [rightGeneratorFiltrationMap, mul_add]

theorem rightGeneratorGradedPiece_zero (n : ℕ) :
    rightGeneratorGradedPiece L n 0 = 0 := by
  apply LinearMap.ext
  intro q
  induction q using Submodule.Quotient.induction_on with
  | _ t =>
      simp [rightGeneratorGradedPiece_mk, rightGeneratorFiltrationMap]

theorem directSumToModule_add
    (f g : ∀ n, HigginsGradedPiece L n →ₗ[ℤ] HigginsAssociatedGraded L) :
    DirectSum.toModule ℤ ℕ (HigginsAssociatedGraded L) (fun n ↦ f n + g n) =
      DirectSum.toModule ℤ ℕ (HigginsAssociatedGraded L) f +
        DirectSum.toModule ℤ ℕ (HigginsAssociatedGraded L) g := by
  apply DirectSum.linearMap_ext
  intro n
  apply LinearMap.ext
  intro q
  simp

theorem directSumToModule_zero :
    DirectSum.toModule ℤ ℕ (HigginsAssociatedGraded L)
        (fun n ↦ (0 : HigginsGradedPiece L n →ₗ[ℤ] HigginsAssociatedGraded L)) = 0 := by
  apply DirectSum.linearMap_ext
  intro n
  apply LinearMap.ext
  intro q
  simp

theorem leftGeneratorAssociatedEnd_add (x y : L) :
    leftGeneratorAssociatedEnd L (x + y) =
      leftGeneratorAssociatedEnd L x + leftGeneratorAssociatedEnd L y := by
  unfold leftGeneratorAssociatedEnd
  rw [show (fun n ↦
      (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
        (leftGeneratorGradedPiece L n (x + y))) =
      (fun n ↦
        (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
            (leftGeneratorGradedPiece L n x) +
          (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
            (leftGeneratorGradedPiece L n y)) by
    funext n
    rw [leftGeneratorGradedPiece_add]
    exact LinearMap.comp_add _ _ _]
  exact directSumToModule_add L _ _

theorem leftGeneratorAssociatedEnd_zero :
    leftGeneratorAssociatedEnd L 0 = 0 := by
  unfold leftGeneratorAssociatedEnd
  rw [show (fun n ↦
      (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
        (leftGeneratorGradedPiece L n 0)) =
      (fun n ↦ (0 : HigginsGradedPiece L n →ₗ[ℤ] HigginsAssociatedGraded L)) by
    funext n
    rw [leftGeneratorGradedPiece_zero]
    exact LinearMap.comp_zero _]
  exact directSumToModule_zero L

theorem rightGeneratorAssociatedEnd_add (x y : L) :
    rightGeneratorAssociatedEnd L (x + y) =
      rightGeneratorAssociatedEnd L x + rightGeneratorAssociatedEnd L y := by
  unfold rightGeneratorAssociatedEnd
  rw [show (fun n ↦
      (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
        (rightGeneratorGradedPiece L n (x + y))) =
      (fun n ↦
        (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
            (rightGeneratorGradedPiece L n x) +
          (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
            (rightGeneratorGradedPiece L n y)) by
    funext n
    rw [rightGeneratorGradedPiece_add]
    exact LinearMap.comp_add _ _ _]
  exact directSumToModule_add L _ _

theorem rightGeneratorAssociatedEnd_zero :
    rightGeneratorAssociatedEnd L 0 = 0 := by
  unfold rightGeneratorAssociatedEnd
  rw [show (fun n ↦
      (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1)).comp
        (rightGeneratorGradedPiece L n 0)) =
      (fun n ↦ (0 : HigginsGradedPiece L n →ₗ[ℤ] HigginsAssociatedGraded L)) by
    funext n
    rw [rightGeneratorGradedPiece_zero]
    exact LinearMap.comp_zero _]
  exact directSumToModule_zero L

/-- Left multiplication on the associated graded module depends linearly on the generator. -/
def leftGeneratorAssociated :
    L →ₗ[ℤ] Module.End ℤ (HigginsAssociatedGraded L) :=
  ({ toFun := leftGeneratorAssociatedEnd L
     map_zero' := leftGeneratorAssociatedEnd_zero L
     map_add' := leftGeneratorAssociatedEnd_add L } :
    L →+ Module.End ℤ (HigginsAssociatedGraded L)).toIntLinearMap

/-- Right multiplication on the associated graded module depends linearly on the generator. -/
def rightGeneratorAssociated :
    L →ₗ[ℤ] Module.End ℤ (HigginsAssociatedGraded L) :=
  ({ toFun := rightGeneratorAssociatedEnd L
     map_zero' := rightGeneratorAssociatedEnd_zero L
     map_add' := rightGeneratorAssociatedEnd_add L } :
    L →+ Module.End ℤ (HigginsAssociatedGraded L)).toIntLinearMap

/-! ## Tensor-algebra actions -/

/-- The algebra homomorphism implementing left multiplication on the associated graded module. -/
def leftTensorAction :
    T →ₐ[ℤ] Module.End ℤ (HigginsAssociatedGraded L) :=
  TensorAlgebra.lift ℤ (leftGeneratorAssociated L)

/-- Right multiplication, regarded as a map into the opposite endomorphism ring. -/
def rightTensorActionOp :
    T →ₐ[ℤ] (Module.End ℤ (HigginsAssociatedGraded L))ᵐᵒᵖ :=
  TensorAlgebra.lift ℤ
    ((MulOpposite.opLinearEquiv ℤ).toLinearMap.comp (rightGeneratorAssociated L))

/-- The ring homomorphism from `Tᵐᵒᵖ` implementing the right tensor-algebra action. -/
def rightTensorAction :
    Tᵐᵒᵖ →+* Module.End ℤ (HigginsAssociatedGraded L) :=
  (RingEquiv.opOp (Module.End ℤ (HigginsAssociatedGraded L))).symm.toRingHom.comp
    (RingHom.op (rightTensorActionOp L).toRingHom)

/-- The left `T(L)`-module structure on Higgins's associated graded module. -/
@[implicit_reducible] noncomputable def higginsAssociatedModule :
    Module T (HigginsAssociatedGraded L) :=
  Module.compHom (HigginsAssociatedGraded L) (leftTensorAction L).toRingHom

/-- The commuting right `T(L)`-module structure, expressed as a module over `T(L)ᵐᵒᵖ`. -/
@[implicit_reducible] noncomputable def higginsAssociatedModuleOpposite :
    Module Tᵐᵒᵖ (HigginsAssociatedGraded L) :=
  Module.compHom (HigginsAssociatedGraded L) (rightTensorAction L)

@[simp]
theorem leftTensorAction_ι (x : L) :
    leftTensorAction L (TensorAlgebra.ι ℤ x) = leftGeneratorAssociatedEnd L x := by
  simp [leftTensorAction, leftGeneratorAssociated]

@[simp]
theorem rightTensorAction_op_ι (x : L) :
    rightTensorAction L (MulOpposite.op (TensorAlgebra.ι ℤ x)) =
      rightGeneratorAssociatedEnd L x := by
  simp [rightTensorAction, rightTensorActionOp, rightGeneratorAssociated]

/-- Left and right multiplication by canonical generators commute as linear maps. -/
theorem left_right_generator_comp (x y : L) :
    (leftGeneratorAssociatedEnd L x).comp (rightGeneratorAssociatedEnd L y) =
      (rightGeneratorAssociatedEnd L y).comp (leftGeneratorAssociatedEnd L x) := by
  apply LinearMap.ext
  intro a
  induction a using DirectSum.induction_on with
  | zero => simp
  | add a b ha hb => simpa using congrArg₂ (· + ·) ha hb
  | of n q =>
      induction q using Submodule.Quotient.induction_on with
      | _ t =>
          change leftGeneratorAssociatedEnd L x
              (rightGeneratorAssociatedEnd L y
                (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n
                  (Submodule.Quotient.mk t))) =
            rightGeneratorAssociatedEnd L y
              (leftGeneratorAssociatedEnd L x
                (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n
                  (Submodule.Quotient.mk t)))
          simp only [rightGeneratorAssociatedEnd_lof, leftGeneratorAssociatedEnd_lof,
            rightGeneratorGradedPiece_mk, leftGeneratorGradedPiece_mk]
          apply congrArg (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + 1 + 1))
          apply congrArg Submodule.Quotient.mk
          apply Subtype.ext
          simp [leftGeneratorFiltrationMap, rightGeneratorFiltrationMap, mul_assoc]

/-- Left and right multiplication by canonical generators commute in the endomorphism ring. -/
theorem left_right_generator_commute (x y : L) :
    Commute (leftGeneratorAssociatedEnd L x) (rightGeneratorAssociatedEnd L y) := by
  exact left_right_generator_comp L x y

theorem left_generator_rightTensorActionOp_commute (x : L) (b : T) :
    Commute (leftGeneratorAssociatedEnd L x) ((rightTensorActionOp L b).unop) := by
  induction b using TensorAlgebra.induction with
  | algebraMap z =>
      simp [rightTensorActionOp]
  | ι y =>
      simpa [rightTensorActionOp, rightGeneratorAssociated] using
        left_right_generator_commute L x y
  | mul a b ha hb =>
      simpa only [map_mul, MulOpposite.unop_mul] using hb.mul_right ha
  | add a b ha hb =>
      simpa only [map_add, MulOpposite.unop_add] using ha.add_right hb

theorem leftTensorAction_rightTensorActionOp_commute (a b : T) :
    Commute (leftTensorAction L a) ((rightTensorActionOp L b).unop) := by
  induction a using TensorAlgebra.induction with
  | algebraMap z =>
      simp [leftTensorAction]
  | ι x =>
      simpa using left_generator_rightTensorActionOp_commute L x b
  | mul a c ha hc =>
      simpa only [map_mul] using ha.mul_left hc
  | add a c ha hc =>
      simpa only [map_add] using ha.add_left hc

@[simp]
theorem rightTensorAction_op (b : T) :
    rightTensorAction L (MulOpposite.op b) = (rightTensorActionOp L b).unop := by
  rfl

/-- Arbitrary left and right tensor-algebra elements act by commuting endomorphisms. -/
theorem leftTensorAction_rightTensorAction_commute (a : T) (b : Tᵐᵒᵖ) :
    Commute (leftTensorAction L a) (rightTensorAction L b) := by
  induction b using MulOpposite.rec' with
  | _ b => simpa using leftTensorAction_rightTensorActionOp_commute L a b

/-- The left and right tensor-algebra module structures on the associated graded commute. -/
@[implicit_reducible] noncomputable def higginsAssociatedSMulCommClass :
    letI := higginsAssociatedModule L
    letI := higginsAssociatedModuleOpposite L
    SMulCommClass T Tᵐᵒᵖ (HigginsAssociatedGraded L) := by
  letI := higginsAssociatedModule L
  letI := higginsAssociatedModuleOpposite L
  constructor
  intro a b v
  have h := leftTensorAction_rightTensorAction_commute L a b
  exact congrArg (fun f : Module.End ℤ (HigginsAssociatedGraded L) ↦ f v) h.eq

/-! ## The defining-relation class -/

/-- The defining relation, regarded as an element of `J(2)`. -/
def envelopingRelationFiltrationElement (x y : L) : higginsFiltration L 2 :=
  ⟨envelopingRelation L x y, envelopingRelation_mem_higginsFiltration_two L x y⟩

/-- The class of `xy-yx-[x,y]` in the degree-two part of the associated graded. -/
def higginsRelationClassValue (x y : L) : HigginsAssociatedGraded L :=
  DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 2
    (Submodule.Quotient.mk (envelopingRelationFiltrationElement L x y))

theorem envelopingRelation_add_left (x₁ x₂ y : L) :
    envelopingRelation L (x₁ + x₂) y =
      envelopingRelation L x₁ y + envelopingRelation L x₂ y := by
  unfold envelopingRelation
  have hlie : ⁅x₁ + x₂, y⁆ = ⁅x₁, y⁆ + ⁅x₂, y⁆ :=
    LieRing.add_lie x₁ x₂ y
  rw [hlie]
  simp [add_mul, mul_add]
  noncomm_ring

theorem envelopingRelation_add_right (x y₁ y₂ : L) :
    envelopingRelation L x (y₁ + y₂) =
      envelopingRelation L x y₁ + envelopingRelation L x y₂ := by
  unfold envelopingRelation
  have hlie : ⁅x, y₁ + y₂⁆ = ⁅x, y₁⁆ + ⁅x, y₂⁆ :=
    LieRing.lie_add x y₁ y₂
  rw [hlie]
  simp [add_mul, mul_add]
  noncomm_ring

theorem higginsRelationClassValue_zero_left (y : L) :
    higginsRelationClassValue L 0 y = 0 := by
  have hr : envelopingRelation L 0 y = 0 := by
    unfold envelopingRelation
    have hz : ⁅(0 : L), y⁆ = 0 := by
      have h := LieRing.add_lie (0 : L) 0 y
      apply add_left_cancel (a := ⁅(0 : L), y⁆)
      simpa only [zero_add, add_zero] using h.symm
    rw [hz]
    simp
  have he : envelopingRelationFiltrationElement L 0 y = 0 := by
    apply Subtype.ext
    exact hr
  simp [higginsRelationClassValue, he]

theorem higginsRelationClassValue_add_left (x₁ x₂ y : L) :
    higginsRelationClassValue L (x₁ + x₂) y =
      higginsRelationClassValue L x₁ y + higginsRelationClassValue L x₂ y := by
  unfold higginsRelationClassValue
  rw [← map_add]
  apply congrArg (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 2)
  rw [← Submodule.Quotient.mk_add]
  apply congrArg Submodule.Quotient.mk
  apply Subtype.ext
  exact envelopingRelation_add_left L x₁ x₂ y

theorem higginsRelationClassValue_zero_right (x : L) :
    higginsRelationClassValue L x 0 = 0 := by
  have hr : envelopingRelation L x 0 = 0 := by
    unfold envelopingRelation
    have hz : ⁅x, (0 : L)⁆ = 0 := by
      have h := LieRing.lie_add x (0 : L) 0
      apply add_left_cancel (a := ⁅x, (0 : L)⁆)
      simpa only [zero_add, add_zero] using h.symm
    rw [hz]
    simp
  have he : envelopingRelationFiltrationElement L x 0 = 0 := by
    apply Subtype.ext
    exact hr
  simp [higginsRelationClassValue, he]

theorem higginsRelationClassValue_add_right (x y₁ y₂ : L) :
    higginsRelationClassValue L x (y₁ + y₂) =
      higginsRelationClassValue L x y₁ + higginsRelationClassValue L x y₂ := by
  unfold higginsRelationClassValue
  rw [← map_add]
  apply congrArg (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 2)
  rw [← Submodule.Quotient.mk_add]
  apply congrArg Submodule.Quotient.mk
  apply Subtype.ext
  exact envelopingRelation_add_right L x y₁ y₂

/-- The integral bilinear defining-relation class used for Higgins's Lie structure. -/
def higginsRelationClass :
    L →ₗ[ℤ] L →ₗ[ℤ] HigginsAssociatedGraded L :=
  ({ toFun := fun x ↦
      ({ toFun := higginsRelationClassValue L x
         map_zero' := higginsRelationClassValue_zero_right L x
         map_add' := higginsRelationClassValue_add_right L x } :
        L →+ HigginsAssociatedGraded L).toIntLinearMap
     map_zero' := by
       apply LinearMap.ext
       intro y
       exact higginsRelationClassValue_zero_left L y
     map_add' := by
       intro x₁ x₂
       apply LinearMap.ext
       intro y
       exact higginsRelationClassValue_add_left L x₁ x₂ y } :
    L →+ (L →ₗ[ℤ] HigginsAssociatedGraded L)).toIntLinearMap

@[simp]
theorem higginsRelationClass_apply (x y : L) :
    higginsRelationClass L x y = higginsRelationClassValue L x y :=
  rfl

theorem higginsRelationClass_lie_self (x : L) :
    higginsRelationClass L x x = 0 := by
  rw [higginsRelationClass_apply]
  have hr : envelopingRelation L x x = 0 := by
    unfold envelopingRelation
    have hlie : ⁅x, x⁆ = 0 := LieRing.lie_self x
    rw [hlie]
    simp
  have he : envelopingRelationFiltrationElement L x x = 0 := by
    apply Subtype.ext
    exact hr
  simp [higginsRelationClassValue, he]

theorem left_ι_smul_higginsRelationClass (z x y : L) :
    letI := higginsAssociatedModule L
    TensorAlgebra.ι ℤ z • higginsRelationClass L x y =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 3
        (Submodule.Quotient.mk
          (leftGeneratorFiltrationMap L 2 z
            (envelopingRelationFiltrationElement L x y))) := by
  letI := higginsAssociatedModule L
  change leftTensorAction L (TensorAlgebra.ι ℤ z)
      (higginsRelationClassValue L x y) = _
  rw [leftTensorAction_ι]
  simp [higginsRelationClassValue]

theorem right_ι_smul_higginsRelationClass (z x y : L) :
    letI := higginsAssociatedModuleOpposite L
    MulOpposite.op (TensorAlgebra.ι ℤ z) • higginsRelationClass L x y =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 3
        (Submodule.Quotient.mk
          (rightGeneratorFiltrationMap L 2 z
            (envelopingRelationFiltrationElement L x y))) := by
  letI := higginsAssociatedModuleOpposite L
  change rightTensorAction L (MulOpposite.op (TensorAlgebra.ι ℤ z))
      (higginsRelationClassValue L x y) = _
  rw [rightTensorAction_op_ι]
  simp [higginsRelationClassValue]

/-- The tensor representative of Higgins's cyclic identity (L3). -/
def higginsJacobiTensor (x y z : L) : T :=
  (envelopingRelation L x y * TensorAlgebra.ι ℤ z -
      TensorAlgebra.ι ℤ z * envelopingRelation L x y) +
    (envelopingRelation L y z * TensorAlgebra.ι ℤ x -
      TensorAlgebra.ι ℤ x * envelopingRelation L y z) +
    (envelopingRelation L z x * TensorAlgebra.ι ℤ y -
      TensorAlgebra.ι ℤ y * envelopingRelation L z x)

theorem cyclic_nested_lie_eq_zero (x y z : L) :
    ⁅⁅x, y⁆, z⁆ + ⁅⁅y, z⁆, x⁆ + ⁅⁅z, x⁆, y⁆ = 0 := by
  rw [← lie_skew ⁅x, y⁆ z, ← lie_skew ⁅y, z⁆ x, ← lie_skew ⁅z, x⁆ y]
  have h := lie_jacobi x y z
  calc
    (-⁅z, ⁅x, y⁆⁆ + -⁅x, ⁅y, z⁆⁆) + -⁅y, ⁅z, x⁆⁆ =
        -(⁅x, ⁅y, z⁆⁆ + ⁅y, ⁅z, x⁆⁆ + ⁅z, ⁅x, y⁆⁆) := by abel
    _ = 0 := by rw [h]; simp

/-- The cyclic tensor is, up to sign, a sum of degree-two defining relations. -/
theorem higginsJacobiTensor_eq (x y z : L) :
    higginsJacobiTensor L x y z =
      -(envelopingRelation L ⁅x, y⁆ z +
        envelopingRelation L ⁅y, z⁆ x +
        envelopingRelation L ⁅z, x⁆ y) := by
  have hj := congrArg (TensorAlgebra.ι ℤ) (cyclic_nested_lie_eq_zero L x y z)
  simp only [map_add, map_zero] at hj
  have hj' : (TensorAlgebra.ι ℤ) ⁅⁅z, x⁆, y⁆ =
      -((TensorAlgebra.ι ℤ) ⁅⁅x, y⁆, z⁆ +
        (TensorAlgebra.ι ℤ) ⁅⁅y, z⁆, x⁆) := by
    have h := congrArg
      (fun w : T ↦ w - ((TensorAlgebra.ι ℤ) ⁅⁅x, y⁆, z⁆ +
        (TensorAlgebra.ι ℤ) ⁅⁅y, z⁆, x⁆)) hj
    simpa [add_comm, add_left_comm, add_assoc] using h
  unfold higginsJacobiTensor envelopingRelation
  rw [hj']
  noncomm_ring

theorem higginsJacobiTensor_mem_higginsFiltration_two (x y z : L) :
    higginsJacobiTensor L x y z ∈ higginsFiltration L 2 := by
  rw [higginsJacobiTensor_eq]
  exact (higginsFiltration L 2).neg_mem
    ((higginsFiltration L 2).add_mem
      ((higginsFiltration L 2).add_mem
        (envelopingRelation_mem_higginsFiltration_two L ⁅x, y⁆ z)
        (envelopingRelation_mem_higginsFiltration_two L ⁅y, z⁆ x))
      (envelopingRelation_mem_higginsFiltration_two L ⁅z, x⁆ y))

/-- The cyclic tensor, regarded as an element of `J(3)`. -/
def higginsJacobiFiltrationElement (x y z : L) : higginsFiltration L 3 :=
  ⟨higginsJacobiTensor L x y z,
    higginsFiltration_mono L (by omega) (higginsJacobiTensor_mem_higginsFiltration_two L x y z)⟩

theorem higginsJacobiFiltrationElement_mem_previous (x y z : L) :
    higginsJacobiFiltrationElement L x y z ∈ previousHigginsFiltration L 3 := by
  exact higginsJacobiTensor_mem_higginsFiltration_two L x y z

theorem higginsRelationClass_jacobi (x y z : L) :
    letI := higginsAssociatedModule L
    letI := higginsAssociatedModuleOpposite L
    (MulOpposite.op (TensorAlgebra.ι ℤ z) • higginsRelationClass L x y -
        TensorAlgebra.ι ℤ z • higginsRelationClass L x y) +
      (MulOpposite.op (TensorAlgebra.ι ℤ x) • higginsRelationClass L y z -
        TensorAlgebra.ι ℤ x • higginsRelationClass L y z) +
      (MulOpposite.op (TensorAlgebra.ι ℤ y) • higginsRelationClass L z x -
        TensorAlgebra.ι ℤ y • higginsRelationClass L z x) = 0 := by
  letI := higginsAssociatedModule L
  letI := higginsAssociatedModuleOpposite L
  rw [right_ι_smul_higginsRelationClass, left_ι_smul_higginsRelationClass,
    right_ι_smul_higginsRelationClass, left_ι_smul_higginsRelationClass,
    right_ι_smul_higginsRelationClass, left_ι_smul_higginsRelationClass]
  simp only [← map_sub, ← map_add]
  simp only [← Submodule.Quotient.mk_sub, ← Submodule.Quotient.mk_add]
  have he :
      (rightGeneratorFiltrationMap L 2 z (envelopingRelationFiltrationElement L x y) -
          leftGeneratorFiltrationMap L 2 z (envelopingRelationFiltrationElement L x y)) +
        (rightGeneratorFiltrationMap L 2 x (envelopingRelationFiltrationElement L y z) -
          leftGeneratorFiltrationMap L 2 x (envelopingRelationFiltrationElement L y z)) +
        (rightGeneratorFiltrationMap L 2 y (envelopingRelationFiltrationElement L z x) -
          leftGeneratorFiltrationMap L 2 y (envelopingRelationFiltrationElement L z x)) =
        higginsJacobiFiltrationElement L x y z := by
    apply Subtype.ext
    rfl
  rw [he]
  have hq : Submodule.Quotient.mk (higginsJacobiFiltrationElement L x y z) = 0 :=
    (Submodule.Quotient.mk_eq_zero (previousHigginsFiltration L 3)).mpr
      (higginsJacobiFiltrationElement_mem_previous L x y z)
  rw [hq, map_zero]

/-! ## Tensor-word actions, used for the filtered balance identity -/

theorem lof_quotient_mk_eq_of_coe_eq {m n : ℕ}
    (a : higginsFiltration L m) (b : higginsFiltration L n)
    (hindex : m = n) (hvalue : (a : T) = (b : T)) :
    DirectSum.lof ℤ ℕ (HigginsGradedPiece L) m (Submodule.Quotient.mk a) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n (Submodule.Quotient.mk b) := by
  subst n
  apply congrArg (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) m)
  apply congrArg Submodule.Quotient.mk
  apply Subtype.ext
  exact hvalue

theorem lof_quotient_mk_sub_eq_of_coe_sub_eq {m n k : ℕ}
    (a : higginsFiltration L m) (b : higginsFiltration L n)
    (c : higginsFiltration L k) (hm : m = k) (hn : n = k)
    (hvalue : (a : T) - (b : T) = (c : T)) :
    DirectSum.lof ℤ ℕ (HigginsGradedPiece L) m (Submodule.Quotient.mk a) -
        DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n (Submodule.Quotient.mk b) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) k (Submodule.Quotient.mk c) := by
  subst m
  subst n
  rw [← map_sub, ← Submodule.Quotient.mk_sub]
  apply congrArg (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) k)
  apply congrArg Submodule.Quotient.mk
  apply Subtype.ext
  exact hvalue

def leftTensorWordFiltrationElement (xs : List L) (n : ℕ)
    (t : higginsFiltration L n) : higginsFiltration L (n + xs.length) :=
  ⟨tensorWord L xs * (t : T), by
    induction xs with
    | nil => simpa using t.property
    | cons z zs ih =>
        rw [tensorWord, List.map_cons, List.prod_cons]
        rw [mul_assoc]
        change TensorAlgebra.ι ℤ z * (tensorWord L zs * (t : T)) ∈
          higginsFiltration L (n + (z :: zs).length)
        simpa [Nat.add_assoc] using ι_mul_mem_higginsFiltration_succ L z ih⟩

def rightTensorWordFiltrationElement (xs : List L) (n : ℕ)
    (t : higginsFiltration L n) : higginsFiltration L (n + xs.length) :=
  ⟨(t : T) * tensorWord L xs, by
    induction xs using List.reverseRecOn with
    | nil => simpa using t.property
    | append_singleton ys z ih =>
        rw [tensorWord_append, tensorWord_singleton, ← mul_assoc]
        simpa [Nat.add_assoc] using
          mul_ι_mem_higginsFiltration_succ L z ih⟩

theorem left_tensorWord_smul_lof_mk (xs : List L) (n : ℕ)
    (t : higginsFiltration L n) :
    letI := higginsAssociatedModule L
    tensorWord L xs •
        DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n (Submodule.Quotient.mk t) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + xs.length)
        (Submodule.Quotient.mk (leftTensorWordFiltrationElement L xs n t)) := by
  letI := higginsAssociatedModule L
  induction xs with
  | nil =>
      simp [tensorWord, leftTensorWordFiltrationElement]
      rfl
  | cons z zs ih =>
      rw [tensorWord, List.map_cons, List.prod_cons, mul_smul]
      change TensorAlgebra.ι ℤ z • tensorWord L zs • _ = _
      rw [ih]
      change leftTensorAction L (TensorAlgebra.ι ℤ z) _ = _
      rw [leftTensorAction_ι]
      rw [leftGeneratorAssociatedEnd_lof, leftGeneratorGradedPiece_mk]
      apply congrArg (DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + (z :: zs).length))
      apply congrArg Submodule.Quotient.mk
      apply Subtype.ext
      simp [leftTensorWordFiltrationElement, leftGeneratorFiltrationMap, tensorWord, mul_assoc]

theorem right_tensorWord_smul_lof_mk (xs : List L) (n : ℕ)
    (t : higginsFiltration L n) :
    letI := higginsAssociatedModuleOpposite L
    MulOpposite.op (tensorWord L xs) •
        DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n (Submodule.Quotient.mk t) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + xs.length)
        (Submodule.Quotient.mk (rightTensorWordFiltrationElement L xs n t)) := by
  letI := higginsAssociatedModuleOpposite L
  induction xs using List.reverseRecOn generalizing n with
  | nil =>
      simp [tensorWord, rightTensorWordFiltrationElement]
      rfl
  | append_singleton ys z ih =>
      rw [tensorWord_append, tensorWord_singleton, MulOpposite.op_mul, mul_smul]
      rw [ih (n := n) t]
      change rightTensorAction L (MulOpposite.op (TensorAlgebra.ι ℤ z)) _ = _
      rw [rightTensorAction_op_ι, rightGeneratorAssociatedEnd_lof,
        rightGeneratorGradedPiece_mk]
      apply lof_quotient_mk_eq_of_coe_eq L
      · simp
        omega
      · simp [rightTensorWordFiltrationElement, rightGeneratorFiltrationMap,
          tensorWord_append, mul_assoc]

theorem right_tensorWords_smul_lof_mk (xs ys : List L) (n : ℕ)
    (t : higginsFiltration L n) :
    letI := higginsAssociatedModuleOpposite L
    MulOpposite.op (tensorWord L ys) •
        (MulOpposite.op (tensorWord L xs) •
          DirectSum.lof ℤ ℕ (HigginsGradedPiece L) n (Submodule.Quotient.mk t)) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (n + (xs ++ ys).length)
        (Submodule.Quotient.mk
          (rightTensorWordFiltrationElement L (xs ++ ys) n t)) := by
  letI := higginsAssociatedModuleOpposite L
  rw [← mul_smul, ← MulOpposite.op_mul, ← tensorWord_append]
  exact right_tensorWord_smul_lof_mk L (xs ++ ys) n t

/-! ## The filtered balance identity (L2) -/

/-- The tensor whose top filtered component is Higgins's balance identity. -/
def higginsBalanceTensor (xs : List L) (x y u v : L) : T :=
  envelopingRelation L x y * tensorWord L xs *
      ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ -
    ⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * tensorWord L xs *
      envelopingRelation L u v

/-- Expanding the two commutators cancels the product of defining relations. -/
theorem higginsBalanceTensor_eq (xs : List L) (x y u v : L) :
    higginsBalanceTensor L xs x y u v =
      envelopingRelation L x y * tensorWord L xs * TensorAlgebra.ι ℤ ⁅u, v⁆ -
        TensorAlgebra.ι ℤ ⁅x, y⁆ * tensorWord L xs * envelopingRelation L u v := by
  unfold higginsBalanceTensor envelopingRelation
  simp only [LieRing.of_associative_ring_bracket]
  noncomm_ring

theorem higginsBalanceTensor_mem_lower (xs : List L) (x y u v : L) :
    higginsBalanceTensor L xs x y u v ∈ higginsFiltration L (xs.length + 3) := by
  rw [higginsBalanceTensor_eq]
  apply (higginsFiltration L (xs.length + 3)).sub_mem
  · have h := mul_ι_mem_higginsFiltration_succ L ⁅u, v⁆
      (rightTensorWordFiltrationElement L xs 2
        (envelopingRelationFiltrationElement L x y)).property
    simpa only [rightTensorWordFiltrationElement, Nat.add_assoc, Nat.add_comm,
      Nat.add_left_comm] using h
  · have h := ι_mul_mem_higginsFiltration_succ L ⁅x, y⁆
      (leftTensorWordFiltrationElement L xs 2
        (envelopingRelationFiltrationElement L u v)).property
    simpa only [leftTensorWordFiltrationElement, Nat.add_assoc, Nat.add_comm,
      Nat.add_left_comm, mul_assoc] using h

/-- The balance tensor, regarded at its natural top filtration degree. -/
def higginsBalanceFiltrationElement (xs : List L) (x y u v : L) :
    higginsFiltration L (xs.length + 4) :=
  ⟨higginsBalanceTensor L xs x y u v,
    higginsFiltration_mono L (by omega)
      (higginsBalanceTensor_mem_lower L xs x y u v)⟩

theorem higginsBalanceFiltrationElement_mem_previous
    (xs : List L) (x y u v : L) :
    higginsBalanceFiltrationElement L xs x y u v ∈
      previousHigginsFiltration L (xs.length + 4) := by
  change higginsBalanceTensor L xs x y u v ∈
    higginsFiltration L ((xs.length + 4) - 1)
  simpa using higginsBalanceTensor_mem_lower L xs x y u v

theorem tensorGeneratorCommutator_eq (a b : L) :
    ⁅TensorAlgebra.ι ℤ a, TensorAlgebra.ι ℤ b⁆ =
      tensorWord L [a, b] - tensorWord L [b, a] := by
  simp [tensorWord, LieRing.of_associative_ring_bracket]

def higginsRightBalanceTopElement (xs : List L) (x y u v : L) :
    higginsFiltration L (xs.length + 4) :=
  ⟨envelopingRelation L x y * tensorWord L xs *
      ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆, by
    rw [tensorGeneratorCommutator_eq]
    rw [mul_sub]
    apply (higginsFiltration L (xs.length + 4)).sub_mem
    · have h := (rightTensorWordFiltrationElement L (xs ++ [u, v]) 2
          (envelopingRelationFiltrationElement L x y)).property
      simpa [rightTensorWordFiltrationElement, envelopingRelationFiltrationElement,
        tensorWord_append, tensorWord, mul_assoc, Nat.add_assoc, Nat.add_comm,
        Nat.add_left_comm]
        using h
    · have h := (rightTensorWordFiltrationElement L (xs ++ [v, u]) 2
          (envelopingRelationFiltrationElement L x y)).property
      simpa [rightTensorWordFiltrationElement, envelopingRelationFiltrationElement,
        tensorWord_append, tensorWord, mul_assoc, Nat.add_assoc, Nat.add_comm,
        Nat.add_left_comm]
        using h⟩

def higginsLeftBalanceTopElement (xs : List L) (x y u v : L) :
    higginsFiltration L (xs.length + 4) :=
  ⟨⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * tensorWord L xs *
      envelopingRelation L u v, by
    rw [tensorGeneratorCommutator_eq]
    rw [sub_mul, sub_mul]
    apply (higginsFiltration L (xs.length + 4)).sub_mem
    · have h := (leftTensorWordFiltrationElement L ([x, y] ++ xs) 2
          (envelopingRelationFiltrationElement L u v)).property
      simpa [leftTensorWordFiltrationElement, envelopingRelationFiltrationElement,
        tensorWord_append, tensorWord, mul_assoc, Nat.add_assoc, Nat.add_comm,
        Nat.add_left_comm]
        using h
    · have h := (leftTensorWordFiltrationElement L ([y, x] ++ xs) 2
          (envelopingRelationFiltrationElement L u v)).property
      simpa [leftTensorWordFiltrationElement, envelopingRelationFiltrationElement,
        tensorWord_append, tensorWord, mul_assoc, Nat.add_assoc, Nat.add_comm,
        Nat.add_left_comm]
        using h⟩

theorem rightTop_sub_leftTop_eq_balance (xs : List L) (x y u v : L) :
    higginsRightBalanceTopElement L xs x y u v -
        higginsLeftBalanceTopElement L xs x y u v =
      higginsBalanceFiltrationElement L xs x y u v := by
  apply Subtype.ext
  rfl

theorem right_commutator_smul_tensorWord_relation
    (xs : List L) (x y u v : L) :
    letI := higginsAssociatedModuleOpposite L
    MulOpposite.op ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ •
        (MulOpposite.op (tensorWord L xs) • higginsRelationClass L x y) =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (xs.length + 4)
        (Submodule.Quotient.mk (higginsRightBalanceTopElement L xs x y u v)) := by
  letI := higginsAssociatedModuleOpposite L
  rw [tensorGeneratorCommutator_eq, MulOpposite.op_sub, sub_smul]
  change MulOpposite.op (tensorWord L [u, v]) •
        (MulOpposite.op (tensorWord L xs) •
          DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 2
            (Submodule.Quotient.mk (envelopingRelationFiltrationElement L x y))) -
      MulOpposite.op (tensorWord L [v, u]) •
        (MulOpposite.op (tensorWord L xs) •
          DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 2
            (Submodule.Quotient.mk (envelopingRelationFiltrationElement L x y))) = _
  rw [right_tensorWords_smul_lof_mk, right_tensorWords_smul_lof_mk]
  apply lof_quotient_mk_sub_eq_of_coe_sub_eq L
  · simp
    omega
  · simp
    omega
  · simp [rightTensorWordFiltrationElement, higginsRightBalanceTopElement,
      envelopingRelationFiltrationElement, tensorWord_append, tensorWord,
      LieRing.of_associative_ring_bracket, mul_assoc, mul_sub]

theorem left_commutator_tensorWord_smul_relation
    (xs : List L) (x y u v : L) :
    letI := higginsAssociatedModule L
    (⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * tensorWord L xs) •
        higginsRelationClass L u v =
      DirectSum.lof ℤ ℕ (HigginsGradedPiece L) (xs.length + 4)
        (Submodule.Quotient.mk (higginsLeftBalanceTopElement L xs x y u v)) := by
  letI := higginsAssociatedModule L
  rw [tensorGeneratorCommutator_eq, sub_mul, sub_smul]
  rw [← tensorWord_append, ← tensorWord_append]
  change tensorWord L ([x, y] ++ xs) •
        DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 2
          (Submodule.Quotient.mk (envelopingRelationFiltrationElement L u v)) -
      tensorWord L ([y, x] ++ xs) •
        DirectSum.lof ℤ ℕ (HigginsGradedPiece L) 2
          (Submodule.Quotient.mk (envelopingRelationFiltrationElement L u v)) = _
  rw [left_tensorWord_smul_lof_mk, left_tensorWord_smul_lof_mk]
  apply lof_quotient_mk_sub_eq_of_coe_sub_eq L
  · simp
    omega
  · simp
    omega
  · simp [leftTensorWordFiltrationElement, higginsLeftBalanceTopElement,
      envelopingRelationFiltrationElement, tensorWord_append, tensorWord,
      LieRing.of_associative_ring_bracket, mul_assoc, sub_mul]

theorem higginsRelationClass_balance_tensorWord
    (x y u v : L) (xs : List L) :
    letI := higginsAssociatedModule L
    letI := higginsAssociatedModuleOpposite L
    MulOpposite.op ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ •
        (MulOpposite.op (tensorWord L xs) • higginsRelationClass L x y) =
      (⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * tensorWord L xs) •
        higginsRelationClass L u v := by
  letI := higginsAssociatedModule L
  letI := higginsAssociatedModuleOpposite L
  rw [right_commutator_smul_tensorWord_relation,
    left_commutator_tensorWord_smul_relation]
  rw [← sub_eq_zero, ← map_sub, ← Submodule.Quotient.mk_sub,
    rightTop_sub_leftTop_eq_balance]
  have hq :
      Submodule.Quotient.mk (higginsBalanceFiltrationElement L xs x y u v) = 0 :=
    (Submodule.Quotient.mk_eq_zero (previousHigginsFiltration L (xs.length + 4))).mpr
      (higginsBalanceFiltrationElement_mem_previous L xs x y u v)
  rw [hq, map_zero]

/-- Higgins's balance identity (L2) for the relation class and an arbitrary tensor. -/
theorem higginsRelationClass_balance (x y u v : L) (t : T) :
    letI := higginsAssociatedModule L
    letI := higginsAssociatedModuleOpposite L
    letI := higginsAssociatedSMulCommClass L
    MulOpposite.op ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ •
        (MulOpposite.op t • higginsRelationClass L x y) =
      (⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * t) •
        higginsRelationClass L u v := by
  letI := higginsAssociatedModule L
  letI := higginsAssociatedModuleOpposite L
  letI := higginsAssociatedSMulCommClass L
  obtain ⟨n, ht⟩ := exists_mem_tensorDegreeFiltration L t
  induction ht using Submodule.span_induction with
  | mem t ht =>
      obtain ⟨xs, hxs, rfl⟩ := ht
      exact higginsRelationClass_balance_tensorWord L x y u v xs
  | zero => simp
  | add a b ha hb hia hib =>
      simpa only [MulOpposite.op_add, add_smul, mul_add, smul_add] using
        congrArg₂ (· + ·) hia hib
  | smul c a ha hia =>
      have hop (z : HigginsAssociatedGraded L) :
          MulOpposite.op (c • a) • z = c • (MulOpposite.op a • z) := by
        have hopc : MulOpposite.op (c • a) = c • MulOpposite.op a :=
          map_smul (MulOpposite.opLinearEquiv ℤ) c a
        rw [hopc]
        exact smul_assoc c (MulOpposite.op a) z
      have hleft (z : HigginsAssociatedGraded L) :
          (⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * (c • a)) • z =
            c • ((⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * a) • z) := by
        rw [mul_smul_comm]
        exact smul_assoc c _ z
      calc
        _ = MulOpposite.op ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ •
              (c • (MulOpposite.op a • higginsRelationClass L x y)) :=
            congrArg
              (fun z : HigginsAssociatedGraded L ↦
                MulOpposite.op ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ • z)
              (hop (higginsRelationClass L x y))
        _ = c • (MulOpposite.op ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆ •
              (MulOpposite.op a • higginsRelationClass L x y)) :=
            map_zsmul
              (DistribSMul.toAddMonoidHom (HigginsAssociatedGraded L)
                (MulOpposite.op ⁅TensorAlgebra.ι ℤ u, TensorAlgebra.ι ℤ v⁆)) c _
        _ = c • ((⁅TensorAlgebra.ι ℤ x, TensorAlgebra.ι ℤ y⁆ * a) •
              higginsRelationClass L u v) := congrArg (c • ·) hia
        _ = _ := (hleft (higginsRelationClass L u v)).symm

/-- The associated graded of Higgins's filtration, with its canonical Higgins Lie structure. -/
noncomputable def higginsFiltrationLieStructure :
    letI := higginsAssociatedModule L
    letI := higginsAssociatedModuleOpposite L
    letI := higginsAssociatedSMulCommClass L
    LieStructure L (HigginsAssociatedGraded L) := by
  letI := higginsAssociatedModule L
  letI := higginsAssociatedModuleOpposite L
  letI := higginsAssociatedSMulCommClass L
  exact
    { bracket := higginsRelationClass L
      lie_self := higginsRelationClass_lie_self L
      balance := higginsRelationClass_balance L
      jacobi := higginsRelationClass_jacobi L }

end

end LieRings.PBW.Higgins
