import LieRings.DimensionSubring.DegreeFive.GlobalReduction
import LieRings.DimensionSubring.DegreeFive.FiniteClassTwoBasis

/-!
# Finite witnesses for the factor-two reduction

This file records the two finitary inputs used by the factor-two proof: a Lie ring generated by
finitely many elements has a module-finite class-three quotient, and a finite family of free
associative words uses only finitely many generators.
-/

namespace LieRings.DegreeFive

noncomputable section

universe u v

variable (X : Type u) [Finite X]

local notation "F" => FreeLieAlgebra ℤ X

/-- The first three homogeneous pieces, evaluated in a class-three quotient. -/
def finiteLowExactToClassThree
    (A : Type v) [LieRing A] (evaluation : F →ₗ⁅ℤ⁆ A) :
    (freeLieExact X 1 × freeLieExact X 2 × freeLieExact X 3) →ₗ[ℤ]
      ClassThreeQuotient A where
  toFun z := LieSubmodule.Quotient.mk
    (evaluation ((z.1 : F) + (z.2.1 : F) + (z.2.2 : F)))
  map_add' x y := by
    simp only [Prod.fst_add, Prod.snd_add]
    change LieSubmodule.Quotient.mk (evaluation
      (((x.1 + y.1 : freeLieExact X 1) : F) +
        ((x.2.1 + y.2.1 : freeLieExact X 2) : F) +
        ((x.2.2 + y.2.2 : freeLieExact X 3) : F))) = _
    change LieSubmodule.Quotient.mk (evaluation
      ((x.1 : F) + (y.1 : F) + ((x.2.1 : F) + (y.2.1 : F)) +
        ((x.2.2 : F) + (y.2.2 : F)))) = _
    simp only [map_add]
    congr 1
    abel
  map_smul' n x := by
    simp only [Prod.smul_fst, Prod.smul_snd]
    change LieSubmodule.Quotient.mk (evaluation
      (((n • x.1 : freeLieExact X 1) : F) +
        ((n • x.2.1 : freeLieExact X 2) : F) +
        ((n • x.2.2 : freeLieExact X 3) : F))) = _
    change LieSubmodule.Quotient.mk (evaluation
      (n • (x.1 : F) + n • (x.2.1 : F) + n • (x.2.2 : F))) = _
    rw [← smul_add, ← smul_add, map_smul]
    exact Submodule.Quotient.mk_smul
      (lowerCentralSeries ℤ A 3).toSubmodule n _

/-- The first three homogeneous pieces surject onto the class-three quotient of every
surjective image of the finite free Lie ring. -/
theorem finiteLowExactToClassThree_surjective
    (A : Type v) [LieRing A] (evaluation : F →ₗ⁅ℤ⁆ A)
    (hevaluation : Function.Surjective evaluation) :
    Function.Surjective (finiteLowExactToClassThree X A evaluation) := by
  intro z
  induction z using Submodule.Quotient.induction_on with
  | _ a =>
      obtain ⟨f, rfl⟩ := hevaluation a
      let f₁ : freeLieExact X 1 :=
        ⟨freeLieLengthComponent X 1 f,
          freeLieLengthComponent_mem_exact X 1 f⟩
      let f₂ : freeLieExact X 2 :=
        ⟨freeLieLengthComponent X 2 f,
          freeLieLengthComponent_mem_exact X 2 f⟩
      let f₃ : freeLieExact X 3 :=
        ⟨freeLieLengthComponent X 3 f,
          freeLieLengthComponent_mem_exact X 3 f⟩
      refine ⟨(f₁, f₂, f₃), ?_⟩
      apply sub_eq_zero.mp
      change LieSubmodule.Quotient.mk
          (evaluation ((f₁ : F) + (f₂ : F) + (f₃ : F))) -
        LieSubmodule.Quotient.mk (evaluation f) = 0
      rw [← Submodule.Quotient.mk_sub, ← map_sub]
      apply (LieSubmodule.Quotient.mk_eq_zero'
        (N := lowerCentralSeries ℤ A 3)).mpr
      change evaluation (((f₁ : F) + (f₂ : F) + (f₃ : F)) - f) ∈
        lowerCentralSeries ℤ A 3
      apply (LieIdeal.map_lowerCentralSeries_le (R := ℤ) (f := evaluation) 3)
      apply LieIdeal.mem_map
      have hhighOne : f - (f₁ : F) - (f₂ : F) - (f₃ : F) ∈
          FreeLieDimension.lieHigh X 1 := by
        rw [FreeLieDimension.lieHigh_one]
        trivial
      have hcomponentOne : freeLieLengthComponent X 1
          (f - (f₁ : F) - (f₂ : F) - (f₃ : F)) = 0 := by
        rw [map_sub, map_sub, map_sub,
          freeLieLengthComponent_coe_exact X 1 f₁,
          freeLieLengthComponent_coe_exact_of_ne X f₂ (by omega : 2 ≠ 1),
          freeLieLengthComponent_coe_exact_of_ne X f₃ (by omega : 3 ≠ 1)]
        change freeLieLengthComponent X 1 f - freeLieLengthComponent X 1 f - 0 - 0 = 0
        abel
      have hhighTwo : f - (f₁ : F) - (f₂ : F) - (f₃ : F) ∈
          FreeLieDimension.lieHigh X 2 := by
        simpa using mem_lieHigh_succ_of_component_eq_zero X hhighOne hcomponentOne
      have hcomponentTwo : freeLieLengthComponent X 2
          (f - (f₁ : F) - (f₂ : F) - (f₃ : F)) = 0 := by
        rw [map_sub, map_sub, map_sub,
          freeLieLengthComponent_coe_exact_of_ne X f₁ (by omega : 1 ≠ 2),
          freeLieLengthComponent_coe_exact X 2 f₂,
          freeLieLengthComponent_coe_exact_of_ne X f₃ (by omega : 3 ≠ 2)]
        change freeLieLengthComponent X 2 f - 0 - freeLieLengthComponent X 2 f - 0 = 0
        abel
      have hhighThree : f - (f₁ : F) - (f₂ : F) - (f₃ : F) ∈
          FreeLieDimension.lieHigh X 3 := by
        simpa using mem_lieHigh_succ_of_component_eq_zero X hhighTwo hcomponentTwo
      have hcomponentThree : freeLieLengthComponent X 3
          (f - (f₁ : F) - (f₂ : F) - (f₃ : F)) = 0 := by
        rw [map_sub, map_sub, map_sub,
          freeLieLengthComponent_coe_exact_of_ne X f₁ (by omega : 1 ≠ 3),
          freeLieLengthComponent_coe_exact_of_ne X f₂ (by omega : 2 ≠ 3),
          freeLieLengthComponent_coe_exact X 3 f₃]
        change freeLieLengthComponent X 3 f - 0 - 0 - freeLieLengthComponent X 3 f = 0
        abel
      have hhighFour : f - (f₁ : F) - (f₂ : F) - (f₃ : F) ∈
          FreeLieDimension.lieHigh X 4 := by
        simpa using mem_lieHigh_succ_of_component_eq_zero X hhighThree hcomponentThree
      have hrem : (f₁ : F) + (f₂ : F) + (f₃ : F) - f ∈
          FreeLieDimension.lieHigh X 4 := by
        simpa [sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using
          (FreeLieDimension.lieHigh X 4).neg_mem hhighFour
      rw [FreeLieDimension.lieHigh_eq_lowerCentralSeries X 3] at hrem
      exact hrem

/-- A surjective image of a free Lie ring on a finite type has module-finite class-three
quotient. -/
theorem moduleFinite_classThreeQuotient_of_surjective_free
    (A : Type v) [LieRing A] (evaluation : F →ₗ⁅ℤ⁆ A)
    (hevaluation : Function.Surjective evaluation) :
    Module.Finite ℤ (ClassThreeQuotient A) := by
  exact Module.Finite.of_surjective
    (finiteLowExactToClassThree X A evaluation)
    (finiteLowExactToClassThree_surjective X A evaluation hevaluation)

section FiniteSupport

variable {X : Type u} {Y : Type v}

/-- Renaming the generators of a free Lie ring. -/
def freeLieRename (e : X → Y) :
    FreeLieAlgebra ℤ X →ₗ⁅ℤ⁆ FreeLieAlgebra ℤ Y :=
  FreeLieAlgebra.lift ℤ (fun x ↦ FreeLieAlgebra.of ℤ (e x))

/-- Renaming the generators of a free associative algebra. -/
def freeAssociativeRename (e : X → Y) :
    FreeAlgebra ℤ X →ₐ[ℤ] FreeAlgebra ℤ Y :=
  FreeAlgebra.lift ℤ (fun x ↦ FreeAlgebra.ι ℤ (e x))

@[simp]
theorem freeLieRename_of (e : X → Y) (x : X) :
    freeLieRename e (FreeLieAlgebra.of ℤ x) = FreeLieAlgebra.of ℤ (e x) := by
  exact FreeLieAlgebra.lift_of_apply
    (R := ℤ) (fun x ↦ FreeLieAlgebra.of ℤ (e x)) x

@[simp]
theorem freeAssociativeRename_ι (e : X → Y) (x : X) :
    freeAssociativeRename e (FreeAlgebra.ι ℤ x) = FreeAlgebra.ι ℤ (e x) := by
  simp [freeAssociativeRename]

/-- The standard identification `U(FreeLie X) ≃ FreeAlgebra X` is natural in `X`. -/
theorem universalEnvelopingEquivFreeAlgebra_natural
    (e : X → Y) (u : UEA ℤ (FreeLieAlgebra ℤ X)) :
    FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ Y
        (UEA.map ℤ (FreeLieAlgebra ℤ X) (FreeLieAlgebra ℤ Y)
          (freeLieRename e) u) =
      freeAssociativeRename e
        (FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ X u) := by
  let left : UEA ℤ (FreeLieAlgebra ℤ X) →ₐ[ℤ] FreeAlgebra ℤ Y :=
    (FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ Y).toAlgHom.comp
      (UEA.map ℤ (FreeLieAlgebra ℤ X) (FreeLieAlgebra ℤ Y) (freeLieRename e))
  let right : UEA ℤ (FreeLieAlgebra ℤ X) →ₐ[ℤ] FreeAlgebra ℤ Y :=
    (freeAssociativeRename e).comp
      (FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ X).toAlgHom
  change left u = right u
  suffices left = right by rw [this]
  apply UniversalEnvelopingAlgebra.hom_ext
  apply LieHom.ext
  intro x
  change left (UniversalEnvelopingAlgebra.ι ℤ x) =
    right (UniversalEnvelopingAlgebra.ι ℤ x)
  rw [show left (UniversalEnvelopingAlgebra.ι ℤ x) =
      FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ Y
        (UEA.map ℤ (FreeLieAlgebra ℤ X) (FreeLieAlgebra ℤ Y)
          (freeLieRename e) (UniversalEnvelopingAlgebra.ι ℤ x)) by rfl,
    UEA.map_ι]
  let lhs : FreeLieAlgebra ℤ X →ₗ⁅ℤ⁆ FreeAlgebra ℤ Y :=
    (PBW.freeLieToFreeAlgebra ℤ Y).comp (freeLieRename e)
  let rhs : FreeLieAlgebra ℤ X →ₗ⁅ℤ⁆ FreeAlgebra ℤ Y :=
    (freeAssociativeRename e).toLieHom.comp
      (PBW.freeLieToFreeAlgebra ℤ X)
  have hnat : lhs = rhs := by
    apply FreeLieAlgebra.hom_ext
    intro z
    change PBW.freeLieToFreeAlgebra ℤ Y
        (freeLieRename e (FreeLieAlgebra.of ℤ z)) =
      freeAssociativeRename e
        (PBW.freeLieToFreeAlgebra ℤ X (FreeLieAlgebra.of ℤ z))
    rw [freeLieRename_of]
    change (FreeLieAlgebra.lift ℤ (FreeAlgebra.ι ℤ))
        (FreeLieAlgebra.of ℤ (e z)) =
      freeAssociativeRename e
        ((FreeLieAlgebra.lift ℤ (FreeAlgebra.ι ℤ))
          (FreeLieAlgebra.of ℤ z))
    rw [FreeLieAlgebra.lift_of_apply, FreeLieAlgebra.lift_of_apply,
      freeAssociativeRename_ι]
  calc
    FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ Y
        (UniversalEnvelopingAlgebra.ι ℤ (freeLieRename e x)) =
        PBW.freeLieToFreeAlgebra ℤ Y (freeLieRename e x) :=
      FreeLieDimension.universalEnvelopingEquiv_ι_eq_freeLieToFreeAlgebra
        Y (freeLieRename e x)
    _ = freeAssociativeRename e (PBW.freeLieToFreeAlgebra ℤ X x) :=
      DFunLike.congr_fun hnat x
    _ = freeAssociativeRename e
        (FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ X
          (UniversalEnvelopingAlgebra.ι ℤ x)) := by
      exact congrArg (freeAssociativeRename e)
        (FreeLieDimension.universalEnvelopingEquiv_ι_eq_freeLieToFreeAlgebra
          X x).symm

/-- Every free-associative polynomial involves only finitely many generators, expressed in the
form most useful for changing the ambient alphabet. -/
theorem exists_finset_fixedBy_freeAssociativeRename
    (a : FreeAlgebra ℤ X) :
    ∃ S : Finset X, ∀ e : X → X,
      (∀ x ∈ S, e x = x) → freeAssociativeRename e a = a := by
  classical
  induction a using FreeAlgebra.induction with
  | grade0 n =>
      refine ⟨∅, ?_⟩
      intro e he
      simp [freeAssociativeRename]
  | grade1 x =>
      refine ⟨{x}, ?_⟩
      intro e he
      simpa [freeAssociativeRename] using he x (by simp)
  | mul a b ha hb =>
      obtain ⟨Sa, ha⟩ := ha
      obtain ⟨Sb, hb⟩ := hb
      refine ⟨Sa ∪ Sb, ?_⟩
      intro e he
      rw [map_mul, ha e (fun x hx ↦ he x (Finset.mem_union_left _ hx)),
        hb e (fun x hx ↦ he x (Finset.mem_union_right _ hx))]
  | add a b ha hb =>
      obtain ⟨Sa, ha⟩ := ha
      obtain ⟨Sb, hb⟩ := hb
      refine ⟨Sa ∪ Sb, ?_⟩
      intro e he
      rw [map_add, ha e (fun x hx ↦ he x (Finset.mem_union_left _ hx)),
        hb e (fun x hx ↦ he x (Finset.mem_union_right _ hx))]

/-- A finite family of free-associative polynomials has a common finite alphabet. -/
theorem exists_finset_fixedBy_freeAssociativeRename_finset
    (T : Finset (FreeAlgebra ℤ X)) :
    ∃ S : Finset X, ∀ e : X → X,
      (∀ x ∈ S, e x = x) → ∀ a ∈ T, freeAssociativeRename e a = a := by
  classical
  induction T using Finset.induction_on with
  | empty => exact ⟨∅, fun _ _ _ h ↦ by simp at h⟩
  | @insert a T ha ih =>
      obtain ⟨Sa, hSa⟩ := exists_finset_fixedBy_freeAssociativeRename a
      obtain ⟨ST, hST⟩ := ih
      refine ⟨Sa ∪ ST, ?_⟩
      intro e he b hb
      rw [Finset.mem_insert] at hb
      rcases hb with rfl | hb
      · exact hSa e (fun x hx ↦ he x (Finset.mem_union_left _ hx))
      · exact hST e (fun x hx ↦ he x (Finset.mem_union_right _ hx)) b hb

/-- A finite family in the enveloping algebra of a free Lie ring has a common finite alphabet. -/
theorem exists_finset_fixedBy_ueaRename_finset
    (T : Finset (UEA ℤ (FreeLieAlgebra ℤ X))) :
    ∃ S : Finset X, ∀ e : X → X,
      (∀ x ∈ S, e x = x) → ∀ a ∈ T,
        UEA.map ℤ (FreeLieAlgebra ℤ X) (FreeLieAlgebra ℤ X)
          (freeLieRename e) a = a := by
  classical
  let E := FreeLieAlgebra.universalEnvelopingEquivFreeAlgebra ℤ X
  obtain ⟨S, hS⟩ :=
    exists_finset_fixedBy_freeAssociativeRename_finset (T.image E)
  refine ⟨S, ?_⟩
  intro e he a ha
  apply E.injective
  rw [universalEnvelopingEquivFreeAlgebra_natural]
  exact hS e he (E a) (Finset.mem_image.mpr ⟨a, ha, rfl⟩)

end FiniteSupport

end

end LieRings.DegreeFive
