import LieRings.FinitePlateau.Presentation
import LieRings.Plotkin.NilpotentTarget
import Mathlib.RingTheory.MvPolynomial.Ideal
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Truncated metabelian Magnus probes

This file constructs the presentation-specific associative probes used to
read Hall coordinates below the critical degree.  The coefficient ring is a
truncated symmetric algebra.  The nonunital Magnus ring consists of pairs
`(s,m)` with multiplication `(s,m)(t,n)=(st,sn)`; its commutator Lie ring is
metabelian, and the standard generator `i` is sent to `(X_i,X_i e_i)`.

The construction is deliberately independent of any PBW assertion for a
torsion Lie ring.  All coefficient calculations take place before passing to
the presented quotient, in an explicit associative ring whose nilpotence is
controlled by polynomial degree.
-/

namespace LieRings.FinitePlateau

noncomputable section

open LieRings.Plotkin

namespace MagnusProbe

-- Quotients of multivariable polynomial rings carry several equivalent
-- scalar actions; the larger local budget keeps their deterministic instance
-- search from obscuring the elementary degree arguments below.
set_option synthInstance.maxHeartbeats 100000

/-- The polynomial ring used by a probe with coefficient modulus `q`.  As
usual, `ZMod 0` is the integral coefficient ring. -/
abbrev Poly (q : ℕ) := MvPolynomial Generator (ZMod q)

/-- The ideal generated by all five variables. -/
abbrev variableIdeal (q : ℕ) : Ideal (Poly q) :=
  MvPolynomial.idealOfVars Generator (ZMod q)

/-- Symmetric polynomials truncated just before total degree `r`. -/
abbrev TruncatedPoly (q r : ℕ) := Poly q ⧸ variableIdeal q ^ r

/-- The positive-degree ideal in the truncated polynomial ring. -/
def positiveIdeal (q r : ℕ) : Ideal (TruncatedPoly q r) :=
  (variableIdeal q).map (Ideal.Quotient.mk (variableIdeal q ^ r))

instance positiveIdeal_isTwoSided (q r : ℕ) :
    (positiveIdeal q r).IsTwoSided := inferInstance

set_option synthInstance.maxHeartbeats 100000 in
/-- By construction, the `r`th power of the positive-degree ideal is zero. -/
theorem positiveIdeal_pow_eq_bot (q r : ℕ) :
    positiveIdeal q r ^ r = ⊥ := by
  change ((variableIdeal q).map
      (Ideal.Quotient.mk (variableIdeal q ^ r))) ^ r = ⊥
  rw [← Ideal.map_pow, Ideal.map_quotient_self]

set_option synthInstance.maxHeartbeats 100000 in
/-- A named form of the powers of the positive ideal.  Naming this object
keeps quotient-ring instance synthesis out of the later filtration API. -/
def positivePower (q r n : ℕ) : Ideal (TruncatedPoly q r) :=
  positiveIdeal q r ^ n

@[simp] theorem positivePower_one (q r : ℕ) :
    positivePower q r 1 = positiveIdeal q r := by
  rw [positivePower, Submodule.pow_one]

theorem positivePower_pow_add (q r m n : ℕ) :
    positivePower q r (m + n) = positivePower q r m * positivePower q r n := by
  change positiveIdeal q r ^ (m + n) =
    positiveIdeal q r ^ m * positiveIdeal q r ^ n
  rw [Ideal.IsTwoSided.pow_add]

theorem positivePower_eq_bot_of_le (q r n : ℕ) (hrn : r ≤ n) :
    positivePower q r n = ⊥ := by
  apply le_antisymm ?_ bot_le
  change positiveIdeal q r ^ n ≤ ⊥
  exact (Ideal.pow_le_pow_right hrn).trans_eq (positiveIdeal_pow_eq_bot q r)

/-- The image of a polynomial variable in the positive-degree ideal. -/
def varImage (q r : ℕ) (i : Generator) : positiveIdeal q r :=
  ⟨Ideal.Quotient.mk (variableIdeal q ^ r) (MvPolynomial.X i),
    Ideal.mem_map_of_mem (Ideal.Quotient.mk (variableIdeal q ^ r))
      (Ideal.subset_span (Set.mem_range_self i))⟩

@[simp] theorem varImage_coe (q r : ℕ) (i : Generator) :
    ((varImage q r i : positiveIdeal q r) : TruncatedPoly q r) =
      Ideal.Quotient.mk (variableIdeal q ^ r) (MvPolynomial.X i) := rfl

/-- The one-sided square-zero extension used in the classical Magnus
embedding of a free metabelian Lie ring. -/
structure Ring (q r : ℕ) where
  scalar : positiveIdeal q r
  vector : Generator → positiveIdeal q r

namespace Ring

variable (q r : ℕ)

@[ext] theorem ext {x y : Ring q r}
    (hscalar : x.scalar = y.scalar) (hvector : x.vector = y.vector) : x = y := by
  cases x
  cases y
  simp_all

def equivType : Ring q r ≃ positiveIdeal q r × (Generator → positiveIdeal q r) where
  toFun x := (x.scalar, x.vector)
  invFun x := ⟨x.1, x.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

instance : AddCommGroup (Ring q r) := (equivType q r).addCommGroup

instance : Mul (Ring q r) where
  mul x y := ⟨x.scalar * y.scalar, fun i ↦ x.scalar * y.vector i⟩

@[simp] theorem scalar_zero : (0 : Ring q r).scalar = 0 := rfl
@[simp] theorem vector_zero (i : Generator) : (0 : Ring q r).vector i = 0 := rfl
@[simp] theorem scalar_add (x y : Ring q r) : (x + y).scalar = x.scalar + y.scalar := rfl
@[simp] theorem vector_add (x y : Ring q r) (i : Generator) :
    (x + y).vector i = x.vector i + y.vector i := rfl
@[simp] theorem scalar_neg (x : Ring q r) : (-x).scalar = -x.scalar := rfl
@[simp] theorem vector_neg (x : Ring q r) (i : Generator) :
    (-x).vector i = -x.vector i := rfl
@[simp] theorem scalar_zsmul (z : ℤ) (x : Ring q r) :
    (z • x).scalar = z • x.scalar := rfl
@[simp] theorem vector_zsmul (z : ℤ) (x : Ring q r) (i : Generator) :
    (z • x).vector i = z • x.vector i := rfl
@[simp] theorem scalar_mul (x y : Ring q r) : (x * y).scalar = x.scalar * y.scalar := rfl
@[simp] theorem vector_mul (x y : Ring q r) (i : Generator) :
    (x * y).vector i = x.scalar * y.vector i := rfl

instance : NonUnitalNonAssocRing (Ring q r) :=
  NonUnitalNonAssocRing.mk
    (by
      intro x y z
      apply ext
      · simp [mul_add]
      · funext i
        simp [mul_add])
    (by
      intro x y z
      apply ext
      · simp [add_mul]
      · funext i
        simp [add_mul])
    (by
      intro x
      apply ext
      · simp
      · funext i
        simp)
    (by
      intro x
      apply ext
      · simp
      · funext i
        simp)

instance : NonUnitalRing (Ring q r) :=
  NonUnitalRing.mk (by
    intro x y z
    apply ext
    · simp [mul_assoc]
    · funext i
      simp [mul_assoc])

/-- The standard Magnus value of the generator `i`. -/
def generator (i : Generator) : Ring q r where
  scalar := varImage q r i
  vector j := if i = j then varImage q r i else 0

@[simp] theorem generator_scalar (i : Generator) :
    (generator q r i).scalar = varImage q r i := rfl

@[simp] theorem generator_vector (i j : Generator) :
    (generator q r i).vector j = if i = j then varImage q r i else 0 := rfl

end Ring

/-! ## The commutator Lie ring and its degree filtration -/

/-- The commutator Lie ring of the positive Magnus ring. -/
abbrev Target (q r : ℕ) := NonUnitalCommutator (Ring q r)

namespace Target

variable (q r : ℕ)

private def asRing : Target q r ≃+ Ring q r := AddEquiv.refl _

@[simp] theorem scalar_zero : (show Ring q r from (0 : Target q r)).scalar = 0 := rfl

@[simp] theorem vector_zero (i : Generator) :
    (show Ring q r from (0 : Target q r)).vector i = 0 := rfl

@[simp] theorem scalar_lie (x y : Target q r) :
    (⁅x, y⁆ : Target q r).scalar = 0 := by
  change x.scalar * y.scalar - y.scalar * x.scalar = 0
  rw [mul_comm, sub_self]

@[simp] theorem vector_lie (x y : Target q r) (i : Generator) :
    (⁅x, y⁆ : Target q r).vector i =
      x.scalar * y.vector i - y.scalar * x.vector i := rfl

/-- The ideal of Magnus elements with zero scalar coordinate. -/
def scalarZeroIdeal : LieIdeal ℤ (Target q r) where
  carrier := {x | x.scalar = 0}
  zero_mem' := rfl
  add_mem' := by
    intro x y hx hy
    change x.scalar + y.scalar = 0
    rw [hx, hy, add_zero]
  smul_mem' := by
    intro z x hx
    change z • x.scalar = 0
    rw [hx]
    exact zsmul_zero z
  lie_mem := by
    intro x y hy
    exact scalar_lie q r x y

/-- Every derived Magnus element has zero scalar coordinate. -/
theorem derived_le_scalarZero :
    LieAlgebra.derivedSeries ℤ (Target q r) 1 ≤ scalarZeroIdeal q r := by
  change ⁅(⊤ : LieIdeal ℤ (Target q r)),
    (⊤ : LieIdeal ℤ (Target q r))⁆ ≤ scalarZeroIdeal q r
  rw [LieSubmodule.lie_le_iff]
  intro x hx y hy
  exact scalar_lie q r x y

/-- The Magnus commutator Lie ring is metabelian. -/
theorem isMetabelian : IsMetabelian (Target q r) := by
  apply IsMetabelian.iff_bracket_eq_zero.mpr
  intro x y hx hy
  apply Ring.ext
  · exact scalar_lie q r x y
  · funext i
    rw [vector_lie]
    have hxs : x.scalar = 0 := derived_le_scalarZero q r hx
    have hys : y.scalar = 0 := derived_le_scalarZero q r hy
    rw [hxs, hys]
    simp

/-- Elements all of whose Magnus coordinates have polynomial degree at
least `n`. -/
def degreeLieSubmodule (n : ℕ) : LieSubmodule ℤ (Target q r) (Target q r) where
  carrier := {x | ((x.scalar : positiveIdeal q r) : TruncatedPoly q r) ∈
      positivePower q r n ∧
    ∀ i, ((x.vector i : positiveIdeal q r) : TruncatedPoly q r) ∈
      positivePower q r n}
  zero_mem' := by simp
  add_mem' := by
    rintro x y ⟨hxs, hxv⟩ ⟨hys, hyv⟩
    exact ⟨(positivePower q r n).add_mem hxs hys,
      fun i ↦ (positivePower q r n).add_mem (hxv i) (hyv i)⟩
  smul_mem' := by
    intro z x hx
    change ((z • x.scalar : positiveIdeal q r) : TruncatedPoly q r) ∈
        positivePower q r n ∧
      ∀ i, ((z • x.vector i : positiveIdeal q r) : TruncatedPoly q r) ∈
        positivePower q r n
    exact ⟨(positivePower q r n).toAddSubgroup.zsmul_mem hx.1 z,
      fun i ↦ (positivePower q r n).toAddSubgroup.zsmul_mem (hx.2 i) z⟩
  lie_mem := by
    intro x y hx
    refine ⟨?_, ?_⟩
    · simp
    · intro i
      change ((x.scalar * y.vector i - y.scalar * x.vector i :
        positiveIdeal q r) : TruncatedPoly q r) ∈ positivePower q r n
      apply (positivePower q r n).sub_mem
      · exact (positivePower q r n).mul_mem_left _ (hx.2 i)
      · exact (positivePower q r n).mul_mem_right _ hx.1

@[simp] theorem mem_degreeLieSubmodule_iff (n : ℕ) (x : Target q r) :
    x ∈ degreeLieSubmodule q r n ↔
      ((x.scalar : positiveIdeal q r) : TruncatedPoly q r) ∈
          positivePower q r n ∧
      ∀ i, ((x.vector i : positiveIdeal q r) : TruncatedPoly q r) ∈
          positivePower q r n := Iff.rfl

private theorem all_mem_degree_one (x : Target q r) :
    x ∈ degreeLieSubmodule q r 1 := by
  rw [mem_degreeLieSubmodule_iff, positivePower_one]
  exact ⟨x.scalar.property, fun i ↦ (x.vector i).property⟩

private theorem lie_mem_degree_succ {n : ℕ}
    (x y : Target q r) (hy : y ∈ degreeLieSubmodule q r (n + 1)) :
    ⁅x, y⁆ ∈ degreeLieSubmodule q r (n + 2) := by
  rw [mem_degreeLieSubmodule_iff] at hy ⊢
  refine ⟨?_, ?_⟩
  · simp
  · intro i
    rw [show n + 2 = 1 + (n + 1) by omega,
      positivePower_pow_add]
    apply (positivePower q r 1 * positivePower q r (n + 1)).sub_mem
    · have hx1 : (x.scalar : TruncatedPoly q r) ∈ positivePower q r 1 := by
        rw [positivePower_one]
        exact x.scalar.property
      exact Ideal.mul_mem_mul hx1 (hy.2 i)
    · have hxv1 : (x.vector i : TruncatedPoly q r) ∈ positivePower q r 1 := by
        rw [positivePower_one]
        exact (x.vector i).property
      simpa [mul_comm] using Ideal.mul_mem_mul hxv1 hy.1

/-- The `n`th lower-central term has polynomial degree at least `n+1`. -/
theorem lowerCentralSeries_le_degree (n : ℕ) :
    LieModule.lowerCentralSeries ℤ (Target q r) (Target q r) n ≤
      degreeLieSubmodule q r (n + 1) := by
  induction n with
  | zero =>
      intro x hx
      exact all_mem_degree_one q r x
  | succ n ih =>
      rw [LieModule.lowerCentralSeries_succ, LieSubmodule.lie_le_iff]
      intro x hx y hy
      exact lie_mem_degree_succ q r x y (ih hy)

/-- Truncation in polynomial degree forces the corresponding lower-central
cutoff. -/
theorem lowerCentralSeries_eq_bot_of_le {n : ℕ} (hrn : r ≤ n + 1) :
    LieModule.lowerCentralSeries ℤ (Target q r) (Target q r) n = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  have hdeg := lowerCentralSeries_le_degree q r n hx
  rw [mem_degreeLieSubmodule_iff] at hdeg
  have hpow : positivePower q r (n + 1) = ⊥ :=
    positivePower_eq_bot_of_le q r (n + 1) hrn
  apply Ring.ext
  · have := hdeg.1
    rw [hpow] at this
    exact Subtype.ext (by simpa using this)
  · funext i
    have := hdeg.2 i
    rw [hpow] at this
    exact Subtype.ext (by simpa using this)

end Target

/-! ## Evaluation of the relatively free source -/

/-- The prescribed values of the five free generators. -/
def generatorLinearMap (q r : ℕ) : GeneratorModule →ₗ[ℤ] Target q r :=
  generatorBasis.constr ℤ (fun i ↦ Ring.generator q r i)

@[simp] theorem generatorLinearMap_basis (q r : ℕ) (i : Generator) :
    generatorLinearMap q r (generatorBasis i) = Ring.generator q r i := by
  exact generatorBasis.constr_basis ℤ (fun i ↦ Ring.generator q r i) i

/-- Universal evaluation in a truncated Magnus probe. -/
def sourceProbe (N q r : ℕ) (hr : r ≤ N + 4) :
    Source N →ₗ⁅ℤ⁆ Target q r :=
  FreeMetabelian.Evaluation.lieHom (Target.isMetabelian q r)
    (Target.lowerCentralSeries_eq_bot_of_le q r (n := N + 3) (by omega))
    (generatorLinearMap q r)

@[simp] theorem sourceProbe_sourceGenerator
    (N q r : ℕ) (hr : r ≤ N + 4) (i : Generator) :
    sourceProbe N q r hr (sourceGenerator N i) = Ring.generator q r i := by
  rw [sourceProbe, sourceGenerator, FreeMetabelian.Free.weightIncl,
    FreeMetabelian.Evaluation.lieHom_apply,
    FreeMetabelian.Evaluation.linear_incl]
  exact generatorLinearMap_basis q r i

/-! ## Associative nilpotence and dimension-subring detection -/

private theorem ring_mul_mem_degree_add
    (q r m n : ℕ) (x y : Ring q r)
    (hx : (show Target q r from x) ∈ Target.degreeLieSubmodule q r m)
    (hy : (show Target q r from y) ∈ Target.degreeLieSubmodule q r n) :
    (show Target q r from x * y) ∈
      Target.degreeLieSubmodule q r (m + n) := by
  rw [Target.mem_degreeLieSubmodule_iff] at hx hy ⊢
  rw [positivePower_pow_add]
  exact ⟨Ideal.mul_mem_mul hx.1 hy.1,
    fun i ↦ Ideal.mul_mem_mul hx.1 (hy.2 i)⟩

private theorem unitization_pow_has_degree
    (q r k : ℕ) {x : Unitization ℤ (Ring q r)}
    (hx : x ∈ unitizationIdeal (R := Ring q r) ^ (k + 1)) :
    x.fst = 0 ∧
      (show Target q r from x.snd) ∈
        Target.degreeLieSubmodule q r (k + 1) := by
  induction k generalizing x with
  | zero =>
      have hxJ : x ∈ unitizationIdeal (R := Ring q r) := by
        simpa only [zero_add, Submodule.pow_one] using hx
      exact ⟨(mem_unitizationIdeal_iff x).mp hxJ,
        Target.all_mem_degree_one q r x.snd⟩
  | succ k ih =>
      have hxmul : x ∈ unitizationIdeal (R := Ring q r) *
          unitizationIdeal (R := Ring q r) ^ (k + 1) := by
        simpa only [Nat.succ_eq_add_one, Ideal.IsTwoSided.pow_succ] using hx
      refine Submodule.mul_induction_on hxmul ?_ ?_
      · intro a ha b hb
        have ha0 : a.fst = 0 := (mem_unitizationIdeal_iff a).mp ha
        have hadeg : (show Target q r from a.snd) ∈
            Target.degreeLieSubmodule q r 1 :=
          Target.all_mem_degree_one q r a.snd
        obtain ⟨hb0, hbdeg⟩ := ih hb
        refine ⟨?_, ?_⟩
        · simpa [Unitization.fst_mul, ha0, hb0]
        · have hsnd : (a * b).snd = a.snd * b.snd := by
            rw [Unitization.snd_mul, ha0, hb0]
            simp
          rw [hsnd]
          have hind : 1 + (k + 1) = k + 2 := by omega
          simpa only [hind] using ring_mul_mem_degree_add q r 1 (k + 1)
            a.snd b.snd hadeg hbdeg
      · intro a b ha hb
        refine ⟨?_, ?_⟩
        · simpa [ha.1, hb.1]
        · exact (Target.degreeLieSubmodule q r (k + 2)).add_mem ha.2 hb.2

/-- The positive Magnus ring is nilpotent at every exponent at least its
polynomial truncation degree. -/
theorem unitizationIdeal_pow_eq_bot
    (q r n : ℕ) (hr : r ≤ n) (hn : 1 ≤ n) :
    unitizationIdeal (R := Ring q r) ^ n = ⊥ := by
  cases n with
  | zero => omega
  | succ k =>
      apply le_antisymm ?_ bot_le
      intro x hx
      change x = 0
      have hx' : x ∈ unitizationIdeal (R := Ring q r) ^ (k + 1) := by
        simpa only [Nat.succ_eq_add_one] using hx
      obtain ⟨hfst, hdeg⟩ := unitization_pow_has_degree q r k hx'
      rw [Target.mem_degreeLieSubmodule_iff] at hdeg
      have hpow : positivePower q r (k + 1) = ⊥ :=
        positivePower_eq_bot_of_le q r (k + 1) (by omega)
      apply Unitization.ext
      · exact hfst
      · apply Ring.ext
        · have hs := hdeg.1
          rw [hpow] at hs
          exact Subtype.ext (by simpa using hs)
        · funext i
          have hv := hdeg.2 i
          rw [hpow] at hv
          exact Subtype.ext (by simpa using hv)

/-- Every critical dimension element is invisible in every truncated Magnus
probe whose truncation degree is at most the critical index. -/
theorem sourceProbe_eq_zero_of_mem_dimensionSubring
    (N q r : ℕ) (hr : r ≤ N + 4) {z : Source N}
    (hz : z ∈ dimensionSubring ℤ (Source N) (N + 4)) :
    sourceProbe N q r hr z = 0 := by
  let rho : Source N →ₗ⁅ℤ⁆ Unitization ℤ (Ring q r) :=
    nonUnitalCommutatorToUnitization.comp (sourceProbe N q r hr)
  have hzero : rho z = 0 :=
    lieHom_eq_zero_of_mem_dimensionSubring_of_ideal_pow_eq_bot rho
      unitizationIdeal
      (fun y ↦ nonUnitalCommutatorToUnitization_mem
        (sourceProbe N q r hr y))
      (N + 4) (unitizationIdeal_pow_eq_bot q r (N + 4) hr (by omega)) hz
  change (show Ring q r from sourceProbe N q r hr z) = 0
  apply Unitization.inr_injective (R := ℤ) (A := Ring q r)
  simpa [rho] using hzero

/-! ## Exact Hall evaluation -/

/-- The commutative Magnus monomial attached recursively to a metabelian
Hall index.  It is the product of one variable for every occurrence in the
Hall word. -/
def hallProduct (q r : ℕ) :
    (s : ℕ) → FreeMetabelian.HallIndex Generator s → positiveIdeal q r
  | 0, h => varImage q r h.head * varImage q r h.pivot
  | s + 1, h => varImage q r h.nextTooth * hallProduct q r s h.predecessor

/-- The alternating sign introduced by successive right brackets. -/
def hallSign : ℕ → ℤ
  | 0 => 1
  | s + 1 => -hallSign s

/-- The exponent vector of the commutative monomial attached to a Hall
index.  This records exactly one copy of each generator occurrence. -/
def hallExponent :
    (s : ℕ) → FreeMetabelian.HallIndex Generator s → Generator →₀ ℕ
  | 0, h => Finsupp.single h.head 1 + Finsupp.single h.pivot 1
  | s + 1, h =>
      Finsupp.single h.nextTooth 1 + hallExponent s h.predecessor

/-- A Hall word with `s` right teeth has total Magnus degree `s+2`. -/
@[simp] theorem hallExponent_degree :
    ∀ (s : ℕ) (h : FreeMetabelian.HallIndex Generator s),
      Finsupp.degree (hallExponent s h) = s + 2 := by
  intro s
  induction s with
  | zero =>
      intro h
      simp [hallExponent, Finsupp.degree_add, Finsupp.degree_single]
  | succ s ih =>
      intro h
      simp [hallExponent, Finsupp.degree_add, Finsupp.degree_single,
        ih h.predecessor]
      omega

@[simp] theorem hallSign_zero : hallSign 0 = 1 := rfl
@[simp] theorem hallSign_succ (s : ℕ) : hallSign (s + 1) = -hallSign s := rfl

private theorem mul_zsmul_right (q r : ℕ)
    (x y : positiveIdeal q r) (z : ℤ) :
    x * (z • y) = z • (x * y) := by
  let f : positiveIdeal q r →+ positiveIdeal q r :=
    { toFun := fun y ↦ x * y
      map_zero' := mul_zero x
      map_add' := mul_add x }
  exact f.map_zsmul y z

private theorem neg_zsmul_eq (q r : ℕ) (z : ℤ)
    (x : positiveIdeal q r) :
    -(z • x) = (-z) • x :=
  (neg_smul z x).symm

@[simp] theorem hallProduct_zero (q r : ℕ)
    (h : FreeMetabelian.HallIndex Generator 0) :
    hallProduct q r 0 h = varImage q r h.head * varImage q r h.pivot := rfl

@[simp] theorem hallProduct_succ (q r s : ℕ)
    (h : FreeMetabelian.HallIndex Generator (s + 1)) :
    hallProduct q r (s + 1) h =
      varImage q r h.nextTooth * hallProduct q r s h.predecessor := rfl

/-- The recursively defined Hall product is the image of its literal monic
monomial in the truncated polynomial ring. -/
theorem hallProduct_coe (q r : ℕ) :
    ∀ (s : ℕ) (h : FreeMetabelian.HallIndex Generator s),
      ((hallProduct q r s h : positiveIdeal q r) : TruncatedPoly q r) =
        Ideal.Quotient.mk (variableIdeal q ^ r)
          (MvPolynomial.monomial (hallExponent s h) 1) := by
  intro s
  induction s with
  | zero =>
      intro h
      change
        Ideal.Quotient.mk (variableIdeal q ^ r) (MvPolynomial.X h.head) *
            Ideal.Quotient.mk (variableIdeal q ^ r) (MvPolynomial.X h.pivot) = _
      rw [← map_mul]
      change Ideal.Quotient.mk (variableIdeal q ^ r)
          (MvPolynomial.monomial (Finsupp.single h.head 1) 1 *
            MvPolynomial.monomial (Finsupp.single h.pivot 1) 1) =
        Ideal.Quotient.mk (variableIdeal q ^ r)
          (MvPolynomial.monomial
            (Finsupp.single h.head 1 + Finsupp.single h.pivot 1) 1)
      rw [MvPolynomial.monomial_mul]
      simp
  | succ s ih =>
      intro h
      rw [hallProduct_succ]
      change
        Ideal.Quotient.mk (variableIdeal q ^ r) (MvPolynomial.X h.nextTooth) *
            ((hallProduct q r s h.predecessor : positiveIdeal q r) :
              TruncatedPoly q r) = _
      rw [ih h.predecessor]
      rw [← map_mul]
      change Ideal.Quotient.mk (variableIdeal q ^ r)
          (MvPolynomial.monomial (Finsupp.single h.nextTooth 1) 1 *
            MvPolynomial.monomial (hallExponent s h.predecessor) 1) =
        Ideal.Quotient.mk (variableIdeal q ^ r)
          (MvPolynomial.monomial
            (Finsupp.single h.nextTooth 1 + hallExponent s h.predecessor) 1)
      rw [MvPolynomial.monomial_mul]
      simp

/-- Coefficient extraction below the truncation degree.  A coefficient of
degree `< r` vanishes on the ideal of terms of degree at least `r`, so it is
well-defined on the truncated polynomial ring. -/
def truncatedCoeff (q r : ℕ) (e : Generator →₀ ℕ)
    (he : Finsupp.degree e < r) :
    TruncatedPoly q r →+ ZMod q :=
  QuotientAddGroup.lift (variableIdeal q ^ r).toAddSubgroup
    (MvPolynomial.coeffAddMonoidHom e) (by
      intro p hp
      exact (MvPolynomial.mem_pow_idealOfVars_iff' r p).mp hp e he)

@[simp] theorem truncatedCoeff_mk (q r : ℕ) (e : Generator →₀ ℕ)
    (he : Finsupp.degree e < r) (p : Poly q) :
    truncatedCoeff q r e he
        (Ideal.Quotient.mk (variableIdeal q ^ r) p) =
      MvPolynomial.coeff e p := by
  rfl

/-- The distinguished coefficient of a Hall product is one whenever that
monomial survives the truncation. -/
theorem truncatedCoeff_hallProduct (q r s : ℕ)
    (h : FreeMetabelian.HallIndex Generator s) (hs : s + 2 < r) :
    truncatedCoeff q r (hallExponent s h) (by simpa using hs)
        ((hallProduct q r s h : positiveIdeal q r) : TruncatedPoly q r) = 1 := by
  rw [hallProduct_coe, truncatedCoeff_mk]
  simp

@[simp] theorem sourceProbe_hallBracket_scalar
    (N q r : ℕ) (hr : r ≤ N + 4) (s : ℕ)
    (h : FreeMetabelian.HallIndex Generator s)
    (hs : s + 1 < N + 3) :
    (sourceProbe N q r hr
      (FreeMetabelian.Evaluation.hallBracket generatorBasis s h hs)).scalar = 0 := by
  cases s with
  | zero =>
      rw [FreeMetabelian.Evaluation.hallBracket, LieHom.map_lie,
        Target.scalar_lie]
  | succ s =>
      rw [FreeMetabelian.Evaluation.hallBracket, LieHom.map_lie,
        Target.scalar_lie]

set_option maxHeartbeats 1000000 in
/-- Evaluation of a literal Hall bracket in the Magnus probe.  The two
nonzero vector coordinates are its pivot and head; each right tooth changes
the sign once. -/
theorem sourceProbe_hallBracket_vector
    (N q r : ℕ) (hr : r ≤ N + 4) :
    ∀ (s : ℕ) (h : FreeMetabelian.HallIndex Generator s)
      (hs : s + 1 < N + 3) (j : Generator),
      (sourceProbe N q r hr
          (FreeMetabelian.Evaluation.hallBracket generatorBasis s h hs)).vector j =
        hallSign s •
          ((if h.pivot = j then hallProduct q r s h else 0) -
            (if h.head = j then hallProduct q r s h else 0)) := by
  intro s
  induction s with
  | zero =>
      intro h hs j
      rw [FreeMetabelian.Evaluation.hallBracket]
      change (sourceProbe N q r hr
          ⁅sourceGenerator N h.head, sourceGenerator N h.pivot⁆).vector j = _
      rw [LieHom.map_lie, sourceProbe_sourceGenerator,
        sourceProbe_sourceGenerator, Target.vector_lie]
      simp only [Ring.generator_scalar, Ring.generator_vector,
        hallProduct_zero, hallSign_zero]
      by_cases hp : h.pivot = j <;> by_cases hh : h.head = j <;>
        simp [hp, hh, mul_comm] <;> module
  | succ s ih =>
      intro h hs j
      have hnext : sourceProbe N q r hr
          (FreeMetabelian.Free.incl (⟨0, by omega⟩ : Fin (N + 3))
            (generatorBasis h.nextTooth)) = Ring.generator q r h.nextTooth := by
        change sourceProbe N q r hr (sourceGenerator N h.nextTooth) = _
        exact sourceProbe_sourceGenerator N q r hr h.nextTooth
      have hprevScalar :
          (sourceProbe N q r hr
            (FreeMetabelian.Evaluation.hallBracket generatorBasis s
              h.predecessor (by omega))).scalar = 0 :=
        sourceProbe_hallBracket_scalar N q r hr s h.predecessor (by omega)
      rw [FreeMetabelian.Evaluation.hallBracket, LieHom.map_lie,
        Target.vector_lie]
      rw [ih h.predecessor (by omega) j, hnext, hprevScalar]
      simp only [zero_mul, Ring.generator_scalar,
        hallProduct_succ]
      have hhead : h.predecessor.head = h.head := rfl
      have hpivot : h.predecessor.pivot = h.pivot := rfl
      rw [hhead, hpivot]
      by_cases hp : h.pivot = j
      · by_cases hh : h.head = j
        · simp [hp, hh, hallSign_succ, mul_comm, smul_mul_assoc]
          exact neg_zsmul_eq q r (hallSign s) 0
        · simp [hp, hh, hallSign_succ, mul_comm, smul_mul_assoc]
          exact neg_zsmul_eq q r (hallSign s)
            (hallProduct q r s h.predecessor * varImage q r h.nextTooth)
      · by_cases hh : h.head = j
        · simp [hp, hh, hallSign_succ, mul_comm, smul_mul_assoc]
          rw [neg_mul (hallProduct q r s h.predecessor)
            (varImage q r h.nextTooth)]
          exact neg_zsmul_eq q r (hallSign s)
            (-(hallProduct q r s h.predecessor * varImage q r h.nextTooth))
        · simp [hp, hh, hallSign_succ, mul_comm, smul_mul_assoc]
          exact neg_zsmul_eq q r (hallSign s) 0

end MagnusProbe

end

end LieRings.FinitePlateau
