import LieRings.DimensionSubring.MetabelianVanishing.QuadraticPBWBlock
import Mathlib.Util.AssertNoSorry

/-! Compile gates for Points 4, 5, and 6 of the implementation plan. -/

assert_no_sorry LieRings.MetabelianVanishing.transgression
assert_no_sorry LieRings.MetabelianVanishing.exact_D_augmentation
assert_no_sorry LieRings.MetabelianVanishing.extensionTail_relation
assert_no_sorry LieRings.MetabelianVanishing.Phi_comp_dTwo
assert_no_sorry LieRings.MetabelianVanishing.T_homogeneous_ne_zero_shape
assert_no_sorry LieRings.MetabelianVanishing.eta_comp_map_pi
assert_no_sorry LieRings.MetabelianVanishing.rExact
assert_no_sorry Koszul.QuadraticUCT.horizontal_cycle
assert_no_sorry Koszul.QuadraticUCT.dTwo_twoGenerator
assert_no_sorry Koszul.QuadraticUCT.cycle_eq_horizontalExpansion
assert_no_sorry LieRings.MetabelianVanishing.terminalPhi_bockstein_eq_two_eta
assert_no_sorry LieRings.MetabelianVanishing.certificatePsi_bockstein_eq_eta
assert_no_sorry LieRings.MetabelianVanishing.etaTerminal_comp_map_pi_eq_zero

assert_no_sorry LieRings.PBW.WeightedBasis.augmentationIdeal_pow_eq_weightGE
assert_no_sorry LieRings.PBW.WeightedBasis.factorProj_one_iota
assert_no_sorry LieRings.MetabelianVanishing.exists_governingWitness
assert_no_sorry LieRings.MetabelianVanishing.quadraticHorizontalPlacedRow_proj
assert_no_sorry LieRings.MetabelianVanishing.quadraticPQPlacedRow_proj
assert_no_sorry LieRings.MetabelianVanishing.quadraticQPPlacedRow_proj
assert_no_sorry LieRings.MetabelianVanishing.quadraticQQPlacedRow_proj
assert_no_sorry LieRings.MetabelianVanishing.quadraticHorizontalPlacedRow_factorProj
assert_no_sorry LieRings.MetabelianVanishing.quadraticPQPlacedRow_factorProj
assert_no_sorry LieRings.MetabelianVanishing.quadraticQPPlacedRow_factorProj
assert_no_sorry LieRings.MetabelianVanishing.quadraticQQPlacedRow_factorProj
assert_no_sorry LieRings.MetabelianVanishing.topCoord_quadratic_bracket_eq_terminalPhi
assert_no_sorry LieRings.MetabelianVanishing.quadraticBlockPlacedWord_proj_eq_weightIncl
assert_no_sorry LieRings.MetabelianVanishing.quadraticBlockPlacedWord_factorProj_eq_weightIncl
assert_no_sorry LieRings.MetabelianVanishing.quadraticBlockValue_eq_coordinate
assert_no_sorry LieRings.MetabelianVanishing.quadraticBlockValue_capstone
assert_no_sorry LieRings.MetabelianVanishing.terminalFullLift_prefix
assert_no_sorry LieRings.MetabelianVanishing.relation_sub_terminalFullLift_eq_top
assert_no_sorry LieRings.MetabelianVanishing.terminalPieceEvaluation_surjective
assert_no_sorry LieRings.MetabelianVanishing.terminalGeneratorTopCorrection_spec
assert_no_sorry LieRings.MetabelianVanishing.terminalGeneratorRealizationDefect
assert_no_sorry LieRings.MetabelianVanishing.terminalRelationRealizationDefect
assert_no_sorry LieRings.MetabelianVanishing.TerminalRowCertificate.value_eq
assert_no_sorry LieRings.MetabelianVanishing.TerminalMarkedWord.primitive_eq_of_word_eq
assert_no_sorry LieRings.MetabelianVanishing.transportTerminalPacket_comparison
