import LieRings.UniversalEnveloping.Quotient

/-!
# The central derivative module

For a central Lie ideal `D` in a Lie ring `E`, this file constructs the quotient

`d(E) / (U(E) D) d(E)`

and its natural action by `E / D`.  The separate PBW coefficient theorem asserting that the copy
of `D` is an additive direct summand is deliberately not folded into this construction.
-/

namespace LieRings.Plotkin

noncomputable section

universe u

variable (E : Type u) [LieRing E]
variable (D : LieIdeal ℤ E)

namespace CentralDerivative

/-- The augmentation ideal, used as the numerator of the derivative module. -/
abbrev Augmentation := UEA.augmentationIdeal ℤ E

/-- The two-sided ideal generated by `D`, multiplied by the augmentation ideal. -/
def productIdeal : Ideal (UEA ℤ E) :=
  UEA.idealOfLieIdeal ℤ E D * UEA.augmentationIdeal ℤ E

instance productIdeal_isTwoSided : (productIdeal E D).IsTwoSided := by
  dsimp [productIdeal]
  infer_instance

/-- The denominator, regarded inside the augmentation ideal. -/
def denominator : Submodule ℤ (Augmentation E) :=
  ((productIdeal E D).restrictScalars ℤ).comap
    ((Augmentation E).subtype.restrictScalars ℤ)

/-- The central derivative module `d(E) / D d(E)`. -/
abbrev Derivative := Augmentation E ⧸ denominator E D

/-- Left multiplication by a generator of `E` preserves the augmentation ideal. -/
def leftAction (e : E) : Module.End ℤ (Augmentation E) where
  toFun v :=
    ⟨UniversalEnvelopingAlgebra.ι ℤ e * (v : UEA ℤ E),
      (Augmentation E).mul_mem_left _ v.property⟩
  map_add' v w := by ext; simp [mul_add]
  map_smul' z v := by
    ext
    simp only [RingHom.id_apply, Submodule.coe_smul_of_tower]
    rw [mul_smul_comm]

@[simp]
theorem leftAction_coe (e : E) (v : Augmentation E) :
    (leftAction E e v : UEA ℤ E) = UniversalEnvelopingAlgebra.ι ℤ e * v :=
  rfl

instance augmentation_lieRingModule : LieRingModule E (Augmentation E) where
  bracket e v := leftAction E e v
  add_lie e e' v := by
    ext
    simp [leftAction, add_mul]
  lie_add e v w := by
    ext
    simp [leftAction, mul_add]
  leibniz_lie e e' v := by
    ext
    change UniversalEnvelopingAlgebra.ι ℤ e *
        (UniversalEnvelopingAlgebra.ι ℤ e' * (v : UEA ℤ E)) =
      UniversalEnvelopingAlgebra.ι ℤ ⁅e, e'⁆ * (v : UEA ℤ E) +
        UniversalEnvelopingAlgebra.ι ℤ e' *
          (UniversalEnvelopingAlgebra.ι ℤ e * (v : UEA ℤ E))
    rw [LieHom.map_lie, LieRing.of_associative_ring_bracket]
    noncomm_ring

instance augmentation_lieModule : LieModule ℤ E (Augmentation E) where
  smul_lie z e v := by
    ext
    change UniversalEnvelopingAlgebra.ι ℤ (z • e) * (v : UEA ℤ E) =
      z • (UniversalEnvelopingAlgebra.ι ℤ e * (v : UEA ℤ E))
    rw [map_smul, smul_mul_assoc]
  lie_smul z e v := by
    ext
    change UniversalEnvelopingAlgebra.ι ℤ e * (z • (v : UEA ℤ E)) =
      z • (UniversalEnvelopingAlgebra.ι ℤ e * (v : UEA ℤ E))
    rw [mul_smul_comm]

/-- The denominator is stable under the left `E`-action. -/
def denominatorLieSubmodule : LieSubmodule ℤ E (Augmentation E) where
  toSubmodule := denominator E D
  lie_mem {e v} hv := by
    change UniversalEnvelopingAlgebra.ι ℤ e * (v : UEA ℤ E) ∈ productIdeal E D
    exact (productIdeal E D).mul_mem_left _ hv

/-- The quotient inherits the left action of `E`. -/
instance derivative_lieRingModule : LieRingModule E (Derivative E D) :=
  LieSubmodule.Quotient.lieQuotientLieRingModule (denominatorLieSubmodule E D)

instance derivative_lieModule : LieModule ℤ E (Derivative E D) :=
  LieSubmodule.Quotient.lieQuotientLieModule (denominatorLieSubmodule E D)

/-- The canonical map from `E` into its augmentation ideal. -/
def toAugmentation : E →ₗ[ℤ] Augmentation E where
  toFun e := ⟨UniversalEnvelopingAlgebra.ι ℤ e,
    UEA.ι_mem_augmentationIdeal ℤ E e⟩
  map_add' e e' := by ext; simp
  map_smul' z e := by ext; simp

/-- The class of a Lie-ring element in the derivative module. -/
def bar : E →ₗ[ℤ] Derivative E D :=
  (denominator E D).mkQ.comp (toAugmentation E)

@[simp]
theorem bar_apply (e : E) :
    bar E D e = Submodule.Quotient.mk
      ⟨UniversalEnvelopingAlgebra.ι ℤ e, UEA.ι_mem_augmentationIdeal ℤ E e⟩ :=
  rfl

/-- Every element of `D` acts trivially on the derivative quotient. -/
theorem lie_eq_zero_of_mem (d : E) (hd : d ∈ D) (v : Derivative E D) :
    ⁅d, v⁆ = 0 := by
  induction v using Submodule.Quotient.induction_on with
  | _ v =>
      change Submodule.Quotient.mk (leftAction E d v) = 0
      rw [Submodule.Quotient.mk_eq_zero]
      change UniversalEnvelopingAlgebra.ι ℤ d * (v : UEA ℤ E) ∈ productIdeal E D
      exact Ideal.mul_mem_mul
        (UEA.ι_mem_idealOfLieIdeal ℤ E D ⟨d, hd⟩) v.property

/-- The ideal `D` lies in the kernel of the left action. -/
theorem actionKernel : D.toSubmodule ≤
    (LieModule.toEnd ℤ E (Derivative E D)).toLinearMap.ker := by
  intro d hd
  rw [LinearMap.mem_ker]
  exact LinearMap.ext fun v ↦ lie_eq_zero_of_mem E D d hd v

/-- The `E`-action on the derivative module factors through `E / D`. -/
def quotientAction :
    E ⧸ D →ₗ⁅ℤ⁆ Module.End ℤ (Derivative E D) where
  toLinearMap := D.toSubmodule.liftQ
    (LieModule.toEnd ℤ E (Derivative E D)).toLinearMap (actionKernel E D)
  map_lie' := by
    intro x y
    induction x using Submodule.Quotient.induction_on with
    | _ x =>
      induction y using Submodule.Quotient.induction_on with
      | _ y =>
        rw [← LieSubmodule.Quotient.mk_bracket]
        change D.toSubmodule.liftQ
            (LieModule.toEnd ℤ E (Derivative E D)).toLinearMap (actionKernel E D)
              (Submodule.Quotient.mk ⁅x, y⁆) =
          ⁅D.toSubmodule.liftQ
              (LieModule.toEnd ℤ E (Derivative E D)).toLinearMap (actionKernel E D)
                (Submodule.Quotient.mk x),
            D.toSubmodule.liftQ
              (LieModule.toEnd ℤ E (Derivative E D)).toLinearMap (actionKernel E D)
                (Submodule.Quotient.mk y)⁆
        rw [Submodule.liftQ_apply, Submodule.liftQ_apply, Submodule.liftQ_apply]
        exact LieHom.map_lie (LieModule.toEnd ℤ E (Derivative E D)) x y

@[simp]
theorem quotientAction_mk (e : E) :
    quotientAction E D (LieSubmodule.Quotient.mk e) =
      LieModule.toEnd ℤ E (Derivative E D) e :=
  rfl

instance quotient_lieRingModule : LieRingModule (E ⧸ D) (Derivative E D) :=
  LieRingModule.compLieHom _ (quotientAction E D)

instance quotient_lieModule : LieModule ℤ (E ⧸ D) (Derivative E D) :=
  LieModule.compLieHom _ (quotientAction E D)

@[simp]
theorem quotient_lie_mk (e : E) (v : Derivative E D) :
    ⁅(LieSubmodule.Quotient.mk e : E ⧸ D), v⁆ = ⁅e, v⁆ :=
  rfl

/-- The defining derivative identity in the quotient module. -/
theorem bar_bracket (e e' : E) :
    bar E D ⁅e, e'⁆ =
      ⁅(LieSubmodule.Quotient.mk e : E ⧸ D), bar E D e'⁆ -
        ⁅(LieSubmodule.Quotient.mk e' : E ⧸ D), bar E D e⁆ := by
  change (denominator E D).mkQ (toAugmentation E ⁅e, e'⁆) =
    (denominator E D).mkQ (leftAction E e (toAugmentation E e')) -
      (denominator E D).mkQ (leftAction E e' (toAugmentation E e))
  rw [← map_sub]
  apply congrArg ((denominator E D).mkQ)
  ext
  change UniversalEnvelopingAlgebra.ι ℤ ⁅e, e'⁆ =
    UniversalEnvelopingAlgebra.ι ℤ e * UniversalEnvelopingAlgebra.ι ℤ e' -
      UniversalEnvelopingAlgebra.ι ℤ e' * UniversalEnvelopingAlgebra.ι ℤ e
  rw [LieHom.map_lie, LieRing.of_associative_ring_bracket]

/-- Elements coming from `D` are annihilated by the quotient Lie ring. -/
theorem quotient_lie_bar_eq_zero
    (hcentral : D ≤ LieAlgebra.center ℤ E)
    (d : E) (hd : d ∈ D) (x : E ⧸ D) :
    ⁅x, bar E D d⁆ = 0 := by
  induction x using Submodule.Quotient.induction_on with
  | _ e =>
      change (denominator E D).mkQ
          (leftAction E e (toAugmentation E d)) = 0
      change Submodule.Quotient.mk
          (leftAction E e (toAugmentation E d)) = 0
      rw [Submodule.Quotient.mk_eq_zero]
      change UniversalEnvelopingAlgebra.ι ℤ e *
          UniversalEnvelopingAlgebra.ι ℤ d ∈ productIdeal E D
      have hzero : ⁅e, d⁆ = 0 := by
        exact (LieModule.mem_maxTrivSubmodule ℤ E E d).mp (hcentral hd) e
      have hcomm : UniversalEnvelopingAlgebra.ι ℤ e *
          UniversalEnvelopingAlgebra.ι ℤ d =
          UniversalEnvelopingAlgebra.ι ℤ d * UniversalEnvelopingAlgebra.ι ℤ e := by
        apply sub_eq_zero.mp
        rw [← LieRing.of_associative_ring_bracket, ← LieHom.map_lie, hzero, map_zero]
      rw [hcomm]
      exact Ideal.mul_mem_mul
        (UEA.ι_mem_idealOfLieIdeal ℤ E D ⟨d, hd⟩)
        (UEA.ι_mem_augmentationIdeal ℤ E e)

end CentralDerivative

end

end LieRings.Plotkin
