import LieRings.UniversalEnveloping.Basic
import Mathlib.Tactic.Module

/-!
# The adjoint action of the universal enveloping algebra

The given action of a Lie algebra `L` on a Lie module `M` extends canonically to an action of
`U(L)`.  The key result here is that an element of the `n`th power of the augmentation ideal sends
a Lie submodule `N` into its `n`th relative lower-central term.
-/

namespace LieRings

universe u v w

variable (R : Type u) (L : Type v) (M : Type w)
variable [CommRing R] [LieRing L] [LieAlgebra R L]
variable [AddCommGroup M] [Module R M] [LieRingModule L M] [LieModule R L M]

namespace UEA

/-- The representation of `U(L)` induced by a Lie-module structure on `M`. -/
def representation : UEA R L →ₐ[R] Module.End R M :=
  UniversalEnvelopingAlgebra.lift R (LieModule.toEnd R L M)

@[simp]
theorem representation_ι_apply (x : L) (m : M) :
    representation R L M (UniversalEnvelopingAlgebra.ι R x) m = ⁅x, m⁆ := by
  simp [representation]

@[simp]
theorem representation_algebraMap_apply (r : R) (m : M) :
    representation R L M (algebraMap R (UEA R L) r) m = r • m := by
  simp [representation]

@[simp]
theorem representation_mul_apply (u v : UEA R L) (m : M) :
    representation R L M (u * v) m = representation R L M u (representation R L M v m) := by
  simp [representation]

/-- Every Lie submodule is stable under the induced `U(L)`-representation. -/
theorem representation_mem (N : LieSubmodule R L M) (u : UEA R L) {m : M} (hm : m ∈ N) :
    representation R L M u m ∈ N := by
  induction u using UEA.induction R L generalizing m with
  | algebraMap r => simpa using N.smul_mem r hm
  | ι x => simpa [representation] using N.lie_mem (x := x) hm
  | add u v hu hv => simpa using N.add_mem (hu hm) (hv hm)
  | mul u v hu hv => simpa using hu (hv hm)

/--
For every `u ∈ U(L)`, its action differs from multiplication by its augmentation by an element
of `[L,N]`.  This is the one-step engine behind dimension centrality.
-/
theorem representation_sub_augmentation_smul_mem
    (N : LieSubmodule R L M) (u : UEA R L) {m : M} (hm : m ∈ N) :
    representation R L M u m - augmentation R L u • m ∈ ⁅(⊤ : LieIdeal R L), N⁆ := by
  induction u using UEA.induction R L with
  | algebraMap r => simp
  | ι x =>
      simpa [representation, augmentation] using
        LieSubmodule.lie_mem_lie (I := (⊤ : LieIdeal R L))
          (N := N) (by simp : x ∈ (⊤ : LieIdeal R L)) hm
  | add u v hu hv =>
      rw [show representation R L M (u + v) m - augmentation R L (u + v) • m =
          (representation R L M u m - augmentation R L u • m) +
            (representation R L M v m - augmentation R L v • m) by
        simp only [map_add, LinearMap.add_apply, add_smul]
        module]
      exact (⁅(⊤ : LieIdeal R L), N⁆).add_mem hu hv
  | mul u v hu hv =>
      have h₁ := representation_mem R L M ⁅(⊤ : LieIdeal R L), N⁆ u hv
      have h₂ := (⁅(⊤ : LieIdeal R L), N⁆).smul_mem (augmentation R L v) hu
      rw [show representation R L M (u * v) m - augmentation R L (u * v) • m =
          representation R L M u
              (representation R L M v m - augmentation R L v • m) +
            augmentation R L v •
              (representation R L M u m - augmentation R L u • m) by
        simp only [map_mul, Module.End.mul_apply, map_sub,
          LinearMap.map_smul_of_tower, mul_smul]
        module]
      exact (⁅(⊤ : LieIdeal R L), N⁆).add_mem h₁ h₂

/-- An element of the augmentation ideal sends `N` into `[L,N]`. -/
theorem augmentationIdeal_action_mem
    (N : LieSubmodule R L M) {u : UEA R L} (hu : u ∈ augmentationIdeal R L)
    {m : M} (hm : m ∈ N) :
    representation R L M u m ∈ ⁅(⊤ : LieIdeal R L), N⁆ := by
  have h := representation_sub_augmentation_smul_mem R L M N u hm
  rw [mem_augmentationIdeal] at hu
  simpa [hu] using h

/--
If `u ∈ 𝜔(L)^n`, then `u` sends `N` into its `n`th relative lower-central term.
-/
theorem augmentationIdeal_pow_action_mem
    (N : LieSubmodule R L M) (n : ℕ) {u : UEA R L}
    (hu : u ∈ augmentationIdeal R L ^ n) {m : M} (hm : m ∈ N) :
    representation R L M u m ∈ N.lcs n := by
  induction n generalizing u m with
  | zero => simpa using representation_mem R L M N u hm
  | succ n ih =>
      rw [Ideal.IsTwoSided.pow_succ] at hu
      refine Submodule.mul_induction_on hu ?_ ?_
      · intro i hi j hj
        rw [representation_mul_apply]
        simpa only [LieSubmodule.lcs_succ] using
          augmentationIdeal_action_mem R L M (N.lcs n) hi (ih hj hm)
      · intro x y hx hy
        simpa using (N.lcs (n + 1)).add_mem hx hy

/--
The `R`-submodule generated by all values `u • m`, with `u ∈ I` and `m ∈ N`, for the
representation of `U(L)` induced by the Lie-module structure.
-/
def actionSubmodule (I : Ideal (UEA R L)) (N : LieSubmodule R L M) : Submodule R M :=
  Submodule.span R {z | ∃ u, u ∈ I ∧ ∃ m, m ∈ N ∧ representation R L M u m = z}

/-- A single action value belongs to the submodule generated by all such values. -/
theorem action_mem_actionSubmodule (I : Ideal (UEA R L)) (N : LieSubmodule R L M)
    {u : UEA R L} (hu : u ∈ I) {m : M} (hm : m ∈ N) :
    representation R L M u m ∈ actionSubmodule R L M I N := by
  apply Submodule.subset_span
  exact ⟨u, hu, m, hm, rfl⟩

/--
The adjoint-module identity
`N · 𝜔(L)^n = [N, L, ..., L]`, with `L` occurring `n` times.

The left-hand side is `actionSubmodule`; the right-hand side is mathlib's relative lower-central
series `N.lcs n`.
-/
theorem actionSubmodule_augmentationIdeal_pow_eq_lcs
    (N : LieSubmodule R L M) (n : ℕ) :
    actionSubmodule R L M (augmentationIdeal R L ^ n) N =
      (N.lcs n : Submodule R M) := by
  apply le_antisymm
  · rw [actionSubmodule, Submodule.span_le]
    rintro _ ⟨u, hu, m, hm, rfl⟩
    exact augmentationIdeal_pow_action_mem R L M N n hu hm
  · induction n with
    | zero =>
        intro m hm
        have hOne : (1 : UEA R L) ∈ augmentationIdeal R L ^ 0 := by
          rw [Submodule.pow_zero, Ideal.one_eq_top]
          trivial
        simpa using action_mem_actionSubmodule R L M
          (augmentationIdeal R L ^ 0) N hOne hm
    | succ n ih =>
        rw [LieSubmodule.lcs_succ, LieSubmodule.lieIdeal_oper_eq_linear_span',
          Submodule.span_le]
        rintro _ ⟨x, _, y, hy, rfl⟩
        have hy' := ih hy
        clear hy
        rw [actionSubmodule] at hy'
        induction hy' using Submodule.span_induction with
        | mem z hz =>
            obtain ⟨u, hu, m, hm, rfl⟩ := hz
            have hxu : UniversalEnvelopingAlgebra.ι R x * u ∈
                augmentationIdeal R L ^ (n + 1) := by
              rw [Ideal.IsTwoSided.pow_succ]
              exact Ideal.mul_mem_mul (ι_mem_augmentationIdeal R L x) hu
            simpa [representation] using action_mem_actionSubmodule R L M
              (augmentationIdeal R L ^ (n + 1)) N hxu hm
        | zero => simp
        | add y z _ _ hy hz => simpa [lie_add] using
            (actionSubmodule R L M (augmentationIdeal R L ^ (n + 1)) N).add_mem hy hz
        | smul r y _ hy => simpa [lie_smul] using
            (actionSubmodule R L M (augmentationIdeal R L ^ (n + 1)) N).smul_mem r hy

end UEA

end LieRings
