import LieRings.UniversalEnveloping.Basic
import Mathlib.Algebra.Lie.Quotient
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Universal enveloping algebras of Lie quotients

If `I` is a Lie ideal of `L`, then

`U(L ⧸ I) ≃ U(L) ⧸ ⟨ι(I)⟩`,

where the ideal on the right is the two-sided ideal generated by the canonical image of `I`.
This is Proposition 4.2 of Bartholdi--Passi, in a form that does not require `L` to be free.
-/

namespace LieRings

universe u v

variable (R : Type u) (L : Type v)
variable [CommRing R] [LieRing L] [LieAlgebra R L]

namespace UEA

/-- The two-sided ideal of `U(L)` generated by the canonical image of a Lie ideal `I`. -/
def idealOfLieIdeal (I : LieIdeal R L) : Ideal (UEA R L) :=
  (TwoSidedIdeal.span
    (Set.range fun x : I ↦ UniversalEnvelopingAlgebra.ι R (x : L))).asIdeal

instance idealOfLieIdeal_isTwoSided (I : LieIdeal R L) :
    (idealOfLieIdeal R L I).IsTwoSided :=
  show ((TwoSidedIdeal.span
    (Set.range fun x : I ↦ UniversalEnvelopingAlgebra.ι R (x : L))).asIdeal).IsTwoSided from
      inferInstance

/-- Every canonical generator coming from `I` belongs to the ideal generated by `I`. -/
theorem ι_mem_idealOfLieIdeal (I : LieIdeal R L) (x : I) :
    UniversalEnvelopingAlgebra.ι R (x : L) ∈ idealOfLieIdeal R L I := by
  exact TwoSidedIdeal.subset_span ⟨x, rfl⟩

/-- The canonical Lie homomorphism from `L` to its quotient by `I`. -/
def lieIdealQuotientMk (I : LieIdeal R L) : L →ₗ⁅R⁆ L ⧸ I :=
  { I.toSubmodule.mkQ with
    map_lie' := fun {x y} ↦ LieSubmodule.Quotient.mk_bracket I x y }

@[simp]
theorem lieIdealQuotientMk_apply (I : LieIdeal R L) (x : L) :
    lieIdealQuotientMk R L I x = LieSubmodule.Quotient.mk x :=
  rfl

/-- The algebra map `U(L) → U(L/I)` induced by the quotient map. -/
noncomputable def mapToLieQuotient (I : LieIdeal R L) :
    UEA R L →ₐ[R] UEA R (L ⧸ I) :=
  UniversalEnvelopingAlgebra.lift R
    ((UniversalEnvelopingAlgebra.ι R).comp (lieIdealQuotientMk R L I))

@[simp]
theorem mapToLieQuotient_ι (I : LieIdeal R L) (x : L) :
    mapToLieQuotient R L I (UniversalEnvelopingAlgebra.ι R x) =
      UniversalEnvelopingAlgebra.ι R (LieSubmodule.Quotient.mk x : L ⧸ I) := by
  simp [mapToLieQuotient]

/-- The quotient map `U(L) → U(L)/⟨I⟩`, restricted to `L`. -/
noncomputable def lieHomToIdealQuotient (I : LieIdeal R L) :
    L →ₗ⁅R⁆ UEA R L ⧸ idealOfLieIdeal R L I :=
  ((Ideal.Quotient.mkₐ R (idealOfLieIdeal R L I)).toLieHom).comp
    (UniversalEnvelopingAlgebra.ι R)

theorem lieHomToIdealQuotient_eq_zero_on (I : LieIdeal R L) (x : I) :
    lieHomToIdealQuotient R L I (x : L) = 0 := by
  rw [lieHomToIdealQuotient]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (ι_mem_idealOfLieIdeal R L I x)

/-- The Lie map `L/I → U(L)/⟨I⟩` induced by the canonical map on `L`. -/
noncomputable def lieQuotientToIdealQuotient (I : LieIdeal R L) :
    L ⧸ I →ₗ⁅R⁆ UEA R L ⧸ idealOfLieIdeal R L I where
  toLinearMap := I.toSubmodule.liftQ
    (lieHomToIdealQuotient R L I).toLinearMap
    (fun x hx ↦ by
      rw [LinearMap.mem_ker]
      exact lieHomToIdealQuotient_eq_zero_on R L I ⟨x, hx⟩)
  map_lie' := by
    intro x y
    induction x using Submodule.Quotient.induction_on
    induction y using Submodule.Quotient.induction_on
    change lieHomToIdealQuotient R L I ⁅_, _⁆ =
      ⁅lieHomToIdealQuotient R L I _, lieHomToIdealQuotient R L I _⁆
    exact LieHom.map_lie (lieHomToIdealQuotient R L I) _ _

@[simp]
theorem lieQuotientToIdealQuotient_mk (I : LieIdeal R L) (x : L) :
    lieQuotientToIdealQuotient R L I (LieSubmodule.Quotient.mk x) =
      Ideal.Quotient.mk (idealOfLieIdeal R L I)
        (UniversalEnvelopingAlgebra.ι R x) := by
  rfl

/-- The map `U(L/I) → U(L)/⟨I⟩` induced by the quotient generators. -/
noncomputable def fromLieQuotient (I : LieIdeal R L) :
    UEA R (L ⧸ I) →ₐ[R] UEA R L ⧸ idealOfLieIdeal R L I :=
  UniversalEnvelopingAlgebra.lift R (lieQuotientToIdealQuotient R L I)

@[simp]
theorem fromLieQuotient_ι_mk (I : LieIdeal R L) (x : L) :
    fromLieQuotient R L I
        (UniversalEnvelopingAlgebra.ι R (LieSubmodule.Quotient.mk x : L ⧸ I)) =
      Ideal.Quotient.mk (idealOfLieIdeal R L I)
        (UniversalEnvelopingAlgebra.ι R x) := by
  calc
    fromLieQuotient R L I
        (UniversalEnvelopingAlgebra.ι R (LieSubmodule.Quotient.mk x : L ⧸ I)) =
        lieQuotientToIdealQuotient R L I (LieSubmodule.Quotient.mk x) :=
      UniversalEnvelopingAlgebra.lift_ι_apply R
        (lieQuotientToIdealQuotient R L I) _
    _ = _ := lieQuotientToIdealQuotient_mk R L I x

private theorem idealOfLieIdeal_le_ker_mapToLieQuotient (I : LieIdeal R L) :
    idealOfLieIdeal R L I ≤ RingHom.ker (mapToLieQuotient R L I).toRingHom := by
  intro u hu
  change u ∈ (TwoSidedIdeal.span
    (Set.range fun x : I ↦ UniversalEnvelopingAlgebra.ι R (x : L))).asIdeal at hu
  change u ∈ TwoSidedIdeal.span
    (Set.range fun x : I ↦ UniversalEnvelopingAlgebra.ι R (x : L)) at hu
  induction hu using TwoSidedIdeal.span_induction with
  | mem u hu =>
      obtain ⟨x, rfl⟩ := hu
      rw [RingHom.mem_ker]
      change mapToLieQuotient R L I (UniversalEnvelopingAlgebra.ι R (x : L)) = 0
      rw [mapToLieQuotient_ι]
      have hxq : (LieSubmodule.Quotient.mk (x : L) : L ⧸ I) = 0 :=
        (LieSubmodule.Quotient.mk_eq_zero' (N := I)).2 x.property
      rw [hxq]
      exact map_zero (UniversalEnvelopingAlgebra.ι R)
  | zero => simp
  | add x y _ _ hx hy => simpa using congrArg₂ (· + ·) hx hy
  | neg x _ hx => simpa using congrArg Neg.neg hx
  | left_absorb a x _ hx =>
      rw [RingHom.mem_ker] at hx
      rw [RingHom.mem_ker, map_mul, hx, mul_zero]
  | right_absorb a x _ hx =>
      rw [RingHom.mem_ker] at hx
      rw [RingHom.mem_ker, map_mul, hx, zero_mul]

/-- The map `U(L)/⟨I⟩ → U(L/I)` induced by `L → L/I`. -/
noncomputable def toLieQuotient (I : LieIdeal R L) :
    UEA R L ⧸ idealOfLieIdeal R L I →ₐ[R] UEA R (L ⧸ I) :=
  Ideal.Quotient.liftₐ (idealOfLieIdeal R L I) (mapToLieQuotient R L I)
    (fun _ hu ↦ RingHom.mem_ker.mp (idealOfLieIdeal_le_ker_mapToLieQuotient R L I hu))

@[simp]
theorem toLieQuotient_mk (I : LieIdeal R L) (u : UEA R L) :
    toLieQuotient R L I (Ideal.Quotient.mk (idealOfLieIdeal R L I) u) =
      mapToLieQuotient R L I u := by
  exact Ideal.Quotient.lift_mk _ _ _

@[simp]
theorem toLieQuotient_mk_ι (I : LieIdeal R L) (x : L) :
    toLieQuotient R L I
        (Ideal.Quotient.mk (idealOfLieIdeal R L I)
          (UniversalEnvelopingAlgebra.ι R x)) =
      UniversalEnvelopingAlgebra.ι R (LieSubmodule.Quotient.mk x : L ⧸ I) := by
  change mapToLieQuotient R L I (UniversalEnvelopingAlgebra.ι R x) = _
  exact mapToLieQuotient_ι R L I x

/-- **Universal enveloping algebra of a Lie quotient.**

`U(L/I)` is canonically isomorphic to `U(L)` modulo the two-sided ideal generated by `I`.
-/
noncomputable def quotientEquivLieIdeal (I : LieIdeal R L) :
    UEA R (L ⧸ I) ≃ₐ[R] UEA R L ⧸ idealOfLieIdeal R L I :=
  AlgEquiv.ofAlgHom (fromLieQuotient R L I) (toLieQuotient R L I)
    (by
      apply Ideal.Quotient.algHom_ext
      apply UniversalEnvelopingAlgebra.hom_ext
      ext x
      change fromLieQuotient R L I
          (toLieQuotient R L I
            (Ideal.Quotient.mk (idealOfLieIdeal R L I)
              (UniversalEnvelopingAlgebra.ι R x))) =
        Ideal.Quotient.mk (idealOfLieIdeal R L I)
          (UniversalEnvelopingAlgebra.ι R x)
      rw [toLieQuotient_mk, mapToLieQuotient_ι, fromLieQuotient_ι_mk])
    (by
      apply UniversalEnvelopingAlgebra.hom_ext
      ext x
      induction x using Submodule.Quotient.induction_on
      change toLieQuotient R L I
          (fromLieQuotient R L I
            (UniversalEnvelopingAlgebra.ι R
              (LieSubmodule.Quotient.mk _ : L ⧸ I))) =
        UniversalEnvelopingAlgebra.ι R (LieSubmodule.Quotient.mk _ : L ⧸ I)
      rw [fromLieQuotient_ι_mk, toLieQuotient_mk, mapToLieQuotient_ι])

@[simp]
theorem quotientEquivLieIdeal_ι_mk (I : LieIdeal R L) (x : L) :
    quotientEquivLieIdeal R L I
        (UniversalEnvelopingAlgebra.ι R (LieSubmodule.Quotient.mk x : L ⧸ I)) =
      Ideal.Quotient.mk (idealOfLieIdeal R L I)
        (UniversalEnvelopingAlgebra.ι R x) := by
  exact fromLieQuotient_ι_mk R L I x

end UEA

end LieRings
