import LieRings.UniversalEnveloping.Quotient
import Mathlib.Tactic.NoncommRing

/-!
# Collecting enveloping-algebra relations on the left

For a Lie ideal `I` of `F`, the two-sided ideal generated by `I` is the
linear span of products `ι(r)u`.  This is the exact relation-collection
statement used by the two-factor proof.
-/

namespace LieRings.UEA

universe u v

noncomputable section

variable (R : Type u) (F : Type v)
variable [CommRing R] [LieRing F] [LieAlgebra R F]

/-- Moving one Lie generator past another creates their Lie bracket. -/
theorem iota_mul_iota_swap (x y : F) :
    UniversalEnvelopingAlgebra.ι R x * UniversalEnvelopingAlgebra.ι R y =
      UniversalEnvelopingAlgebra.ι R y * UniversalEnvelopingAlgebra.ι R x +
        UniversalEnvelopingAlgebra.ι R ⁅x, y⁆ := by
  have h := LieHom.map_lie (UniversalEnvelopingAlgebra.ι R) x y
  change UniversalEnvelopingAlgebra.ι R ⁅x, y⁆ =
    UniversalEnvelopingAlgebra.ι R x * UniversalEnvelopingAlgebra.ι R y -
      UniversalEnvelopingAlgebra.ι R y * UniversalEnvelopingAlgebra.ι R x at h
  rw [h]
  noncomm_ring

/-- Products consisting of a Lie relation followed by an enveloping word. -/
def rightRelationProducts (I : LieIdeal R F) : Set (UEA R F) :=
  {z | ∃ r : I, ∃ u : UEA R F,
    UniversalEnvelopingAlgebra.ι R (r : F) * u = z}

/-- The linear span of relation-on-the-left products. -/
def rightRelationSpan (I : LieIdeal R F) : Submodule R (UEA R F) :=
  Submodule.span R (rightRelationProducts R F I)

theorem relation_product_mem_rightRelationSpan (I : LieIdeal R F)
    (r : I) (u : UEA R F) :
    UniversalEnvelopingAlgebra.ι R (r : F) * u ∈ rightRelationSpan R F I := by
  exact Submodule.subset_span ⟨r, u, rfl⟩

/-- The span is closed under multiplication on the right. -/
theorem rightRelationSpan_mul_right (I : LieIdeal R F)
    {z : UEA R F} (hz : z ∈ rightRelationSpan R F I) (u : UEA R F) :
    z * u ∈ rightRelationSpan R F I := by
  induction hz using Submodule.span_induction with
  | mem z hz =>
      obtain ⟨r, v, rfl⟩ := hz
      rw [mul_assoc]
      exact relation_product_mem_rightRelationSpan R F I r (v * u)
  | zero => simp
  | add x y _ _ hx hy =>
      rw [add_mul]
      exact (rightRelationSpan R F I).add_mem hx hy
  | smul a x _ hx =>
      rw [Algebra.smul_mul_assoc]
      exact (rightRelationSpan R F I).smul_mem a hx

/-- Moving one Lie generator past a relation preserves the span. -/
theorem iota_mul_mem_rightRelationSpan (I : LieIdeal R F)
    (x : F) {z : UEA R F} (hz : z ∈ rightRelationSpan R F I) :
    UniversalEnvelopingAlgebra.ι R x * z ∈ rightRelationSpan R F I := by
  induction hz using Submodule.span_induction with
  | mem z hz =>
      obtain ⟨r, u, rfl⟩ := hz
      let xr : I := ⟨⁅x, (r : F)⁆, I.lie_mem r.property⟩
      have hcomm :
          UniversalEnvelopingAlgebra.ι R ⁅x, (r : F)⁆ =
            UniversalEnvelopingAlgebra.ι R x *
                UniversalEnvelopingAlgebra.ι R (r : F) -
              UniversalEnvelopingAlgebra.ι R (r : F) *
                UniversalEnvelopingAlgebra.ι R x := by
        exact LieHom.map_lie (UniversalEnvelopingAlgebra.ι R) x (r : F)
      have hidentity :
          UniversalEnvelopingAlgebra.ι R x *
                (UniversalEnvelopingAlgebra.ι R (r : F) * u) =
            UniversalEnvelopingAlgebra.ι R (r : F) *
                (UniversalEnvelopingAlgebra.ι R x * u) +
              UniversalEnvelopingAlgebra.ι R (xr : F) * u := by
        change _ = _ + UniversalEnvelopingAlgebra.ι R ⁅x, (r : F)⁆ * u
        rw [hcomm]
        noncomm_ring
      rw [hidentity]
      exact (rightRelationSpan R F I).add_mem
        (relation_product_mem_rightRelationSpan R F I r
          (UniversalEnvelopingAlgebra.ι R x * u))
        (relation_product_mem_rightRelationSpan R F I xr u)
  | zero => simp
  | add y z _ _ hy hz =>
      rw [mul_add]
      exact (rightRelationSpan R F I).add_mem hy hz
  | smul a y _ hy =>
      rw [mul_smul_comm]
      exact (rightRelationSpan R F I).smul_mem a hy

/-- The span is closed under arbitrary multiplication on the left. -/
theorem rightRelationSpan_mul_left (I : LieIdeal R F)
    (a : UEA R F) {z : UEA R F} (hz : z ∈ rightRelationSpan R F I) :
    a * z ∈ rightRelationSpan R F I := by
  revert z
  induction a using UEA.induction R F with
  | algebraMap r =>
      intro z hz
      rw [Algebra.algebraMap_eq_smul_one, smul_mul_assoc, one_mul]
      exact (rightRelationSpan R F I).smul_mem r hz
  | ι x =>
      intro z hz
      exact iota_mul_mem_rightRelationSpan R F I x hz
  | mul a b ha hb =>
      intro z hz
      rw [mul_assoc]
      exact ha (hb hz)
  | add a b ha hb =>
      intro z hz
      rw [add_mul]
      exact (rightRelationSpan R F I).add_mem (ha hz) (hb hz)

/-- The relation-on-the-left span bundled as a two-sided ideal. -/
def rightRelationIdeal (I : LieIdeal R F) : Ideal (UEA R F) where
  carrier := rightRelationSpan R F I
  zero_mem' := (rightRelationSpan R F I).zero_mem
  add_mem' := (rightRelationSpan R F I).add_mem
  smul_mem' a z hz := by
    change a * z ∈ rightRelationSpan R F I
    exact rightRelationSpan_mul_left R F I a hz

instance rightRelationIdeal_isTwoSided (I : LieIdeal R F) :
    (rightRelationIdeal R F I).IsTwoSided where
  mul_mem_of_left u hz := rightRelationSpan_mul_right R F I hz u

/-- The two-sided ideal generated by `I` equals the relation-on-the-left ideal. -/
theorem idealOfLieIdeal_eq_rightRelationIdeal (I : LieIdeal R F) :
    idealOfLieIdeal R F I = rightRelationIdeal R F I := by
  apply le_antisymm
  · intro z hz
    change z ∈ TwoSidedIdeal.span
      (Set.range fun r : I ↦ UniversalEnvelopingAlgebra.ι R (r : F)) at hz
    change z ∈ rightRelationSpan R F I
    induction hz using TwoSidedIdeal.span_induction with
    | mem z hz =>
        obtain ⟨r, rfl⟩ := hz
        simpa using relation_product_mem_rightRelationSpan R F I r 1
    | zero => exact (rightRelationSpan R F I).zero_mem
    | add x y _ _ hx hy => exact (rightRelationSpan R F I).add_mem hx hy
    | neg x _ hx => exact (rightRelationSpan R F I).neg_mem hx
    | left_absorb a x _ hx => exact rightRelationSpan_mul_left R F I a hx
    | right_absorb a x _ hx => exact rightRelationSpan_mul_right R F I hx a
  · intro z hz
    change z ∈ rightRelationSpan R F I at hz
    induction hz using Submodule.span_induction with
    | mem z hz =>
        obtain ⟨r, u, rfl⟩ := hz
        exact (idealOfLieIdeal R F I).mul_mem_right u
          (ι_mem_idealOfLieIdeal R F I r)
    | zero => exact (idealOfLieIdeal R F I).zero_mem
    | add x y _ _ hx hy => exact (idealOfLieIdeal R F I).add_mem hx hy
    | smul a x _ hx =>
        rw [Algebra.smul_def]
        exact (idealOfLieIdeal R F I).mul_mem_left _ hx

/-- Membership form of relation collection. -/
theorem mem_idealOfLieIdeal_iff_relation_sum (I : LieIdeal R F) (z : UEA R F) :
    z ∈ idealOfLieIdeal R F I ↔ z ∈ rightRelationSpan R F I := by
  rw [idealOfLieIdeal_eq_rightRelationIdeal R F I]
  rfl

/-- A collected relation is represented by an actual finite tagged sum. -/
theorem exists_relation_finsupp_of_mem_rightRelationSpan (I : LieIdeal R F)
    {z : UEA R F} (hz : z ∈ rightRelationSpan R F I) :
    ∃ c : (I × UEA R F) →₀ R,
      c.sum (fun p a ↦ a •
        (UniversalEnvelopingAlgebra.ι R (p.1 : F) * p.2)) = z := by
  have hset : rightRelationProducts R F I =
      Set.range (fun p : I × UEA R F ↦
        UniversalEnvelopingAlgebra.ι R (p.1 : F) * p.2) := by
    ext z
    constructor
    · rintro ⟨r, u, rfl⟩
      exact ⟨(r, u), rfl⟩
    · rintro ⟨⟨r, u⟩, rfl⟩
      exact ⟨r, u, rfl⟩
  rw [rightRelationSpan, hset] at hz
  exact Finsupp.mem_span_range_iff_exists_finsupp.mp hz

end

end LieRings.UEA
