import LieRings.Homological.LieHomology.ReducedExteriorUniversal
import LieRings.Homological.LieHomology.FreeVanishing
import Mathlib.LinearAlgebra.Isomorphisms

/-!
# Reduced exterior squares and presentations

For a surjective Lie homomorphism `p : F → L`, this file proves the exact quotient calculation

`Λ̃² L ≃ Λ̃² F / ⟨r Λ̃∧ x | r ∈ ker p, x ∈ F⟩`.

This is the module-theoretic middle step in the standard proof of the Hopf formula.
-/

universe u v w

namespace LieRings.Homological.LieHomology

noncomputable section

-- Nested quotients of exterior powers make the default typeclass budget too small; no proof
-- search is affected by this setting.
set_option linter.style.setOption false
set_option synthInstance.maxHeartbeats 100000

variable (R : Type u) {F : Type v} {L : Type w}
variable [CommRing R]
variable [LieRing F] [LieAlgebra R F] [LieRing L] [LieAlgebra R L]

/-- The submodule generated by reduced wedges having one entry in the relation kernel. -/
def relationWedges (p : LieHom R F L) :
    Submodule R (ReducedExteriorSquare R F) :=
  Submodule.span R {z | ∃ r ∈ LinearMap.ker p.toLinearMap, ∃ x : F,
    reducedWedge R F r x = z}

theorem relationWedge_mem (p : LieHom R F L) {r : F}
    (hr : r ∈ LinearMap.ker p.toLinearMap) (x : F) :
    reducedWedge R F r x ∈ relationWedges R p :=
  Submodule.subset_span ⟨r, hr, x, rfl⟩

/-- The quotient of the source reduced exterior square by the relation wedges. -/
abbrev ReducedExteriorPresentationQuotient (p : LieHom R F L) :=
  ReducedExteriorSquare R F ⧸ relationWedges R p

/-- The quotient class of a source reduced exterior-square element. -/
abbrev relationClass (p : LieHom R F L) :
    ReducedExteriorSquare R F →ₗ[R] ReducedExteriorPresentationQuotient R p :=
  (relationWedges R p).mkQ

/-- The reduced wedge of source elements, modulo wedges with a relation. -/
def wedgeModuloRelations (p : LieHom R F L) :
    F →ₗ[R] F →ₗ[R] ReducedExteriorPresentationQuotient R p :=
  (reducedWedge R F).compr₂ (relationClass R p)

@[simp]
theorem wedgeModuloRelations_apply (p : LieHom R F L) (x y : F) :
    wedgeModuloRelations R p x y = relationClass R p (reducedWedge R F x y) :=
  rfl

private theorem wedgeModuloRelations_isAlt (p : LieHom R F L) :
    (wedgeModuloRelations R p).IsAlt := by
  intro x
  rw [wedgeModuloRelations_apply, reducedWedge_self, map_zero]

private theorem relationKer_le_wedgeModuloRelations_ker (p : LieHom R F L) :
    LinearMap.ker p.toLinearMap ≤ LinearMap.ker (wedgeModuloRelations R p) := by
  intro r hr
  rw [LinearMap.mem_ker]
  apply LinearMap.ext
  intro x
  rw [LinearMap.zero_apply, wedgeModuloRelations_apply]
  exact (Submodule.Quotient.mk_eq_zero _).2 (relationWedge_mem R p hr x)

/-- The reduced wedge modulo relations, descended to the module quotient `F / ker p` in both
variables. -/
def quotientWedge (p : LieHom R F L) :
    (F ⧸ LinearMap.ker p.toLinearMap) →ₗ[R]
      (F ⧸ LinearMap.ker p.toLinearMap) →ₗ[R]
        ReducedExteriorPresentationQuotient R p :=
  (wedgeModuloRelations R p).liftQ₂
    (LinearMap.ker p.toLinearMap) (LinearMap.ker p.toLinearMap)
    (relationKer_le_wedgeModuloRelations_ker R p)
    ((wedgeModuloRelations_isAlt R p).isRefl.ker_flip ▸
      relationKer_le_wedgeModuloRelations_ker R p)

@[simp]
theorem quotientWedge_mk (p : LieHom R F L) (x y : F) :
    quotientWedge R p (Submodule.Quotient.mk x) (Submodule.Quotient.mk y) =
      relationClass R p (reducedWedge R F x y) := by
  rw [quotientWedge, LinearMap.liftQ₂_mk, wedgeModuloRelations_apply]

/-- The bilinear map on `L` obtained by transporting `quotientWedge` through the first
isomorphism theorem for the surjection `p`. -/
def presentationWedge (p : LieHom R F L) (hp : Function.Surjective p) :
    L →ₗ[R] L →ₗ[R] ReducedExteriorPresentationQuotient R p :=
  (quotientWedge R p).compl₁₂
    (p.toLinearMap.quotKerEquivOfSurjective hp).symm.toLinearMap
    (p.toLinearMap.quotKerEquivOfSurjective hp).symm.toLinearMap

@[simp]
theorem presentationWedge_apply_map (p : LieHom R F L) (hp : Function.Surjective p)
    (x y : F) :
    presentationWedge R p hp (p x) (p y) =
      relationClass R p (reducedWedge R F x y) := by
  rw [presentationWedge, LinearMap.compl₁₂_apply]
  change quotientWedge R p
      ((p.toLinearMap.quotKerEquivOfSurjective hp).symm (p.toLinearMap x))
      ((p.toLinearMap.quotKerEquivOfSurjective hp).symm (p.toLinearMap y)) = _
  rw [
    LinearMap.quotKerEquivOfSurjective_symm_apply,
    LinearMap.quotKerEquivOfSurjective_symm_apply, quotientWedge_mk]

private theorem presentationWedge_isAlt (p : LieHom R F L)
    (hp : Function.Surjective p) : (presentationWedge R p hp).IsAlt := by
  intro x
  obtain ⟨a, rfl⟩ := hp x
  rw [presentationWedge_apply_map, reducedWedge_self, map_zero]

private theorem presentationWedge_leibniz (p : LieHom R F L)
    (hp : Function.Surjective p) (x y z : L) :
    presentationWedge R p hp x ⁅y, z⁆ =
      presentationWedge R p hp ⁅x, y⁆ z + presentationWedge R p hp y ⁅x, z⁆ := by
  obtain ⟨a, rfl⟩ := hp x
  obtain ⟨b, rfl⟩ := hp y
  obtain ⟨c, rfl⟩ := hp z
  rw [← p.map_lie, ← p.map_lie, ← p.map_lie,
    presentationWedge_apply_map, presentationWedge_apply_map,
    presentationWedge_apply_map]
  simpa only [map_add] using
    congrArg (relationClass R p) (reducedWedge_leibniz R F a b c)

/-- The inverse-direction map in the presentation exactness theorem. -/
def reducedExteriorToPresentationQuotient (p : LieHom R F L)
    (hp : Function.Surjective p) :
    ReducedExteriorSquare R L →ₗ[R] ReducedExteriorPresentationQuotient R p :=
  reducedExteriorLift R L (presentationWedge R p hp)
    (presentationWedge_isAlt R p hp) (presentationWedge_leibniz R p hp)

@[simp]
theorem reducedExteriorToPresentationQuotient_wedge_map
    (p : LieHom R F L) (hp : Function.Surjective p) (x y : F) :
    reducedExteriorToPresentationQuotient R p hp (reducedWedge R L (p x) (p y)) =
      relationClass R p (reducedWedge R F x y) := by
  rw [reducedExteriorToPresentationQuotient, reducedExteriorLift_wedge,
    presentationWedge_apply_map]

private theorem relationWedges_le_reducedExteriorMap_ker (p : LieHom R F L) :
    relationWedges R p ≤
      LinearMap.ker (reducedExteriorMap (R := R) (L := F) (K := L) p) := by
  rw [relationWedges, Submodule.span_le]
  rintro _ ⟨r, hr, x, rfl⟩
  change reducedExteriorMap (R := R) (L := F) (K := L) p
      (reducedWedge R F r x) = 0
  rw [reducedExteriorMap_wedge]
  have hr0 : p r = 0 := hr
  rw [hr0, reducedWedge_zero_left]

/-- The map induced by `p` from the presentation quotient to the target reduced exterior
square. -/
def presentationQuotientToReducedExterior (p : LieHom R F L) :
    ReducedExteriorPresentationQuotient R p →ₗ[R] ReducedExteriorSquare R L :=
  (relationWedges R p).liftQ
    (reducedExteriorMap (R := R) (L := F) (K := L) p)
    (relationWedges_le_reducedExteriorMap_ker R p)

@[simp]
theorem presentationQuotientToReducedExterior_class (p : LieHom R F L)
    (x : ReducedExteriorSquare R F) :
    presentationQuotientToReducedExterior R p (relationClass R p x) =
      reducedExteriorMap (R := R) (L := F) (K := L) p x :=
  Submodule.liftQ_apply _ _ x

private theorem presentationQuotientToReducedExterior_comp_inverse
    (p : LieHom R F L) (hp : Function.Surjective p) :
    (presentationQuotientToReducedExterior R p).comp
      (reducedExteriorToPresentationQuotient R p hp) = LinearMap.id := by
  apply reducedExteriorMap_ext R L
  intro x y
  obtain ⟨a, rfl⟩ := hp x
  obtain ⟨b, rfl⟩ := hp y
  rw [LinearMap.comp_apply, reducedExteriorToPresentationQuotient_wedge_map,
    presentationQuotientToReducedExterior_class, reducedExteriorMap_wedge,
    LinearMap.id_apply]

private theorem inverse_comp_presentationQuotientToReducedExterior
    (p : LieHom R F L) (hp : Function.Surjective p) :
    (reducedExteriorToPresentationQuotient R p hp).comp
      (presentationQuotientToReducedExterior R p) = LinearMap.id := by
  apply LinearMap.ext
  intro z
  induction z using Submodule.Quotient.induction_on with
  | _ x =>
      change reducedExteriorToPresentationQuotient R p hp
          (presentationQuotientToReducedExterior R p (relationClass R p x)) =
        relationClass R p x
      rw [presentationQuotientToReducedExterior_class]
      have heq :
          (reducedExteriorToPresentationQuotient R p hp).comp
              (reducedExteriorMap (R := R) (L := F) (K := L) p) =
            relationClass R p := by
        apply reducedExteriorMap_ext R F
        intro a b
        rw [LinearMap.comp_apply, reducedExteriorMap_wedge,
          reducedExteriorToPresentationQuotient_wedge_map]
      exact LinearMap.congr_fun heq x

/-- Exactness of reduced exterior squares for a surjective presentation. -/
def reducedExteriorPresentationEquiv (p : LieHom R F L)
    (hp : Function.Surjective p) :
    ReducedExteriorSquare R L ≃ₗ[R] ReducedExteriorPresentationQuotient R p :=
  LinearEquiv.ofLinear (reducedExteriorToPresentationQuotient R p hp)
    (presentationQuotientToReducedExterior R p)
    (inverse_comp_presentationQuotientToReducedExterior R p hp)
    (presentationQuotientToReducedExterior_comp_inverse R p hp)

end

end LieRings.Homological.LieHomology
